### ISSUE TITLE
LRIS corrupt header crash

### ISSUE THREAD

**Issue by amanda-olmo** [pypeit/PypeIt#1007]
Corrupt header crash on LRIS data from 2010. The test dataset is available [here](https://drive.google.com/drive/folders/1gShaGi3mn6Dc07syKMLwLLC-7NufacGw?usp=sharing)

run_pypeit keck_lris_blue_A/keck_lris_blue_A.pypeit -o
[INFO]  :: Loading the reduction file
[INFO]  :: Found 4 raw data frames
[INFO]  :: Input file loaded successfully
[INFO]  :: Loaded spectrograph keck_lris_blue
[INFO]  :: Setting configuration-specific parameters using LB.20100107.41526.fits
[INFO]  :: Built full PypeIt parameter set.
[INFO]  :: Compiling metadata
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.
707 get_meta_value spectrograph.py
In [1]: exit                                             
[ERROR]  :: Required meta "lampstat01" did not load!You may have a corrupt header.
 
---------------------------------------------------------------------------
PypeItError                Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.0.7.dev0-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/run_pypeit in <module>
   2 # EASY-INSTALL-SCRIPT: 'pypeit==1.0.7.dev0','run_pypeit'
   3 __requires__ = 'pypeit==1.0.7.dev0'
----> 4 __import__('pkg_resources').run_script('pypeit==1.0.7.dev0', 'run_pypeit')
~/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py in run_script(self, requires, script_name)
  664     ns.clear()
  665     ns['__name__'] = name
--> 666     self.require(requires)[0].run_script(script_name, ns)
  667 
  668   def __iter__(self):
~/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py in run_script(self, script_name, namespace)
  1460       source = open(script_filename).read()
  1461       code = compile(source, script_filename, 'exec')
-> 1462       exec(code, namespace, namespace)
  1463     else:
  1464       from linecache import cache
~/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.0.7.dev0-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/run_pypeit in <module>
   15 if __name__ == '__main__':
   16   args = run_pypeit.parser()
---> 17   rtval = run_pypeit.main(args)
   18   sys.exit(rtval)
   19 
~/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.0.7.dev0-py3.7-macosx-10.9-x86_64.egg/pypeit/scripts/run_pypeit.py in main(args)
   82              redux_path=args.redux_path,
   83              calib_only=args.calib_only,
---> 84              logname=logname, show=args.show)
   85 
   86   # JFH I don't see why this is an optional argument here. We could allow the user to modify an infinite number of parameters
~/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.0.7.dev0-py3.7-macosx-10.9-x86_64.egg/pypeit/pypeit.py in __init__(self, pypeit_file, verbosity, overwrite, reuse_masters, logname, show, redux_path, calib_only)
  122     msgs.info('Compiling metadata')
  123     self.fitstbl = PypeItMetaData(self.spectrograph, self.par, files=data_files,
--> 124                    usrdata=usrdata, strict=True)
  125     #  - Interpret automated or user-provided data from the PypeIt
  126     #  file
~/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.0.7.dev0-py3.7-macosx-10.9-x86_64.egg/pypeit/metadata.py in __init__(self, spectrograph, par, files, data, usrdata, strict)
  112     # Build table
  113     self.table = table.Table(data if files is None 
--> 114                 else self._build(files, strict=strict, usrdata=usrdata))
  115 
  116     # Sort on filename
~/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.0.7.dev0-py3.7-macosx-10.9-x86_64.egg/pypeit/metadata.py in _build(self, files, strict, usrdata)
  192       for meta_key in self.spectrograph.meta.keys():
  193         value = self.spectrograph.get_meta_value(headarr, meta_key, required=strict, usr_row=usr_row,
--> 194                               ignore_bad_header=self.par['rdx']['ignore_bad_headers'])
  195         if isinstance(value, str) and '#' in value:
  196           value = value.replace('#', '')
~/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.0.7.dev0-py3.7-macosx-10.9-x86_64.egg/pypeit/spectrographs/spectrograph.py in get_meta_value(self, inp, meta_key, required, ignore_bad_header, usr_row, no_fussing)
  707             embed(header=utils.embed_header())
  708             msgs.error('Required meta "{0}" did not load!'.format(meta_key)
--> 709                  + 'You may have a corrupt header.')
  710         else:
  711           msgs.warn('Required card {0} missing '.format(self.meta[meta_key]['card'])
~/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.0.7.dev0-py3.7-macosx-10.9-x86_64.egg/pypeit/pypmsgs.py in error(self, msg, usage)
  265       self.usage(None)
  266     #
--> 267     raise PypeItError(msg)
  268     sys.exit(1)
  269 
PypeItError: Required meta "lampstat01" did not load!You may have a corrupt header.

**Comment by profxj** [comment]
@amanda-olmo -- I fussed with the Lamps issue in PR #1009 
I can confirm that part runs on your test data.  However,
the arc you included is off.  I suspect they didn't wait
for the lamps to warm up.  So, I was unable to run the
data through fully.

**Comment by profxj** [comment]
@amanda-olmo -- Is this Issue resolved?  If so, kindly close it
Thanks!
