### ISSUE TITLE
Dynamic ampsec, datasec, oscansec

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#102]
Consider making it possible to derive these sections 
from the Header instead of setting in the settings file.

**Comment by adwasser** [comment]
Isn't that what's currently done with LRIS through the arlris.read_lris function?  That would seemingly require a new function for each instrument (in which case, what's the point of the settings file?).

**Comment by profxj** [comment]
Fair point.  So let me give the example I'm most concerned about:
Kast blue/red

People change the windowing on those detectors all the time (myself included).
I'd hate to have to deal with this as a hard line in the settings file
and should prefer we have an automated way.

I'll also add that detectors change (are upgraded mainly).  We'll need to decide
whether to have a unique settings file for each or to handle this internally (maybe
with instrument specific modules like arlris).

**Comment by adwasser** [comment]
Would it be possible to generalize the arlris module to infer all of the ampsec etc. values from just the instrument settings file and the headers?

**Comment by rcooke-ast** [comment]
For instruments that are known to have reliable ampsec, datasec and oscansec in the headers, I'm all for reading this from the headers. The parsing should be relatively straightforward, and I'll do this in my revised parser.

I see I've just been assigned the job -- happy to do it!  :-)

**Comment by adwasser** [comment]
Is it sufficient to have just datasec and naxis1, naxis2?  DEIMOS doesn't define either ampsec or oscansec, and I can't find them for LRIS headers either.  Maybe look for the ampsec and oscansec headers, then if not found, infer from datasec with a warning.

**Comment by rcooke-ast** [comment]
I suppose, but this must then assume that the detector uses only 1 amplifier, and the user must provide dark/bias frames to subtract the bias level. This is probably not ideal. We could perhaps attempt to identify where the overscan region is from the data, but this is prone to error. Does DEIMOS have only 1 amplifier?

**Comment by adwasser** [comment]
DEIMOS has 1 amplifier per CCD detector (in a 4 x 2 mosaic).
