### ISSUE TITLE
BitMask docs and script(s)

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#1034]
We need to document (on `readthedocs`) the meanings
of the various BitMasks, especially those for the 2D image 
(`ImageBitMask`).  

Would also be good to add a script that reads the bitmask 
from a `spec2d` obj and prints the values to the screen, 
e.g. in case they have an older output and `ImageBitMask` evolves.

**Comment by profxj** [comment]
A quick suggestion from Kyle:

Grab from the header of the file.  E.g.:

```
from pypeit.bitmask import BitMask
bm = BitMask(hdu[1].header['IMGBITM'].split(','))
bm.flagged_bits(256)
```

**Comment by kbwestfall** [comment]
This is nearly the same as #936 , right?  I'll put something together this afternoon.

**Comment by profxj** [comment]
Yes, good point.  Thanks!

**Comment by kbwestfall** [comment]
See #1035
