### ISSUE TITLE
Calibration check is not crashing with a sensible error message for standards that don't have required calibs

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1060]
The following PypeIt file does not have arcs and tilts. It should crash as it following the calibration check. This works for science files, but not for standards. Neither run_pypeit nor run_pypeit -c works for this PypeIt file. Note the data is the keck_mosfire/Y_long data so to reproduce this bug, copy this pypeit file to that directory and run. 

[keck_mosfire_y_long_bug1.pypeit.txt](https://github.com/pypeit/PypeIt/files/5432607/keck_mosfire_y_long_bug1.pypeit.txt)

**Comment by profxj** [comment]
Re-open if you can provide a test dataset
