### ISSUE TITLE
Overlapping alignment boxes

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#1061]
When 2 or more alignment boxes overlap,
merge them into one if using slitmask information
(e.g. DEIMOS) to identify them.

**Comment by profxj** [comment]
@deborape -- was this addressed?

**Comment by debora-pe** [comment]
@profxj This was addressed in PR #1065 

Instead of merging overlapping alignment boxes into one, PypeIt traces each alignment box and, to avoid that the edges cross, those edges are placed adjacent to one other.
