### ISSUE TITLE
Example of desired functionality for MOSFIRE darks. 

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1067]
This PypeIt file has an example of the behavior that we want for MOSFIRE darks. It should be self-explanatory
based on the comments in the pypeit file. Note that as constructed this PypeIt file runs, although the 
interface for subtracting darks from trace flats is cumbersome. It also reveals a bug, since the MasterDark is 
constructed with the wrong set of images. 

The science files are in the Google Drive link that I've emailed you. 

[keck_mosfire_Y_dark_example.pypeit.txt](https://github.com/pypeit/PypeIt/files/5451943/keck_mosfire_Y_dark_example.pypeit.txt)

Thanks!

**Comment by kbwestfall** [comment]
I think this has been addressed.
