### ISSUE TITLE
We need a background frametype. Example PypeIt file is attached. 

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1068]
I was under the impression we added a 'background' frametype, but just realized that we don't have one. The attached
PypeIt file illustrates why this is needed for near-IR observations or any other observations where we difference images. The comments explain the usage case. 

The data to run this example has been sent to @kbwestfall and @profxj by e-mail. 

[keck_mosfire_Y_bg_example.pypeit.txt](https://github.com/pypeit/PypeIt/files/5451971/keck_mosfire_Y_bg_example.pypeit.txt)

Thanks!

**Comment by kbwestfall** [comment]
Just a heads up: I started to try to address this and #1067 , and I think we need to talk this through.  I originally thought this was going to be relatively straight-forward.  I.e., it's easy enough to add a new frame type.  But after digging in a bit, I think there are significant control-flow considerations.  I may be missing something though, so let's talk about it at the next telecon.

**Comment by jhennawi** [comment]
Resolved by PR #1071
