### ISSUE TITLE
Pypeit_identify fails in version 1.2 - unexpected keyword argument 'binspectral'

### ISSUE THREAD

**Issue by jpsub** [pypeit/PypeIt#1075]
Hello.  I've recently upgraded to a PypeIt version 1.2 environment and attempted to run pypeit_identify to make adjustments to the automated wavelength calibration solution but received the following error.

Traceback (most recent call last):
  File "/home/john/anaconda3/envs/pypeit/bin/pypeit_identify", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/john/Software/PypeIt/bin/pypeit_identify", line 10, in <module>
    identify.main(identify.parse_args())
  File "/home/john/Software/PypeIt/pypeit/scripts/identify.py", line 90, in main
    wavecal = WaveCalib(msarc, slits, spec, par, binspectral=slits.binspec, det=args.det,
TypeError: __init__() got an unexpected keyword argument 'binspectral'

I've poked around but don't see anything blatantly obvious in the WaveCalib class code.  I'm happy to provide the MasterArc and MasterSlit files if that's helpful.  Any pointers would be greatly appreciated!  Thanks in advance!

**Comment by profxj** [comment]
This is correct.  `identify.py` has been refactored in 
PR #1058 and will make it to `master` in `v1.3`

**Comment by profxj** [comment]
It is on `develop` now, if you can negotiate onto that branch.

**Comment by profxj** [comment]
With better docs:  https://pypeit.readthedocs.io/en/develop/wave_calib.html

**Comment by jpsub** [comment]
Thank you for the prompt response.  I've committed the develop branch and have re-run.  I get the following message.

Traceback (most recent call last):
  File "/home/john/anaconda3/envs/pypeit_devel/bin/pypeit_identify", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/john/Software/PypeIt_Devel/PypeIt/bin/pypeit_identify", line 10, in <module>
    identify.main(identify.parse_args())
  File "/home/john/Software/PypeIt_Devel/PypeIt/pypeit/scripts/identify.py", line 52, in main
    from pypeit.core.gui.identify import Identify
  File "/home/john/Software/PypeIt_Devel/PypeIt/pypeit/core/gui/__init__.py", line 2, in <module>
    from pypeit.core.gui import identify
  File "/home/john/Software/PypeIt_Devel/PypeIt/pypeit/core/gui/identify.py", line 15, in <module>
    from pypeit.core.wavecal import wv_fitting, waveio, wvutils, templates
  File "/home/john/Software/PypeIt_Devel/PypeIt/pypeit/core/wavecal/templates.py", line 24, in <module>
    from pypeit import wavecalib
  File "/home/john/Software/PypeIt_Devel/PypeIt/pypeit/wavecalib.py", line 24, in <module>
    from pypeit.core.gui.identify import Identify
ImportError: cannot import name 'Identify' from partially initialized module 'pypeit.core.gui.identify' (most likely due to a circular import) (/home/john/Software/PypeIt_Devel/PypeIt/pypeit/core/gui/identify.py)

I've confirmed that the PypeIt version I'm running is v1.2.1dev.  As always, thanks in advance!

**Comment by profxj** [comment]
Right you are.   Forgot I had fixed it in another branch
(still in dev).  So have issued a Hotfix  PR #1076

**Comment by profxj** [comment]
Ok @jpsub -- Please try again on `develop`
and thanks for your patience.

**Comment by profxj** [comment]
ps.  what instrument are you working on ?

**Comment by jpsub** [comment]
Thanks @profxj!  I was able to run identify and assign lines (I needed to comment out the requirement check for PySide2, it's installed but was failing).  I saved the line identification to waveid.ascii but was unable to store the solution after using "q" to exit the GUI.  Here's the error I received.

  File "/home/john/anaconda3/envs/pypeit_devel/bin/pypeit_identify", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/john/Software/PypeIt_Devel/PypeIt/bin/pypeit_identify", line 10, in <module>
    identify.main(identify.parse_args())
  File "/home/john/Software/PypeIt_Devel/PypeIt/pypeit/scripts/identify.py", line 124, in main
    arcfitter.store_solution(final_fit, mdir, slits.binspec,
TypeError: store_solution() got an unexpected keyword argument 'specname'

I am reducing Shane Kast data.  By the way, many thanks to your team for this excellent reduction package!

**Comment by profxj** [comment]
Right you are @jpsub 

Can you jump on the `identify_fussing` branch and see if that fixes it?
Thanks.

**Comment by jpsub** [comment]
Hello @profxj.  Yes, working from that branch allowed the solution to be stored.  I placed the saved fits file in the reid_arxiv directory to be called with method=reidentify.  There were some issues with how that file was read, presumably because the format is slightly different from what the parser expects (i.e., waveio.load_reid_arxiv).  I'm sure you have a new method of parsing this file but for now, I made the following changes to the parser (line 119 of waveio.py) to get things to run end-to-end (in case this helps anyone in the interim).

        par = None
        wv_tbl = Table.read(calibfile, hdu=2)
        o_tbl = Table.read(calibfile, hdu=3)
        wv_calib_arxiv = OrderedDict()
        nrow = wv_tbl['wave_fit'].shape[0]
        for irow in np.arange(nrow):
            wv_calib_arxiv[str(irow)] = {}
            wv_calib_arxiv[str(irow)]['spec'] = wv_tbl['spec']
            wv_calib_arxiv[str(irow)]['wave_soln'] = wv_tbl['wave_soln']
            wv_calib_arxiv[str(irow)]['order'] = o_tbl['order']

Thanks again for your efforts to get me running through my data!

**Comment by profxj** [comment]
@jpsub -- What setup are you using?
I should like to add your solution if it will help the community.

**Comment by jpsub** [comment]
Absolutely!  This setup was for Kast's red channel using grating 300/7500 tilted to angle 3795 (spectral coverage ~4600-9700 Angstrom).  The lamps used were HgI,CdI,HeI,ArI.  See attached plot for solution.  Three of the stronger lines at pixel values ~800-1000 are misidentified (should be 6440.249 CdI, 6679.995 HeI, and 7067.138 HeI) but these wavelengths were not selectable when using pypeit_identify.  Despite this, the solution is quite good but I'd be happy to improve it if there's  a way to include these lines.

![Arc_1dfit_B_1_01_S0245](https://user-images.githubusercontent.com/52169014/98570792-a8de0d80-2268-11eb-8137-040f3bbc5869.png)

**Comment by profxj** [comment]
Nice!  Can you meet me on the PypeIt User's Slack
so I can ask a few more questions and grab some files?

**Comment by jpsub** [comment]
Certainly.  I've logged in to the PypeIt User's Slack but am new there so not sure where to navigate.
