### ISSUE TITLE
Generating setup files

### ISSUE THREAD

**Issue by codebreaker2** [pypeit/PypeIt#1098]

**Comment by codebreaker2** [comment]
I am reducing LRIS red data.  The detectors were read out in single amp mode because one of the detectors is failing.   I believe the WARNING about the bad header can be ignored because there are no extensions [3] and [4].

What does the rest of the error message mean?

![error_pypeit_setup](https://user-images.githubusercontent.com/47435481/101426581-1d30be80-38b2-11eb-9e97-c4d1f30b87dd.jpeg)

And it made an empty setup file.

[keck_lris_red_2020-Dec-07.pypeit.txt](https://github.com/pypeit/PypeIt/files/5656281/keck_lris_red_2020-Dec-07.pypeit.txt)

Do you recommend that I edit the setup file manually?  Or are there bigger issues that need to be solve first?

Thanks!

**Comment by profxj** [comment]
Please join the Pypeit Users Slack:

https://github.com/pypeit/PypeIt/issues/676

and discuss there
