### ISSUE TITLE
Wish-list / suggestions for not_alfosc

### ISSUE THREAD

**Issue by dmalesani** [pypeit/PypeIt#1110]
To whom it may concern. First, congratulations for such a great work, we are enthusiastic of your pipeline in our group. We are now using pypeit to reduce the data from NOT/ALFOSC. As it may be expected, we have noticed a couple of issues with the classification of the data. I take the freedom to offer some feedback, with the obvious understanding that no work is expected unless you deem it useful.

- The main issue is that the NOT images contain two sets of RA/DEC keywords: the usual RA and DEC, plus OBJRA and OBJDEC. Pypeit, as defined in not_alfosc.py , adopts OBJRA and OBJDEC. The problem is that OBJRA is expressed in decimal **hours**, so that the coordinates are interpreted incorrectly. This leads to problems for example with recognizing standard stars, as well as propagating the wrong coordinates in the header of the products. So, there seem to be two possible solutions here: one can use RA and DEC in place of OBJRA and OBJDEC, which seems very easy to implement - the disadvantage being that RA and DEC are the pointing coordinates (not the target coordinates), and may differ slightly (~10 arcseconds) from the actual target coordinates. Alternatively, it would be enough to multiply by 15 the value of OBJRA to get the target RA in degrees.

- A second, less serious issue, is that specphot standard stars are not recognized. This is easily fixed, by modifying manually the not_alfosc_?.pypeit file and changing the classification of the relevant files to "standard". However, I would like to point out that there exists the "IMAGETYP" keyword in the header of the NOT files stating whether the observation is of a standard star. I wonder if this information could be incorporated for automatic recognition. For reference, *among others values*, IMAGETYP can be:
- BIAS (raw bias)
- FLAT,LAMP (halogen / spectroscopic flat field)
- OBJECT (science object)
- OBJECT,SLIT (through-slit image of a science object) 
- STD (standard star)
- STD,SLIT (through-slit image of a standard star)
- WAVE,LAMP (wavelength calibration spectrum).

I enclose a file from NOT/ALFOSC with the described headers, maybe it's useful: https://www.dropbox.com/s/anaklo7wpzvps0c/aldk080138.fits.gz?dl=0

- Finally, but to be fair this is not really an issue of pypeit, the NOT provides a large number of unnecessary calibration files (especially the bias frames). Bias frames come in many sizes, often not matching the science data size. Currently pypeit is not capable to discard these mismatched bias frames, which leads to the pipeline stopping (understandably so!). I think it is up to the user to manually remove all files with wrong size (size different than the science frames). However, should you be interested in trying the pipeline to make some of the work, I'd be happy to discuss about this further. In practice, a filter based on NAXIS1 and NAXIS2 could be considered but I don't know if that's practical to implement).

- This is quite a lot already. I also wanted to mention that we are converting in a pypeit form all the "official" spectroscophotometric standard stars (from http://www.not.iac.es/instruments/alfosc/fluxstandard.html ) in a format that can be ingested by pypeit. We would be very happy to share them with you and other users.

Best wishes and thank you in advance,
Daniele Malesani
malesani@space.dtu.dk

**Comment by profxj** [comment]
Great suggestions @dmalesani !

And, as you say, most of these are easy to implement (maybe all).
Enough so, that I'd encourage you to open a PR on them.  But if
you prefer, I can meet you half way and to the development provided
you test on your end.

Let me know.  Maybe, ideally, by joining the PypeIt Users Slack.
Thanks

**Comment by profxj** [comment]
The first two items `OBJRA` and `STD` are being addressed
in the branch `odds_and_ends`

**Comment by profxj** [comment]
done
