### ISSUE TITLE
Append, not overwrite, spec1d.txt file

### ISSUE THREAD

**Issue by marlageha** [pypeit/PypeIt#1116]
A request to append results to the spec1d*.txt, similar to what is current done for spec2d and spec1d*fits files.   In context of DEIMOS, if separate CCD chips are run together the metadata is written to the spec1d*.txt file.  If chips are run separately, spec1d*tx is overwritten for one chip only.

**Comment by profxj** [comment]
if we simply append, we'll get `det=1` over and over again
i.e. for everytime you rerun the code.Is that ok ? 

If not, we may need to turn it into a Table or JSON
and fuss with it as an object.

**Comment by debora-pe** [comment]
Solved!
