### ISSUE TITLE
masking telluric regions in sensfunc

### ISSUE THREAD

**Issue by aburgasser** [pypeit/PypeIt#1123]
sensfunc maskes out H I lines, but is there a way to mask out the telluric bands as well? I'm getting a lot of bad residuals in the sensitivity application because the ESO cals contain the telluric absorption features.

I'm using the ESO data file for Hiltner 600 (please add!): https://www.eso.org/sci/observing/tools/standards/spectra/hilt600.html

Here's before flux cal of a G2 star:
![Screen Shot 2021-01-08 at 7 00 25 PM](https://user-images.githubusercontent.com/5667900/104081523-07315900-51e4-11eb-8d80-194a88f790a5.png)

Here's after:
![Screen Shot 2021-01-08 at 7 00 40 PM](https://user-images.githubusercontent.com/5667900/104081524-0f899400-51e4-11eb-93e1-bd5f2bb58437.png)

Should I just edit out the telluric regions from the ESO dat file?

**Comment by profxj** [comment]
See: 


https://pypeit.readthedocs.io/en/latest/telluric.html
https://pypeit.readthedocs.io/en/latest/fluxing.html

and note that the next release of PypeIt (in ~1 month)
will include numerous improvements to fluxing.

**Comment by jhennawi** [comment]
Hi @aburgasser, 

I just sent you an invitation to the Pypeit Users Slack. I am happy to help you fix this issue. The fluxing algorithms have been improved. 

Joe

**Comment by aburgasser** [comment]
OK, I'll follow up on slack I guess, but I had installed this the day I sent the message so I'm pretty sure I was using the most up to date version.

**Comment by aburgasser** [comment]
mmm, also I can't seem to find you on the slack channel Joe!
