### ISSUE TITLE
Sensitivity function fitting region of wavelength?

### ISSUE THREAD

**Issue by HojinCho** [pypeit/PypeIt#1125]
In my data, the blue & red ends of the spectrum tend not to be flat-fielded well, that including this region for fitting the sensitivity makes the sensitivity blow up at the edges. If I could just remove 100 angstroms or so from each end, I believe it'd work nicely.

So, is it currently possible to limit the wavelength range while using the `pypeit_sensfunc` script?

Alternatively, is it possible to trim images for specified regions of the CCD at any stage of the reduction? Or to make a mask to cover specific region?
(I tried adding `datasec` to the `setup` of my `.pypeit` file, as well as tweaking a lot of different parameters, but they seem to do nothing.)

**Comment by profxj** [comment]
@jhennawi -- please comment

**Comment by jhennawi** [comment]
We have a function that takes care of this now, it is called tweak_standard and can be added to the spectrograph file and implemented for the setup in question. See e.g.: 

https://github.com/pypeit/PypeIt/blob/release/pypeit/spectrographs/shane_kast.py

line 498
