### ISSUE TITLE
Month representation with non-US locale

### ISSUE THREAD

**Issue by HojinCho** [pypeit/PypeIt#1126]
PypeIt represents any date as `%Y-%b-%d` (e.g., 2021-Jan-14) or anything including 3-letter months. This works until if anyone tries to use it on a machine with a non-US locale, where `%b` can include  white-spaces and non-ASCII characters. These strings involving `%b` are used to name files, write headers, and so on, making it impossible to run the scripts until they are rid of. 

I suggest any of the following:

1. Use ISO 8601 (I'm currently using this method w/o problem.)
Replace `%Y-%b-%d` with `%Y-%m-%d` will make it ISO 8601 compliant. (e.g., 2021-Jan-14 -> 2021-01-14)
Of course there are non-standard strings such as the one in `par/util.py:578`, so they also should be made ISO-compliant to make date-formatting consistent. 

2. Force locale to be `en-US` (not tested.)
Since the problem arises from `%b` acting differently depending on the locale, forcing locale to be `en-US` would be a solution. Either using `locale` or using `babel` package seems to do the trick.

I attach the list of `*.py` files involving `%b` (some of them are in comments, and some of them are deprecated, but I included them for completeness).

```
doc/conf.py:194:#html_last_updated_fmt = '%b %d, %Y'
pypeit/data/arc_lines/convert_NIST_to_lists.py:194:        f.write('# Creation Date: {:s}\n'.format(str(datetime.date.today().strftime('%Y-%b-%d'))))
pypeit/core/wavecal/waveio.py:505:        f.write('# Creation Date: {:s}\n'.format(str(datetime.date.today().strftime('%Y-%b-%d'))))
pypeit/core/qa.py:130:    tstamp = datetime.datetime.today().strftime('%Y-%b-%d-T%Hh%Mm%Ss')
pypeit/scripts/flux_setup.py:136:            f.write('# {0}\n'.format(time.strftime("%a %d %b %Y %H:%M:%S", time.localtime())))
pypeit/par/util.py:578:        f.write('# {0}\n'.format(time.strftime("%a %d %b %Y %H:%M:%S",time.localtime())))
pypeit/metadata.py:466:                                           datetime.datetime.strftime(dtime, '%Y%b%dT'),
pypeit/pypeitsetup.py:210:        date = str(datetime.date.today().strftime('%Y-%b-%d'))
pypeit/spec2dobj.py:370:        hdr['DATE-RDX'] = str(datetime.date.today().strftime('%Y-%b-%d'))
pypeit/deprecated/pypsetup.py:313:#        #date = str(datetime.date.today().strftime('%Y-%b-%d'))
pypeit/deprecated/save.py:233:        prihdu.header['DATE-RDX'] = str(datetime.date.today().strftime('%Y-%b-%d'))
pypeit/deprecated/arsciexp.py:180:                         datetime.datetime.strftime(dtime, '%Y%b%dT') + \
```

**Comment by tepickering** [comment]
strong endorse for making all time strings ISO 8601 compliant. in addition to non-US local issues, using month strings screws up sorting when using shell utilities.

**Comment by profxj** [comment]
done
