### ISSUE TITLE
Not progressing past wavelength calibration

### ISSUE THREAD

**Issue by JBanister242** [pypeit/PypeIt#1141]
Hi, I'm a PhD student and fairly new to pypeit.

I'm trying to reduce some x-shooter data and I'm running into trouble when it tries to perform the wavelength calibration.

The code runs well and i get Masters for Arc, Dark, Edges, Slits, and Tiltimg. After this I get some run time error warnings when extracting the approximate arc spectrum along each slit but the code continues. The problem is when wave calibration starts i get this message for each slit:

"
←[1;31m[WARNING] ::←[0m ←[1;34md:\programdata\anaconda3\envs\pypeit\lib\site-packages\pypeit\core\wavecal\autoid.py 1276 report_final()←[0m - ---------------------------------------------------
             Final report for slit 0/15:
               Wavelength calibration not performed!
"

It then runs this line
"
←[1;32m[INFO]    ::←[0m ←[1;34md:\programdata\anaconda3\envs\pypeit\lib\site-packages\pypeit\wavecalib.py 526 echelle_2dfit()←[0m - Fitting 2-d wavelength solution for echelle....
Traceback (most recent call last):
"

after this it immediately crashes out printing a traceback with the final error: 
"
ValueError: zero-size array to reduction operation minimum which has no identity
"

I can't seem to progress any further than this. Any help with this would be greatly appreciated.

**Comment by profxj** [comment]
@JBanister242 -- Join the PypeIt Users Slack and seek help
