### ISSUE TITLE
Dither definition of X-Shooter data incorrect

### ISSUE THREAD

**Issue by JBanister242** [pypeit/PypeIt#1142]
Hi, I'm having an issue where the vlt_xshooter.py script defines dither as "HIERARCH ESO SEQ CUMOFF Y" but this is present in none of my x-shooter science spectra data headers, and I can't seem to find what x-shooter defines the dither as. The closest I have in the headers for the actual science spectra are:
HIERARCH ESO SEQ ARM         = 'NIR     '   / Instrument Arm                    
HIERARCH ESO SEQ CUMOFF DEC  =    -2.032167 / Cumulative DEC offset             
HIERARCH ESO SEQ CUMOFF RA   =     1.456124 / Cumulative RA offset              
HIERARCH ESO SEQ OBS TYPE    = 'OBJECT  '   / List of observation types (Object,
HIERARCH ESO SEQ RELOFF DEC  =    -4.064334 / List of DEC offsets               
HIERARCH ESO SEQ RELOFF RA   =     2.912249 / List of RA offsets             

Any suggestions as to what I should be defining dither as would be greatly appreciated. I'm not sure if this is an issue with the x-shooter data I have or if the pypeit scripts' definition is out of date.

**Comment by jhennawi** [comment]
Hi @JBanister242, 

Thanks for pointing this out. Can you please check the header cards for the data we have in the development suite in the vlt_xshooter folder and see if the header cards have someone changed for X-shooter. Also, which are are you trying to reduce VIS or NIR? 

https://drive.google.com/drive/folders/1oh19siB1-F0jjmY-F_jr73eA-TQYEiFW?usp=sharing

The dithers are not being used to determine how to reduce the data. You the user do this by hand, but the dither information is in there to assist with setting the comb_id and bk_id for NIR reductions.

**Comment by JBanister242** [comment]
Hi @jhennawi

The header cards have the values for CUMOFF Y for the NIR data but not for VIS which I'm assuming is fine as you only use it for NIR

I'm using both NIR and VIS (and UVB) and none of my data has the value. Would you think it would be an issue if I just commented it out of the x-shooter script or would it cause problems later on? when I comment it out the furthest the reduction process will go is wavelength calibration where it stops working but I don't think that's related.

Cheers,
Jamie

**Comment by profxj** [comment]
I believe this was addressed by #1172
