### ISSUE TITLE
Reidentify fails for long-slit spectrograph without specifying `ech_fix_format = False`

### ISSUE THREAD

**Issue by tbowers7** [pypeit/PypeIt#1155]
I am working to add a long-slit spectrograph to PypeIt.  When experimenting with wavelength calibration methods, I tried `reidentify` using an arxiv file I had just created using `pypeit_identify` (on the same master arc spectrum used for the reduction).

One issue I came across with `reidentify` has to do with default parameter values in `pypeit.par.pypeitpar.WavelengthSolutionPar`.  Namely, while the parameter `echelle` is false by default, the parameter `ech_fix_format` is true by default.  While this would seem to not affect long-slit spectrographs, there is logic code within pypeit/core/wavecal/autoid.py that uses only `ech_fix_format` without also checking to see if the spectrograph is, indeed, an echelle.  Since I am not using an echelle spectrograph, I do not have orders specified, and the code exits in an error stating, "If the specrograph is a fixed-format echelle (ech_fix_format is True), the orders must be provided."

I have drafted a possible solution (commit 8cdea5cfc97e7bca42cd49cafd97052da579fb36), but am not sure what side effects this additional `AND` logic might have for other instruments.

The other solution, of course, is to simply specify `ech_fix_format = False` in the instrument-definition class for each non-echelle spectrograph that wishes to use the `reidentify` wavelength calibration method.

**Comment by profxj** [comment]
@jhennawi -- Any thoughts on this one?

**Comment by tbowers7** [comment]
This issue could possibly be rescinded / closed?

A more careful reading of the WaveCal documentation seems to indicate that spectrographs employing adjustable gratings should not be using the `reidentify` WaveCal method, but rather the `full_template` method.  Since this is the type of spectrograph I am working to add to PypeIt, this particular issue is moot for me.

This issue could still affect non-echelle fixed-format spectrographs, where the `reidentify` WaveCal method is still appropriate.  I am not qualified to address this point.

**Comment by profxj** [comment]
ok, closing
