### ISSUE TITLE
pypeit_identify doesn't save solution

### ISSUE THREAD

**Issue by Raindogjones** [pypeit/PypeIt#1158]
After Xavier's talk at the MAAT DS workshop last week, I've been experimenting with adding the GTC-OSIRIS spectrograph to PypeIt and seem to have everything working nicely for one of the gratings and the holy-grail method (my fork of the release branch is here https://github.com/Raindogjones/PypeIt ).  Moving on to a second grating, the holy-grail method fails to get the correct solution so I tried to fix this by running pypeit_identify on the MasterArc and MasterSlits outputs from the previous run, using:
pypeit_identify Masters/MasterArc_B_1_02.fits Masters/MasterSlits_B_1_02.fits.gz --lamps XeI,HgI,NeI --wmin 4500 --wmax 6050 --force_save
This works fine for the identification and dispersion relation fitting (getting a solution that I think should save even without the --force_save), also allowing me to save the line IDs to waveid.ascii, but upon exiting the gui I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/pypeit_identify", line 33, in <module>
    sys.exit(load_entry_point('pypeit', 'console_scripts', 'pypeit_identify')())
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/scripts/identify.py", line 131, in entry_point
    main(parse_args())
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/scripts/identify.py", line 124, in main
    arcfitter.store_solution(final_fit, mdir, slits.binspec,
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/core/gui/identify.py", line 672, in store_solution
    self.save_IDs()
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/core/gui/identify.py", line 1175, in save_IDs
    self.update_infobox(message="Line IDs saved as: {0:s}".format(fname), yesno=False)
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/core/gui/identify.py", line 1101, in update_infobox
    self.canvas.draw()
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_tkagg.py", line 10, in draw
    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/_backend_tk.py", line 75, in blit
    photoimage.blank()
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 4068, in blank
    self.tk.call(self.name, 'blank')
_tkinter.TclError: invalid command name "pyimage12"

I wondered whether it might be something to do with tk not playing nicely on my mac, but I get the same error running with python3.7 with native tk, 3.8 with native tk, and 3.9 with homebrew tk.  I don't have access to another architecture to check further. 

Note that even though this is for a spectrograph that isn't supported, I haven't touched anything in identify/wavecalib/etc.  I've only added GTC to the list of telescopes (in par/pypeitpar.py and in telescopes.py) and gtc_osiris to the list of spectrographs (in spectrographs/__init__.py and spectrographs/gtc_osiris.py).

Also, I tried running run_pypeit with [calibrations] [[wavelengths]] method='identify' but this just opens an ipython prompt that I'm not sure what to do with.

Thanks!

**Comment by jhennawi** [comment]
Hi @Raindogjones, 

Thanks for posting this issue. pypeit_identify is in great need of testing and so I appreciate your work on this. I think the best thing to do at this point would be: 

1) Post a .pypeit file culled down to the minimum amount of data to reproduce your bug, and also the data. 

2) Provide a README file with the steps required to reproduce the crash. 

Another thing you could try is to reproduce this bug on a different OS, but I'm not sure if you have such a machine available. 

Thanks!

**Comment by Raindogjones** [comment]
Hi @jhennawi,
Thanks for the quick reply!  Unfortunately, I don't have access to another OS or not easily at least.

As the data is from a spectrograph that isn't currently supported, I guess it would be easiest to first test pypeit_identify as a "stand-alone" with the MasterArc and MasterSlit from the run_pypeit run that successfully produced them (but failed to find the correct wavelength solution).  So, I've uploaded (to anonymous ftp) the MasterArc at ftp://ftp.iac.es/out/pypeit/MasterArc_B_1_02.fits and the MasterSlit at ftp://ftp.iac.es/out/pypeit/MasterSlits_B_1_02.fits.gz and the waveids at ftp://ftp.iac.es/out/pypeit/waveid.ascii

Recipe to reproduce (or not) the error:
-"pypeit_identify MasterArc_B_1_02.fits MasterSlits_B_1_02.fits.gz --lamps XeI,HgI,NeI --wmin 4500 --wmax 6050 --force_save"
-"l" to load lines from waveid.ascii
-"++" to increase the fit order to 3
-"q" to quit

**Comment by rcooke-ast** [comment]
Thanks for all the helpful details @Raindogjones - I’ll investigate this next week! As @jhennawi said, this is a relatively new script made for development use, and not fully tested, so it’s not surprising to find a unique way to crash it!!

**Comment by rcooke-ast** [comment]
@Raindogjones - I suspect this is a matplotlib issue... do you know what version of matplotlib you are running? I'm running `3.1.3`.

**Comment by Raindogjones** [comment]
@rcooke-ast Thanks for looking into this! I'm running `3.3.4`

**Comment by rcooke-ast** [comment]
No problems @Raindogjones - I am unable to reproduce the error, which makes it a little tricky to resolve... I think the problem is that the GUI gets killed before the line IDs get output, and a message that gets sent to the GUI can't get printed. To see if this is indeed the problem, can you please put in the following `try except` in `pypeit/core/gui/identify.py`. If nothing else, this might help you to proceed with your reduction until we find a more permanent solution.
![image](https://user-images.githubusercontent.com/12585758/111077734-16859900-84ea-11eb-8c23-82238181c557.png)

**Comment by Raindogjones** [comment]
Hi @rcooke-ast, I still get the same error with "screen was killed" never being printed.

Perhaps I'm not understanding what the final output of the gui should be?  It does output the line IDs in the form of waveid.ascii, but I was expecting it to save the wavelength solution to something like MasterWaveCalib.fits so that I could return to run_pypeit and have that used in the reduction.  Is this not the case?

Alternatively, is there a way for me to supply something like waveid.ascii to the WavelengthSolutionPars?  I tried copying the identifications as IDpixels and IDwaves to my pypeit file, but it seems as though they get ignored.  Do I need to set another 'method' (I currently have it left as 'holy-grail') for them to be recognised?

Otherwise, I guess this must be an OS X/tkinter problem.

**Comment by Raindogjones** [comment]
I guess some of this discussion might be better to have via the slack.  Any chance I could get an invite? Thanks!

**Comment by rcooke-ast** [comment]
Sure thing - request an invite here: https://github.com/pypeit/PypeIt/issues/676

**Comment by Raindogjones** [comment]
In the meantime, digging into wavecalib.py, I see that IDpixels and IDwaves are only used by method='simple'.  So, I guess that might solve my issues.  It's getting a bit late here, so I'll give that a shot tomorrow.

**Comment by rcooke-ast** [comment]
Thanks for trying out the simple solution, and sorry that the try/except didn't work... I'm still pretty sure it's because the window gets terminated before it's finished drawing, and probably we need to update the animate method, something like [this](https://stackoverflow.com/a/11505034/7432) (more for my record, than anyone else's!).

**Comment by Raindogjones** [comment]
`method='simple'` also fails, I'm afraid!  Here's the error:

[INFO]    :: arc.py 478 get_censpec() - Extracting approximate arc spectrum along the center of slit 0
[WORK IN ]::
[PROGRESS]:: arc.py 1123 simple_calib() - Detecting lines..
[INFO]    :: arc.py 1139 simple_calib() - Using input lines to seed the wavelength solution
[INFO]    :: arc.py 1144 simple_calib() - Will apply a median offset of 2.93994e-09 pixels
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4502.24
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4525.95
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4584.03
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4625.57
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4672.53
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4735.48
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4808.36
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4831.06
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4844.64
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4917.88
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       4924.53
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5332.26
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5402.06
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5462.27
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5771.21
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5792.28
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5854.11
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5883.53
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5946.48
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       5977.19
[INFO]    :: arc.py 1170 simple_calib() - Identifying arc line:       6031.67
Traceback (most recent call last):
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/datamodel.py", line 1011, in __getattr__
    return self.__getitem__(item)
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/datamodel.py", line 1070, in __getitem__
    return self.__dict__[item]
KeyError: 'copy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/run_pypeit", line 33, in <module>
    sys.exit(load_entry_point('pypeit', 'console_scripts', 'run_pypeit')())
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/scripts/run_pypeit.py", line 126, in entry_point
    main(parse_args())
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/scripts/run_pypeit.py", line 113, in main
    pypeIt.calib_all()
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/pypeit.py", line 279, in calib_all
    self.caliBrate.run_the_steps()
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/calibrations.py", line 753, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/calibrations.py", line 693, in get_wv_calib
    self.wv_calib = self.waveCalib.run(skip_QA=(not self.write_qa))
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/wavecalib.py", line 642, in run
    self.wv_calib = self.build_wv_calib(self.arccen, self.par['method'], skip_QA=skip_QA)
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/wavecalib.py", line 427, in build_wv_calib
    final_fit = arc.simple_calib_driver(line_lists, arccen, ok_mask_idx,
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/core/arc.py", line 1098, in simple_calib_driver
    wv_calib[str(slit)] = iwv_calib.copy()
  File "/Users/djones/Documents/GitHub/PypeIt/pypeit/datamodel.py", line 1013, in __getattr__
    raise AttributeError('{0} is not an attribute of {1}!'.format(item,
AttributeError: copy is not an attribute of WaveFit!

**Comment by Raindogjones** [comment]
To update, I managed to get hold of a linux machine on which to test pypeit_identify and I get essentially the same error (for reference, matplotlib v3.1.2 and TkVersion 8.6):

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 216, in process
    func(*args, **kwargs)
  File "/home/flori/.local/lib/python3.8/site-packages/pypeit/core/gui/identify.py", line 808, in key_press_callback
    self.operations(event.key, axisID, event)
  File "/home/flori/.local/lib/python3.8/site-packages/pypeit/core/gui/identify.py", line 938, in operations
    self.canvas.draw()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 10, in draw
    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_tk.py", line 80, in blit
    photoimage.blank()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4065, in blank
    self.tk.call(self.name, 'blank')
_tkinter.TclError: invalid command name "pyimage10"
Would you like to store the line IDs? (y/n): y
WARNING: AstropyDeprecationWarning: waveid.ascii already exists. Automatically overwriting ASCII files is deprecated. Use the argument 'overwrite=True' in the future. [astropy.io.ascii.ui]
[INFO]    :: Line IDs saved as:
             waveid.ascii
Traceback (most recent call last):
  File "../.local/bin/pypeit_identify", line 8, in <module>
    sys.exit(entry_point())
  File "/home/flori/.local/lib/python3.8/site-packages/pypeit/scripts/identify.py", line 131, in entry_point
    main(parse_args())
  File "/home/flori/.local/lib/python3.8/site-packages/pypeit/scripts/identify.py", line 124, in main
    arcfitter.store_solution(final_fit, mdir, slits.binspec,
  File "/home/flori/.local/lib/python3.8/site-packages/pypeit/core/gui/identify.py", line 672, in store_solution
    self.save_IDs()
  File "/home/flori/.local/lib/python3.8/site-packages/pypeit/core/gui/identify.py", line 1175, in save_IDs
    self.update_infobox(message="Line IDs saved as: {0:s}".format(fname), yesno=False)
  File "/home/flori/.local/lib/python3.8/site-packages/pypeit/core/gui/identify.py", line 1101, in update_infobox
    self.canvas.draw()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 10, in draw
    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_tk.py", line 80, in blit
    photoimage.blank()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4065, in blank
    self.tk.call(self.name, 'blank')
_tkinter.TclError: invalid command name "pyimage10"

**Comment by rcooke-ast** [comment]
Thanks @Raindogjones - I'm going to try different versions of TK to see if I can reproduce the error. I haven't noticed anything on the PypeIt Slack, but I can share the calibration files with you via Slack, if that's helpful in the near term.

I think the `simple_calib` might be deprecated... Most of time, it should be a matter of using either the holy grail method (this is a really tricky problem, and works if you're lucky!) or a combination of identify+reid_archive which works all (...most) of the time.

**Comment by Raindogjones** [comment]
@rcooke-ast That would be great, thanks!  I'd then at least be able to use pypeit for the two OSIRIS setups that I personally have data in (the other works fine with holy-grail).

I ran some tests on the rest of the offered GTC-OSIRIS setups, holy-grail seems to work for about half and fails for the rest.  So, I'd like to sort out the reid_archive files for them *all* before submitting a pull request to merge in the changes.  I could send you all the arcs, slits and waveids, but it would be nice to figure out why I can't run identify myself.  Let me know if there is anything I can do to help. Thanks again!

**Comment by Raindogjones** [comment]
Aha! I think I've solved the problem!

Seeing the error messages about the matplotlib backend and tkagg, I manually changed by mpl backend my matplotlibrc file to qt5agg and voila, it worked!  Suppose this should have been obvious given that the install page explains everything is built on QT but I didn't twig that it could cause a conflict.

**Comment by rcooke-ast** [comment]
Ahh, that's great news! I wonder if you could send me what you have in your matplotlibrc file, so I can reproduce it, and hopefully implement a workaround that "overwrites" the default definitions in the rc file. Thanks a bunch - I never would have looked at that...

You could send it to me on Slack, or paste the relevant line of code in the rc file here...

**Comment by Raindogjones** [comment]
My matplotlibrc was just `backend: TkAgg` and swapping that for `backend: Qt5Agg` worked.  It's very easy to override that just by adding `matplotlib.use('Qt5Agg')` to core/gui/identify.py after importing matplotlib but before importing pyplot, but I don't know if that would cause an issue if the user has PySide2 rather PyQt5 installed.

**Comment by profxj** [comment]
Word on the street is that this can be solved by
simply updating to the latest version of `PyQt5`
