### ISSUE TITLE
Current manual extraction is not useful for dithered spectra

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1170]
According to the manual extraction documented in the readthedocs and the example in the dev suite (vlt_xshooter_vis_manual.pypeit) the manual extraction will not work at all if the users dither their spectra (in other words our current implementation is useless in the IR, or if there is any flexure, or if users dither). 

The current implementation uses parset parameters, which means one set of manual extractions per pypeit file. Clearly this needs to be modified to allow for a set of manual extraction parameters per image. I thought this was implemented, but I do not see any documentation of it, so I assume it is not.  

There appears to be a pypeit file with something along these lines implemented, although it is not documented anywhere. See gemini_gmos_gn_ham_r400_885.pypeit. We should check whether this is working properly.

**Comment by finagle29** [comment]
The per-file manual extraction via .pypeit file approach looks to be quite old and no longer supported (removed [here](https://github.com/pypeit/PypeIt/pull/974/files?file-filters%5B%5D=.py#diff-ffa7c536601514a4e8f574cb125cc2d8c66f899639b01684089c9259564ce2ccL659) and code to parse the manual extraction specification in the pypeit file removed [here](https://github.com/pypeit/PypeIt/pull/1050/files?file-filters%5B%5D=.py&file-filters%5B%5D=No+extension#diff-1591c1a2b02857f63a0186a7238eb24da83ac04b6b418019fc99568d53d07778L216)).

**Comment by kbwestfall** [comment]
Addressed in #1275.  Closing.
