### ISSUE TITLE
Obj find 'bug'

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#1183]
On occasion, when using `moment1d` to smash a slit for object finding,
there are junk edges (see attached for a DEIMOS example; det=7 for
keck_deimos/830G_M_8500).

I found I could kludge a fix by increasing the threshold used in 
constructing to `mask_spec` from 0.3 to 0.8.  But this is probably
not the best fix.

![image (15)](https://user-images.githubusercontent.com/3998093/117862537-978db200-b247-11eb-8585-399824a350c1.png)

**Comment by jhennawi** [comment]
@profxj this a multislit setup but you didn't specify the slit that is problematic, making this hard to debug. Can you please provide that info.

**Comment by profxj** [comment]
It's been awhile.  But as I remember it, two slits crash and burn and aren't reduced.
So, if you run it through, just pick one of those.

And maybe I listed it in Slack.  Can't remember..

**Comment by kbwestfall** [comment]
Please re-open if this is still an issue.
