### ISSUE TITLE
Missing telluric data when installing from conda

### ISSUE THREAD

**Issue by shriharshtendulkar** [pypeit/PypeIt#1187]
I'm facing this issue with `pypeit` when running `sens_func`. It doesn't find the telluric spectrum where it should be: 
```  
 File "/opt/miniconda3/envs/pypeit/lib/python3.8/site-packages/pypeit/core/telluric.py", line 1960, in __init__
    self.tell_dict = self.read_telluric_grid(wave_min = self.wave_in_arr[wv_gpm].min(), wave_max=self.wave_in_arr[wv_gpm].max())
  File "/opt/miniconda3/envs/pypeit/lib/python3.8/site-packages/pypeit/core/telluric.py", line 2289, in read_telluric_grid
    return read_telluric_grid(self.telgridfile, wave_min=wave_min, wave_max=wave_max, pad_frac=pad_frac)
  File "/opt/miniconda3/envs/pypeit/lib/python3.8/site-packages/pypeit/core/telluric.py", line 154, in read_telluric_grid
    hdul = io.fits_open(filename)
  File "/opt/miniconda3/envs/pypeit/lib/python3.8/site-packages/pypeit/io.py", line 769, in fits_open
    return fits.open(filename, **kwargs)
  File "/opt/miniconda3/envs/pypeit/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 162, in fitsopen
    raise ValueError(f'Empty filename: {name!r}')
ValueError: Empty filename: None
```

I looked at the directory where the telluric files should be:
`/opt/miniconda3/envs/pypeit/lib/python3.8/site-packages/pypeit/data/telluric/atm_grids`
but it only has a README directing me to the pypeit installation page, which has nothing on telluric data. 

I installed a new conda environment and installed pypeit directly from conda. Is there something I should have done differently?

**Comment by finagle29** [comment]
The doc page with the correct info is here https://pypeit.readthedocs.io/en/release/fluxing.html#troubleshooting

Either the install docs should be updated to mention the telluric data google drive, `atm_grids/README` should be updated to include this link.

**Comment by profxj** [comment]
@kbwestfall -- was this addressed in your last PR?

**Comment by kbwestfall** [comment]
Yes, but the update to the installation doc and the associated scripts haven't been merged from `develop` to `release` yet.

**Comment by profxj** [comment]
Got it.  Can you link this to your PR (i.e. reference it here)?

**Comment by kbwestfall** [comment]
Yep, see #1234 .  And preview the new installation specifics here:

https://pypeit.readthedocs.io/en/develop/installing.html#additional-data

**Comment by jhennawi** [comment]
Installation docs now explain where to get this data.
