### ISSUE TITLE
Script pypeit_collate1d is not populating output file with correct DEIMOS detectors

### ISSUE THREAD

**Issue by marlageha** [pypeit/PypeIt#1190]
Running pypeit_collate1d on DEIMOS data, the detector column in the output file 'by_object_meta.dat' is not populated right.   The detector column repeats the blue detectors twice (1-4), rather than showing both the blue and red detector numbers which have been combined.   The output written directly to screen is correct.   I am using the by_object_meta.dat file to confirm that spectra in both detectors has been extracted.

**Comment by profxj** [comment]
And this.

**Comment by badpandabear** [comment]
Corrected by https://github.com/pypeit/PypeIt/pull/1196
