### ISSUE TITLE
suggestions to install on readthedocs

### ISSUE THREAD

**Issue by astronomeara** [pypeit/PypeIt#1191]
For those that cut n paste into the command line from readthedocs, I recommend the following

1. 
virtualenv pypeit source pypeit/bin/activate

should become

virtualenv pypeit 

source pypeit/bin/activate

2.
pip install "pypeit[pyqt5]"
 
should become

pip install pypeit[pyqt5]

(same for the pyside2) (

similar to 1:

conda create -n pypeit python=3.8 conda activate pypeit

goes to

conda create -n pypeit python=3.8 
conda activate pypeit

**Comment by jhennawi** [comment]
Changes made!
