### ISSUE TITLE
Suggestion for pypeit_collate1d 

### ISSUE THREAD

**Issue by marlageha** [pypeit/PypeIt#1193]
For DEIMOS, pypeit_collate1d is fragile.  That is, the whole script fails if a single slit in a given mask fails.  So far, the script has only run to completion on 2 of 10 DEIMOS masks I've run so far (these were dense masks though).   The failures all occur in the pypeit_1dcoadd part of the script and tend to be lousy slits (but lousy in various different ways).   Can we consider run the co-addition as a try/except: pypeit_1dcoadd?    If a slit fails, then just keep moving on rather than crashing the full collate1d process.

**Comment by profxj** [comment]
Was this corrected, @badpandabear ?
Just checking.

**Comment by badpandabear** [comment]
Yes, this was corrected with https://github.com/pypeit/PypeIt/pull/1196
