### ISSUE TITLE
Correction in documentation for `pypeit_coadd_2dspec` script

### ISSUE THREAD

**Issue by santoshmh** [pypeit/PypeIt#1205]
In the documentation file for `pypeit_coadd_2dspec` (https://pypeit.readthedocs.io/en/latest/coadd2d.html#), the example for _coadd2d_ file contains an error: the data block should start and end as ‘spec2d read’ and ‘spec2d end’, respectively.

**Comment by debora-pe** [comment]
@santoshmh this issue was addresses. It is now in the `develop` branch (https://pypeit.readthedocs.io/en/develop/coadd2d.html).

@profxj please confirm if you agree.

**Comment by profxj** [comment]
Confirmed.
