### ISSUE TITLE
Script entry_points and spectrographs + scripts `__init__` cleanup

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#1206]
Following from #1200, we'd like to clean-up how the script entry_points are collected into `setup.cfg`, and how all the relevant modules are loaded in the `__init__.py` files in the `pypeit/scripts` and `pypeit/spectrographs` directories.  Here's one of the relevant comments from @tepickering in response to #1200:

> it looks like we can at least use the file: directive in setup.cfg to load its entry_points config: https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html. might also be worth looking at the capabilities for dynamic discovery that importlib.metadata provides: https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html#dynamic-discovery-of-services-and-plugins. it looks like that might be a cleaner way of doing what you do in __init__.py. it would at least enable all the entry_point configuration to be defined in one place, setup.cfg or a file it loads.

**Comment by tepickering** [comment]
i think the way to go is to generate the `entry_points` configuration at build time in `setup.py`. this would be done before the `setup()` call at the end and can use the trick to recurse through `ScriptBase` subclasses to find them. the `setup.cfg` file's `[options.entry_points]` section would then point to that generated file using the `file:` directive described above. i'll see if i can carve out a bit of time this week to give this idea a bash...

**Comment by profxj** [comment]
@tepickering -- did we do this?  Seems like we have.

**Comment by tepickering** [comment]
no, we're still defining `entry_points` manually in `setup.cfg`. the python packaging ecosystem is moving away from `setup.*` and towards `pyproject.toml` (PEP 621). that also doesn't provide any way to dynamically build an `entry_points` config and i don't see any sign of support for a `file:` directive in the documentation. that all said, in the current `setup.cfg` there are a few `entry_points` that are commented out as well as descriptive comments and grouping of gui and non-gui `entry_points`. so there is some value in the current way of doing things.
