### ISSUE TITLE
same maskid

### ISSUE THREAD

**Issue by sinataamoli** [pypeit/PypeIt#1231]
I'm reducing keck_deimos data. When I do:
`pypeit_setup -r [path to raw data]/ -s keck_deimos -c A`
I get this error: 
`...
left_edgeloss[i] = (expected_slitlen[obj_maskdef_id == maskid] - measured_slitlen[i]) / 2.  # pixels
ValueError: setting an array element with a sequence.`
When I printed "maskid" at this line, I got an array in which there were two same elements (maskid), so `[obj_maskdef_id == maskid]` returns two values.
Does anyone know how to solve this problem?

- Here is the full traceback

<img width="718" alt="Screen Shot 2021-07-16 at 7 21 04 PM" src="https://user-images.githubusercontent.com/40503658/126022436-74e434aa-ae83-4647-9c8d-06431f98fcda.png">

**Comment by debora-pe** [comment]
Hi @sinataamoli this bug should be fixed now. Please, pull in the latest changes in the `develop` branch  and try it again. Let me know if you still have this problem.

**Comment by jhennawi** [comment]
Closing now, if it is still an issue we can reopen it.
