### ISSUE TITLE
Gemini GMOS-N Wavelength Calibration Issue

### ISSUE THREAD

**Issue by oconnorb** [pypeit/PypeIt#1232]
Hello,

I am a new user of pypeit using the software on Gemini GMOS-N long-slit spectra (gemini_gmos_north_ham). I identified an issue with the wavelength calibration where the same lines are being identified in each detector even though the arc lines are clearly different visually. Is this a known issue and are there any recommendations to fix this? 

Below I display the commands for my .pypeit folder as well as the wavlength calibration .png files for Det01, Det02, and Det03.

Thank you in advance, 
Brendan
____________________________

Arc_1dfit_C_1_01_S0384
![Arc_1dfit_C_1_01_S0384](https://user-images.githubusercontent.com/56123351/126519517-d474b600-a2ae-46de-a5c6-e88680b30c20.png)

Arc_1dfit_C_1_02_S0386
![Arc_1dfit_C_1_02_S0386](https://user-images.githubusercontent.com/56123351/126519560-4731a384-77f9-4d1b-8c86-e72d711d0d9d.png)

Arc_1dfit_C_1_03_S0386
![Arc_1dfit_C_1_03_S0386](https://user-images.githubusercontent.com/56123351/126519573-6ec070d5-1685-45c1-a8e2-bb33ea03e06a.png)

Below are the commands added to the .pypeit file: (it does not keep the indenting when I paste here unfortunately)

[rdx]
    spectrograph = gemini_gmos_north_ham
[baseprocess]
    use_biasimage = False
    sigclip = 3
    lamaxiter = 5
    cr_sigrej = 5
[calibrations]
    [[biasframe]]
        [[[process]]]
            apply_gain = False
            combine = median
            use_biasimage = False
            use_pixelflat = False
            use_illumflat = False
    [[darkframe]]
        [[[process]]]
            apply_gain = False
            use_biasimage = False
            use_overscan = False
            use_pixelflat = False
            use_illumflat = False
    [[arcframe]]
        [[[process]]]
            cr_sigrej = -1
            use_pixelflat = False
            use_illumflat = False
    [[tiltframe]]
        [[[process]]]
            cr_sigrej = -1
            use_pixelflat = False
            use_illumflat = False
    [[pixelflatframe]]
        [[[process]]]
            combine = median
            satpix = nothing
            use_pixelflat = False
            use_illumflat = False
    [[alignframe]]
        [[[process]]]
            satpix = nothing
            cr_sigrej = -1
            use_pixelflat = False
            use_illumflat = False
    [[traceframe]]
        [[[process]]]
            use_pixelflat = False
            use_illumflat = False
    [[illumflatframe]]
        [[[process]]]
            satpix = nothing
            use_pixelflat = False
            use_illumflat = False
    [[skyframe]]
        [[[process]]]
            mask_cr = True
    [[standardframe]]
        [[[process]]]
            mask_cr = True
    [[wavelengths]]
        method = full_template
        lamps = CuI, ArI, ArII
        rms_threshold = 0.4
        nsnippet = 1
    [[slitedges]]
        det_min_spec_length=0.1
        fit_min_spec_length=0.1
        fit_order = 3
    [[tilts]]
        tracethresh = 10.0
[scienceframe]
    [[process]]
        mask_cr = True
[reduce]
    [[skysub]]
        bspline_spacing = 0.8
    [[findobj]]
        sig_thresh = 5.0
    [[extraction]]
        boxcar_radius = 3.0
[flexure]
    spec_method = boxcar
[sensfunc]
    multi_spec_det = 1, 2, 3

**Comment by profxj** [comment]
Yes, this is a known issue.  It should be resolved
when we start mosaicing the 3 detectors instead of
treating them independently.  That work is underway
and I anticipate will complete this month (August) or next.

**Comment by kbwestfall** [comment]
GMOS now uses mosaic reductions.  Closing.
