### ISSUE TITLE
documentation for optional parameters for settings files

### ISSUE THREAD

**Issue by tiffanyhsyu** [pypeit/PypeIt#124]
I've set up documentation for creating the most basic settings .pypit file (titled "setup"), and am trying to figure out the best way to write documentation for all additional optional parameters that can be put in the settings files.

An option is to start a new .rst file to include documentation, and organize them by dictionaries as in arload.py?

Seeing if anyone has opinions on what would be most useful as a PYPIT user!

**Comment by rcooke-ast** [comment]
This seems fine to me, and that's a good idea to start a new document for all allowed reduction parameters, and organize it by dictionary (alphabetical order is probably best). Organizing it like the index of a book makes for easy lookup.

Perhaps an rst file called "reduction parameters" or just "parameters", or "settings". The third option seems the most sensible, given that the files are called settings.blah...

**Comment by rcooke-ast** [comment]
Closing this issue, because @kbwestfall has addressed this in a recent PR.
