### ISSUE TITLE
WD Standards

### ISSUE THREAD

**Issue by Will-Cooper** [pypeit/PypeIt#1250]
Hi,

I have a weird list of standards from a years old observing run on GTC-Osiris; which I'm trying to run this pipeline on. Results look great thus far, but I've just been getting to the stage of flux calibration and of my standards:

- G158-100
- G191-B2B
- GD140
- GD153
- GD248
- Hiltner 600
- Ross 640

I believe most of them have their comparative spectra/ models in the calspec/eso list, except GD140 (which is in the NOAO list, so I'm hoping that'll work) and Ross 640, which I can only find on the [ING spectroscopic standards list](http://www.ing.iac.es/Astronomy/observing/manuals/html_manuals/tech_notes/tn065-100/r640.html), with spectra from Oke 1974. Naturally, my 'test' object uses Ross 640 as it's standard so I was hoping to get the full reduction procedure working with that object before I proceed with the full sample (most other objects are worse signal etc).
Any ideas on how to proceed with this?

**Comment by rcooke-ast** [comment]
Addressed by PR #1422, I believe... closing.
