### ISSUE TITLE
Issue combining MOSFIRE frames of different sequences in the data reduction

### ISSUE THREAD

**Issue by guidorb** [pypeit/PypeIt#1252]
Hi, I'm using the development version of Pypeit (v1.4.3.dev4+gdc93fd370) and when running run_pypeit with a .pypeit file on some MOSFIRE data, the code crashes as it passes from one ABBA sequence to another. The various sequences reduce fine on their own when handled separately, but when handled together in the same pypeit file the code crashes for some reason. I attach a screenshot of the error and can send a pypeit file along with the necessary data to reproduce the issue on the Slack channel.
![Screenshot 2021-08-17 at 14 59 32](https://user-images.githubusercontent.com/26487354/130502318-69c8cd89-5db3-49a0-a563-0e44c3beccc2.png)

**Comment by debora-pe** [comment]
This issue has been addressed in PR #1254.
Closing it.
