### ISSUE TITLE
Frametype Background not recognized

### ISSUE THREAD

**Issue by prappleizer** [pypeit/PypeIt#1265]
The documentation for `pypeit` indicates there is a frametype `background` which if specified won't be reduced and will be used to sky subtract, e.g., for near-IR data. 

When I use this frametype, I get an error: 
```
ValueError: The following bit names are not recognized: background
```
I am not sure if I am missing something; I tried installing the development version from github to see if it was a new feature, but that hasn't fixed it either. My .pypeit file looks identical to the example provided. 

Additionally, is there any way for the background setup for near-IR data to handle on-off exposures? Assuming the "background" frametype were to work, it doesn't seem like you can specify for each "on" frame to use the combination of the previous and subsequent exposures ("off") as background --- because the exposure after *that* will want to combine its previous frame with its subsequent one for subtraction. For example, if frames are off1-on1-off2-on2-off3-on3-off4, I would want on1 - combined(off1,off2), on2 - (off2,off3), on3 - (off3,off4).

**Comment by profxj** [comment]
I don't see any discussion of a `background` frametype here:

https://pypeit.readthedocs.io/en/release/frametype.html

I think you want something like A-B subtraction, as described here:

https://pypeit.readthedocs.io/en/release/A-B_differencing.html

If that doesn't serve your needs, I suggest you jump on the PypeIt Users Slack
to discuss further.

**Comment by prappleizer** [comment]
Hi, thanks for the quick response. The reference to the `background` frametype is in the A-B differencing page you just linked.

**Comment by jhennawi** [comment]
Hi @prappleizer, 

Check out the vlt_sinfoni pypeit file here for an example of what you want to do: 

https://github.com/pypeit/PypeIt-development-suite/blob/master/pypeit_files/vlt_sinfoni_k_0.8.pypeit

The background frametype is actually called sky. We need to fix that documentation -- apologies for that. If you feel like submitting a pull request to update the docs we would appreciate it!
