### ISSUE TITLE
Need updated / corrected dev suite data for VLT_FORS2?

### ISSUE THREAD

**Issue by tbowers7** [pypeit/PypeIt#1266]
I’m trying to track down the weird `vlt_fors2` error I was getting in `test_setups.py` (see discussion in PR #1258).

The root of the error seems to stem from a lack of proper calibrations for all setups, as reported by `chk_for_calibs`.

Using the dev suite `RAW_DATA/vlt_fors2/300I` files just pulled from the Google Drive, I get 5 distinct configurations:
```
##########################################################
Setup A
     dispname: None
    dispangle: None
       decker: lSlit1_0arcsec
     detector: CHIP1
##########################################################
Setup B
     dispname: GRIS_300I
    dispangle: 857.5
       decker: lSlit1_0arcsec
     detector: CHIP1
##########################################################
Setup C
     dispname: GRIS_300I
    dispangle: 857.5
       decker: lSlit1_0arcsec
     detector: CHIP2
##########################################################
Setup D
     dispname: None
    dispangle: None
       decker: lSlit1_0arcsec
     detector: CHIP2
##########################################################
Setup E
     dispname: GRIS_300I
    dispangle: 857.5
       decker: LSS_1.0_arcsec
     detector: CHIP1
```
The `chk_for_calibs` passes for setup E, but not for any of the others.  I suspect there should only be 3 setups (A+B, C+D, E).

Can anyone confirm getting 5 setups?

Also, I’ve added a test for `vlt_fors2` to `test_chk_calibs.py` in my branch `tbowers7/PypeIt:fix_test_fors2`.  Can someone fork/copy that test to see if it passes for you?

Is this a case of needing corrected data on the Google Drive?  In particular, 7/30 files in this directory are missing the FITS keywords `HIERARCH ESO INS GRIS1 NAME` and `HIERARCH ESO INS GRIS1 WLEN` (used for configuration grouping).

**Comment by profxj** [comment]
Not reproduced.
