### ISSUE TITLE
MasterFrame calibration bits cannot be easily associated with the calib ids and files used to create them

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1270]
For near-IR reduction there is often a long list of arcs and tilts associated with many different calib IDs (since we get arcs and tilts from the OH sky lines). In this situation one needs to be able to know for example which QA files correspond to which set of frames. This is currently impossibly given the bits used to name the MasterFiles. 

An easy solution would be a script that prints out this information (maybe it is in the headers). A more elegant solution would be some kind of string identified that could be converted into the filenames used.

**Comment by profxj** [comment]
Done
