### ISSUE TITLE
Check data matches spectrograph

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#1276]
If possible, can we implement code early on in `run_pypeit` that makes some nominal checks that the data in the pypeit file matches certain expectations from the user-designated spectrograph?  Easy to chalk it up to user error, but this recently happened and the error message was far too obtuse.

**Comment by profxj** [comment]
We can and probably should do queries against `INSTRUME` in the header.
  For those instruments that provide it..
