### ISSUE TITLE
Color blind friendly plotting

### ISSUE THREAD

**Issue by freddavies** [pypeit/PypeIt#1281]
I recently gave a PypeIt tutorial, and a color blind colleague noted that they could not see the red slit edges in the ginga viewer at all, as they cannot tell the difference between black and bright red. Similarly, they could not see the masked pixels in the 2D tilts QA. 

It would probably be worth adjusting the color palette to be more visible for such folks.

**Comment by profxj** [comment]
https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

**Comment by debora-pe** [comment]
addressed in PR #1285.
Closing this.
