### ISSUE TITLE
Correct "Flexure Correction" documentation

### ISSUE THREAD

**Issue by tbowers7** [pypeit/PypeIt#1283]
The flexure correction documentation (https://pypeit.readthedocs.io/en/latest/flexure.html#flexure) states that spectral flexure correction is enabled by default.

However, the default FlexurePar key `spec_method` actually defaults to `skip`.  This parameter is set to either `boxcar` or `slitcen` for the following spectrographs only:
* Gemini/GMOS (N&S)
* Keck DEIMOS
* Keck KCWI
* Keck LRIS (all)
* LBT MODS (all)
* MMT Binospec
* NTT EFOSC2
* Shane KAST (all)
* VLT FORS2

**Comment by debora-pe** [comment]
Addressed in PR #1285 
Closing this.

**Comment by tbowers7** [comment]
Thanks for adding this!
