### ISSUE TITLE
Collate1d request for heliocentric correction option

### ISSUE THREAD

**Issue by marlageha** [pypeit/PypeIt#1318]
Collate1d request to add a second of two features:   For stellar work, I do not correct the single exposure wavelength arrays for heliocentric velocities.   However, in the coadded spectra, I'd like the option to apply this correction, especially in co-adding exposures from different nights of the same mask.

**Comment by profxj** [comment]
@badpandabear -- was this addressed?
  if so, please close.  And the other one before it.    Thanks!

**Comment by badpandabear** [comment]
@profxj I started this but it hasn't been completed.

**Comment by kbwestfall** [comment]
Looks like this has been addressed.  Please re-open if not.
