### ISSUE TITLE
Add a PypeIt loader to SpecUtils

### ISSUE THREAD

**Issue by tbowers7** [pypeit/PypeIt#1327]
As discussed in #1263 and related conversation among the development team, it would be helpful to add a loader for PypeIt spec1d FITS files to the Astropy-coordinated SpecUtils package.

I know various PypeIt developers and users have created their own SpecUtils "[custom loader](https://specutils.readthedocs.io/en/stable/custom_loading.html)" for PypeIt data, but having a PypeIt-sponsored default loader would bring closer integration and expose the broader community of SpecUtils users to PypeIt.

I have built a working loader for PypeIt `MultiSlit` 1D spectra [in a SpecUtils fork](https://github.com/tbowers7/specutils/blob/add_pypeit_loader/specutils/io/default_loaders/pypeit.py).  The custom loaders others have built may be more elegant, but this is functioning for my needs (works with my own `LDT/DeVeny` data and Cooked `Keck/DEIMOS` data).

How to move forward:

- Discuss whether the PypeIt team wants to support a loader for 1D spectra into SpecUtils in the first place.
- If yes, should PypeIt create its own fork of SpecUtils to develop the full-featured loader and submit the SpecUtils PR -- or should such a loader come from one individual associated with PypeIt?
- If this moves forward, we will need a test in PypeIt that ensures the output from the pipeline is always loadable in SpecUtils via the default loader.
- From those who are more familiar with the `Echelle` and `IFU` pipelines, loaders for these 1D data will be needed.

I am willing to be a coordinator for this issue, but will need assistance from those who are more intimately familiar with PypeIt and its data products.

**Comment by tepickering** [comment]
having some familiarity with `specutils`, i'd be happy to help with this. i'll try to take a look at your specutils fork later today...

**Comment by profxj** [comment]
I support this and can help where needed.
Meet on Slack to discuss further

**Comment by kbwestfall** [comment]
Where are we on this?  Should we revive the discussion?

**Comment by tbowers7** [comment]
Added in #1562 .
