### ISSUE TITLE
sensfunc error - Kast red

### ISSUE THREAD

**Issue by wynnjacobson-galan** [pypeit/PypeIt#1343]
Hi there, 

I get the following error when I try to generate a sensitivity function on the red side of kast: 

`UnboundLocalError: local variable 'gpm_out' referenced before assignment`

Can you help with this?

Thanks!

-Wynn

**Comment by profxj** [comment]
Please join our Users Slack, read the #guidelines 
 and join the #fluxing channel to discuss further.
