### ISSUE TITLE
pypeit_sensfunc fails for shane_kast_red

### ISSUE THREAD

**Issue by KevinMcK95** [pypeit/PypeIt#1349]
When running `pypeit_sensfunc` with `shane_kast_red` data, I get the following error:
```
File "/Users/kevinm/anaconda3/envs/pypeit_env/lib/python3.9/site-packages/pypeit/spectrographs/shane_kast.py", line 559, in tweak_standard
    return wave_in, counts_in, counts_ivar_in, gpm_out
UnboundLocalError: local variable 'gpm_out' referenced before assignment
```

It looks like this is because `gpm_out` is defined inside of an if statement in `spectrographs/shane_kast.py` that is only true for `shane_kast_blue` data. To fix this, I just add an else statement that sets `gpm_out=gpm_in` before line 557

**Comment by kbwestfall** [comment]
Looking at the most recent code, I think this is now fixed.  Please reopen if not.
