### ISSUE TITLE
pypeit_setup still crashes on keck deimos files with corrupt headers. 

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1357]
See the image d0225_0994.fits posted the PypeIt Develop Slack. 

This image has a nominal fits header but lots of information is missing. As we've discussed, pypeit_setup should not crash, since one corrupt files means one cannot do anything with the dataset. This happens to about 3% of files at Keck.

My suggestion is that we 1) do not crash, 2) come up with some script that can populate the header information based on say a file nearby in time that the users can run to patch up there files. The point is the data is good, just a missing header.

**Comment by profxj** [comment]
Addressed
