### ISSUE TITLE
Mismatch between the number of valid orders found by PypeIt and the number expected for magellan_fire spectrograph

### ISSUE THREAD

**Issue by MeArpanGhosh** [pypeit/PypeIt#1370]
Hi 
     I have been encountering this problem while reducing the echelle spectra from the magellan fire spectrograph. The pipeline says
     "There is a mismatch between the number of valid orders found by PypeIt and the number expected for this spectrograph.  Unable to
      continue."
                  Please help
![issues](https://user-images.githubusercontent.com/30334426/161489515-0538d842-5453-4760-83e9-c3fcb16769ae.png)

**Comment by profxj** [comment]
Hi @MeArpanGhosh -- odds are your flats aren't bright enough
in the blue.  But am not sure.  

Join the PypeIt Slack and seek help there.
