### ISSUE TITLE
Inconsistence of manual extraction settings in pypeit file and coadd2d file

### ISSUE THREAD

**Issue by samwang141224** [pypeit/PypeIt#1402]
I find an Inconsistence of manual extraction settings in pypeit file and coadd2d file when using the codes in objfind_refactor branch to reduce gemini_gnirs data. Since ginga displays X as spatial and Y as spectral, the manual parameter setting in the pypeit file should be spat:spec:fwhm (X:Y:FWHM), or it will raise an error like 

File "/Users/samwang/Downloads/gnirs_typeII/PypeIt/pypeit/core/findobj_skymask.py", line 380, in ech_objfind
    iord_hand = gdslit_spat.tolist().index(slit)
ValueError: -1 is not in list

However, when I go to the coadd2d file, the manual parameter setting under coadd2d should be spec:spat:fwhm (Y:X:FWHM). Or it will raise an 'out of range' error like

Traceback (most recent call last):
  File "/Users/samwang/opt/anaconda3/envs/pypeit/bin/pypeit_coadd_2dspec", line 33, in <module>
    sys.exit(load_entry_point('pypeit', 'console_scripts', 'pypeit_coadd_2dspec')())
  File "/Users/samwang/Downloads/gnirs_typeII/PypeIt/pypeit/scripts/scriptbase.py", line 110, in entry_point
    cls.main(cls.parse_args())
  File "/Users/samwang/Downloads/gnirs_typeII/PypeIt/pypeit/scripts/coadd_2dspec.py", line 239, in main
    = coadd.reduce(pseudo_dict, show=args.show, show_peaks=args.peaks, basename=basename)
  File "/Users/samwang/Downloads/gnirs_typeII/PypeIt/pypeit/coadd2d.py", line 587, in reduce
    sobjs_obj, nobj = objFind.find_objects(sciImage.image, sciImage.ivar, show_peaks=show_peaks,
  File "/Users/samwang/Downloads/gnirs_typeII/PypeIt/pypeit/find_objects.py", line 396, in find_objects
    self.find_objects_pypeline(image, ivar,
  File "/Users/samwang/Downloads/gnirs_typeII/PypeIt/pypeit/find_objects.py", line 947, in find_objects_pypeline
    sobjs_ech = findobj_skymask.ech_objfind(
  File "/Users/samwang/Downloads/gnirs_typeII/PypeIt/pypeit/core/findobj_skymask.py", line 378, in ech_objfind
    slit = slitmask[ispec, ispat]
IndexError: index 712 is out of bounds for axis 1 with size 462

I think it is a little confused to use X:Y in pypeit file and Y:X in coadd2d file.  Not sure whether this is a common issue. Thanks!

**Comment by debora-pe** [comment]
Hi @samwang141224. I don't think the error you get is due to the fact the manual extraction format is different between pypeit file and coadd2d file. The format for manual extraction is always `det:spat:spec:FWHM` . In cases where there is only one detector `det` is 1. Can you tell us which PypeIt version you are using?

**Comment by jhennawi** [comment]
Hi @deborape, 

I think Sam's issue is not so much the error, but rather why are the conventions different? In the pypeit file it is spat:spec, whereas in the coadd2d parser it is spec:spat

**Comment by debora-pe** [comment]
@jhennawi but they are not. The convention is exactly the same.

**Comment by samwang141224** [comment]
Hi @deborape I am using the objfind_refactor branch. If I just copy the manual parameter from the pypeit file to coadd2d file, there will be a 'out of range' error. But if I change the spat and spec in coadd2d file, the coadd 2dspec code runs successfully.

**Comment by samwang141224** [comment]
Hi @deborape this is the manual parameter I used in the pypeit file:
| manual               |
|1:711.2:262.1:5.  |
|1:692.5:263.2:5.|
|1:692.5:263.2:5.|
|1:711.2:262.1:5.  |
|1:711.2:263.2:5. |
|1:691.4:263.2:5.|
|1:691.4:263.2:5.|
|1:711.2:263.2:5.|

and this is the manual parameters I used in the coadd2d file:
[coadd2d]
  manual = 1:262.1:711.8:5.
  
with this setting, the pypeit and coadd2d can run well. But if I use 
[coadd2d]
  manual = 1:711.8:262.1:5.
 There will be an 'out of range' error. So I thought that In the pypeit file it is spat:spec, whereas in the coadd2d parser it is spec:spat. Did I miss something? Thanks!

**Comment by jhennawi** [comment]
I think I see what the issue is. In the .coadd2d file you need to enter the coordinates in the frame of the rectified 2d coadd, since you are manually extracting from that image.

**Comment by debora-pe** [comment]
That's right! @samwang141224 you should not use the exact same locations that you used in the pypeit file because the 2d coadded frame has a different shape than the raw file. You should first run coadd2d without manual extraction, identify the location in the coadded frame, and then rerun coadd2d with the manual extraction.

If you think this issue is resolved, please close it.

**Comment by samwang141224** [comment]
Thanks! @deborape I will close this issue.
