### ISSUE TITLE
pypeit_setup should never crash

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1407]
Run the following command on this file:

Download the following file: 

https://drive.google.com/file/d/1igRZCLIzvRhaIS8W9BFJNgV3YIaR-_b5/view?usp=sharing

Run: 

pypeit_setup -s vlt_xshooter_nir -r ./

Note that astropy cannot read in this file. It is a compressed fits file. If I uncompress it astropy can read it in. If it remains compressed astropy cannot. 

Nevertheless pypeit_setup needs to be robust against these kinds of issues which occur very often. It is not acceptable for a user to be dead in the water because 1% of the files have issues like this.

**Comment by profxj** [comment]
Is this a `pypeit_setup` issue or simply I/O?

i.e. aren't all of our scripts going to fail (e.g. `pypeit_view_fits`)?

**Comment by kbwestfall** [comment]
@jhennawi What behavior would you like to see?  As X said, if astropy can't read it, everything in pypeit will fail.  The easiest path for would be for pypeit_setup to report this as a "bad file".

**Comment by jhennawi** [comment]
I think a crash in pypeit_view_fits is tolerable in this case, since you know which file you have the problem with in that case. The issue with pypeit_setup crashing is that only a black belt can isolate the file causing the problem and without that ability, a user is simply out of business. I don't think that is acceptable. As such, I think pypeit_setup should just construct a list of files it could not analyze and users can decide if they want to chase down those cases. At least you know the problematic files in that case.

**Comment by kbwestfall** [comment]
Okay, that's doable.

**Comment by jhennawi** [comment]
I think the bug here is somehow in astropy. Since when I uncompress the file it is just fine. This file was downloaded from the VLT archive. As you can guess, when dealing with hundreds of files there are going to be some corrupt files.

**Comment by kbwestfall** [comment]
See #1408.  Closing.
