### ISSUE TITLE
Identify trace location by hand

### ISSUE THREAD

**Issue by tiffanyhsyu** [pypeit/PypeIt#141]
For sources with single emission lines/no continuum that aren't automatically detected by PYPIT!

**Comment by profxj** [comment]
I'm happy to help you with this.

**Comment by profxj** [comment]
@tiffanyhsyu -- did you have a branch on this?

**Comment by profxj** [comment]
@tiffanyhsyu -- Does this exist now?

**Comment by tiffanyhsyu** [comment]
It does, but only on one of my local branches :)

Initially, I wanted to be able to specify a raw file name in the .pypit file that we want the manual extraction on. PYPIT would then match that raw file name to one of the N science exposures being reduced and do the manual extraction on only that frame. But I think this is annoying, because it means one would have to re-run PYPIT for the multiple exposures they have that need manual extracting on.

I am tempted to just have PYPIT apply the manual extraction to *all* frames if the line:

science extraction manual01 params [det,spatial, dispersion,[spatial width, dispersion width]]

is in the .pypit file. Is this too risky?

**Comment by profxj** [comment]
I think that is fine @tiffanyhsyu 

One can always restrict the files being processed (I do this).

**Comment by profxj** [comment]
Being addressed by @jhennawi

**Comment by tiffanyhsyu** [comment]
Addressed by pull request #606
