### ISSUE TITLE
Version number appears inconsistent with tag

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#1455]
While we think we are on 1.10, `pypeit_version` tends to give an older one..

**Comment by kbwestfall** [comment]
This continues to happen when working on github branches.  I'm not sure if there's a way around this.  Any thoughts @tepickering ?  FWIW, my tests using a pip installation show the correct version.

**Comment by tepickering** [comment]
i'd have to dig into it and refresh my memory. that said, it looks like the 1.11.0 tag isn't in the history for the `develop` branch which is i think why `setuptools_scm` returns a version of `1.10.1.dev326+ge55e00e9f`. i did a `git merge "1.11.0"` locally and that does fix it.

**Comment by tepickering** [comment]
do note, you need `setuptools_scm` to be installed for `pypeit_version` to be able to directly query git to build the version. otherwise it will return whatever gets hard-coded into `pypeit/version.py` at install time.

**Comment by kbwestfall** [comment]
So this sounds like user error, not something that requires a code fix.  Let us know if you find anything, @tepickering , but I'm closing this for now.
