### ISSUE TITLE
Coadd2D HOWTO example uses the old / deprecated file format

### ISSUE THREAD

**Issue by tomgreene** [pypeit/PypeIt#1463]
The Coadd2D HOWTO at https://pypeit.readthedocs.io/en/latest/coadd2d_howto.html gives an example of making a Coadd2D parameter file in the old / deprecated format. It does not contain the 'filename' or 'path' keywords.
It also sets the snr threshold with the work keyword (should be snr_thresh in current pypeit v 1.10).

The main docs on Coadd2D at https://pypeit.readthedocs.io/en/latest/coadd2d.html#coadd2d-file do give the new / correct format.

**Comment by debora-pe** [comment]
Addressed in #1490
Closing this.
