### ISSUE TITLE
wavelength calibration parameter fwhm_fromline for GMOS

### ISSUE THREAD

**Issue by drupke** [pypeit/PypeIt#1467]
Presently, `gemini_gmos.py` sets the wavelength calibration parameter `fwhm_fromline=True`. With a recent Gemini/GMOS/R400 dataset (spectral binning=2), I found this to give an RMS value 2-3 too high when fitting the wavelength solution. Setting `fwhm_fromline=False`, the default value for most other spectrographs, appeared to reduce the RMS to the proper range (<0.1 pix).

**Comment by kbwestfall** [comment]
Thanks for the report, @drupke .  We'll keep this in mind and have added a note to the documentation (PR #1494) , but we'll leave the current default for now.  Please let us know if you continue to find this to be necessary for additional datasets.
