### ISSUE TITLE
cannot import name 'msgs' from 'pypeit'

### ISSUE THREAD

**Issue by temuller** [pypeit/PypeIt#1468]
I have installed pypeit in developer mode on an anaconda environmnet:

```
git clone https://github.com/pypeit/PypeIt.git
cd PypeIt
pip install -e ".[dev,pyqt5]"
``` 
but when I run the test `run_pypeit -h` I get:

```
Traceback (most recent call last):
  File "/home/tomas/anaconda3/envs/pypeit/bin/run_pypeit", line 5, in <module>
    from pypeit.scripts.run_pypeit import RunPypeIt
  File "/home/tomas/PypeIt/pypeit/scripts/__init__.py", line 2, in <module>
    from pypeit.utils import all_subclasses
  File "/home/tomas/PypeIt/pypeit/utils.py", line 29, in <module>
    from pypeit import msgs
ImportError: cannot import name 'msgs' from 'pypeit' (unknown location)
```

Current version: `1.10.1.dev3+g52d10eddd`. The pip version works correctly though.

**Comment by kbwestfall** [comment]
Hi @temuller ,  I tried and cannot reproduce your error using a fresh clone and fresh environment.  I expect this error is specific to your system.  What is your OS and python version?

**Comment by temuller** [comment]
I am using Ubuntu 22.04 with python 3.9.

**Comment by kbwestfall** [comment]
Hmm...  I would expect that to work.  It's difficult for me to help debug when I can't reproduce the error.  I would suggest posting your issue in the #installing channel on the PypeIt Users Slack to see if anyone else has had this problem and may have a solution.  Other developers will see this github comment, so they may have suggestions for you as well.

**Comment by temuller** [comment]
Will do, thanks.

**Comment by temuller** [comment]
I solved this by properly installing pyetst in the anaconda environment, as suggested in [pypeit/PypeIt-development-suite#221](https://github.com/pypeit/PypeIt-development-suite/issues/221). Thanks!
