### ISSUE TITLE
Include directory structure in output file description

### ISSUE THREAD

**Issue by cgelino** [pypeit/PypeIt#1472]
It would be most helpful to include the directory structure out the output files.  Some of the directories are duplicated (ex. 'lev2/keck_mosfire_G/keck_mosfire_G/Masters/') which seems like a bug but might make sense for other instruments.  So, it would be helpful to describe where those names come from.  Thanks.

**Comment by kbwestfall** [comment]
I agree that this seems like a bug, but I'm not sure it's a bug in the PypeIt code base itself.  Executing `run_pypeit` should (by default) only create the `Masters` directory from where it's called.  `pypeit_setup` will create the, e.g., `keck_mosfire_G` directory, but its as if `pypeit_setup` was executed a 2nd time from within that directory.  Can you check how the code was executed?

**Comment by kbwestfall** [comment]
After talking to Max, I'm closing this.  Feel free to re-open.
