### ISSUE TITLE
more pypeit_setup bad header crashes

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1474]
As titled. Trace image is attached as well as google drive link (in developer slack) to the data. Image 77 is the culprit. 

![Screen Shot 2022-09-27 at 3 23 04 PM](https://user-images.githubusercontent.com/8774563/192538736-97d9a156-625a-4665-b4d1-b2bf637b13f5.png)

**Comment by kbwestfall** [comment]
Hi @jhennawi .  I've got a fix in for this; see https://github.com/pypeit/PypeIt/compare/develop...setup_fix

I don't know why we removed the try/except block that used to catch the MJD error at this place in `keck_lris.py`.  We should check on that before issuing a PR.

**Comment by jhennawi** [comment]
Hi @kbwestfall,  I think @profxj did not want it in there is my recollection. We should get his opinion on it.

**Comment by profxj** [comment]
What I wish to avoid is a solution that will pass through on `pypeit_setup` *and* `run_pypeit`.
  i.e. `run_pypeit` better crash if the MJD is buggered up.

**Comment by kbwestfall** [comment]
The specific use that was causing a problem was parsing the MJD to determine the observation date that is then used to define the available set of lamps.  I.e., this isn't the general read of the MJD.  I think `run_pypeit` should still fault as it would have before if it can't read the MJD.  But is there a dataset that we can check this on?  Maybe you can test this @jhennawi with this same dataset that was causing the problem?

**Comment by kbwestfall** [comment]
Just so it didn't get lost, I issued the current fix in #1494 .
