### ISSUE TITLE
In matplotlib >3.3, set_window_title method is depreciated, and causes an error when using skysub gui

### ISSUE THREAD

**Issue by prappleizer** [pypeit/PypeIt#1479]
With matplotlib version >3.3, the `set_window_title` method has been depreciated. The latest version of pypeit installed from git still uses this method with the manual sky definition gui, throwing an error on launch: 

```
'FigureCanvasQTAgg' object has no attribute 'set_window_title'
```

I was able to resolve the problem by downgrading to matplotlib 3.3, but in the future this should be fixed as we are past matplotlib 3.6 at this point. 

From the perspective of the codebase, I found one piece of advice: A quick fix is to replace `fig.canvas.set_window_title` with `fig.canvas.manager.set_window_title`, but there may be more elegant ways to get around this as well.

**Comment by rcooke-ast** [comment]
Addressed by PR #1482 - Thanks for submitting the issue @prappleizer!
