### ISSUE TITLE
The attribute "set_window_title" no longer exists in fig.canvas

### ISSUE THREAD

**Issue by xyz3919** [pypeit/PypeIt#1489]
I recently installed Pypelt and analyzed the Gemini/GMOS long-slit data for my project.
I was running pypeit_identify, then I got the error message about the plotting function.

File "/home/xxxxx/.conda/envs/pypeit/lib/python3.9/site-packages/pypeit/core/gui/identify.py", line 337, in initialise
    fig.canvas.set_window_title('PypeIt - Identify')
AttributeError: 'FigureCanvasQTAgg' object has no attribute 'set_window_title'

It seems that the newest matplotlib no longer supports 'set_window_title' in fig.canvas. I just commented the line out and the program worked fine.

**Comment by kbwestfall** [comment]
@rcooke-ast Did you recently fix this?

**Comment by rcooke-ast** [comment]
Addressed by PR #1482... closing.
