### ISSUE TITLE
usebiasimage=False

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#1493]
We seemed to have lost how to show folks how 
to edit their config paramters to turn off bias subtraction.

Let's make them reappear, i.e.

```
[baseprocess]
   use_biasimage=False  
```

**Comment by kbwestfall** [comment]
Is this it?

https://pypeit.readthedocs.io/en/release/calibrations/image_proc.html#example-changes

**Comment by profxj** [comment]
Yes, thanks!

**Comment by kbwestfall** [comment]
Closing.
