### ISSUE TITLE
pypeit_show_2dspec fails on Mosaiced DEIMOS data

### ISSUE THREAD

**Issue by bpholden** [pypeit/PypeIt#1496]
`pypeit_show_2dspec`    `spec2d_DE.20141129.48350-M454D_1_DEIMOS_20141129T132545.638.fits`

[ERROR]   :: DET01 not available in any extension of spec2d_DE.20141129.48350-M454D_1_DEIMOS_20141129T132545.638.fits
_traceback deleted_
pypeit.pypmsgs.PypeItError: DET01 not available in any extension of spec2d_DE.20141129.48350-M454D_1_DEIMOS_20141129T132545.638.fits

This will run with 
`pypeit_show_2dspec  --det MSC02`

but ideally the script would handle this more gracefully.

**Comment by profxj** [comment]
Being addressed in the `merge_ql` branch
