### ISSUE TITLE
pypeit_cache_github_data keck_deimos misses some calibration data

### ISSUE THREAD

**Issue by stevenrjanssens** [pypeit/PypeIt#1498]
The nodes in my high performance computing environment do not have outside access so I ran `pypeit_cache_github_data keck_deimos` to cache everything Pypeit needs. However, `run_pypeit` still attempts to download some stuff:
```
[ERROR]   :: utils.py 573 fetch_remote_file() - Error downloading keck_deimos_600ZD.fits: <urlopen error [Errno -2] Name or service not known>
             URL attempted: https://raw.githubusercontent.com/pypeit/PypeIt/1.11.0/pypeit/data//arc_lines/reid_arxiv/keck_deimos_600ZD.fits
             If the error relates to the server not being found,
             check your internet connection.  If the remote server
             name has changed, please contact the PypeIt development
             team.
```

And this appears to occur for every grating.

**Comment by tbowers7** [comment]
@stevenrjanssens : To help me track this down, could you also include the informational lines printed before this error statement?

**Comment by tbowers7** [comment]
@stevenrjanssens : This fix has been merged in, watch for the next Release of PypeIt.
