### ISSUE TITLE
Possible incorrect noise calculation when combining multiple spectra differences (MOSFIRE, K band)

### ISSUE THREAD

**Issue by tomgreene** [pypeit/PypeIt#1517]
![spec2d_chk_noise_m221110_0074-Per-emb-24A-B](https://user-images.githubusercontent.com/28412470/206228561-c4d12981-854f-4f55-958c-6092f3415c04.png)
![spec2d_chk_noise_m221110_0076-Per-emb-24AA-BB](https://user-images.githubusercontent.com/28412470/206228568-ed3f352a-15e0-43a7-92e3-0e4e207a563c.png)
![spec1d_m221110_0076_Per-emb-24AA-BB_21244-22200](https://user-images.githubusercontent.com/28412470/206228572-affe440a-5723-4b2f-9a59-f1564f142c64.png)
![spec1d_m221110_0074_Per-emb-24A-B_21244-22200](https://user-images.githubusercontent.com/28412470/206228575-e5a421ad-48c9-40b3-9ff0-d7b7fe11808a.png)
Per my conversation with Joe Hennawi in the PypeIt Users mosfire Slack channel (Dec 4 - 6, 2022), it appears that pypeit  v1.11.0 (per $ run_pypeit -h) may not compute the noise properly when combining multiple spectra into an A-B pair: The variance for an A+A-B-B difference does not equal 2 x the variance of an A-B difference, per JH: there:

"So the noise is clearly wrong for the A + A -B-B combined, and it happens to be off by exactly the factor of sqrt(2) suggesting our error propgation has a bug. it is possible this was introduced recently when the combine routine was modified slightly
Could you please post a minimal pypeit file with these four images and calibrations in a github issue and we will look into it."

I have attached an edited minimal pypeit file and the graphical outputs of the pypeit_chk_noise_1dspec and pypeit_chk_noise_2dspec scripts run on the A-B vs A+A -B-B spectra. The raw images and flats use are available on my google drive here: https://drive.google.com/drive/folders/1_Ogkj8HU0Vvz8Cd3i9I8i6XmPWfFutxQ?usp=sharing

[test_combine.pypeit.txt](https://github.com/pypeit/PypeIt/files/10171303/test_combine.pypeit.txt)

**Comment by debora-pe** [comment]
Solved in PR #1590 . Closing this.
