### ISSUE TITLE
Either the slit has many bad pixels or the number of trimmed pixels is too large.

### ISSUE THREAD

**Issue by ghost** [pypeit/PypeIt#1528]
Greetings,

I'm having the following issue when I run the `run_pypeit` command, while it is subtracting the lamps off flats.

"ZeroDivisionError: division by zero"

This is the las part of the magellan_mage_A.log file

`[INFO]    :: calibrations.py 590 get_flats() - Subtracting lamp off flats using files: 
             calibrations.py 592 get_flats() - mage0104.fits
             calibrations.py 592 get_flats() - mage0105.fits
             calibrations.py 592 get_flats() - mage0106.fits
             calibrations.py 592 get_flats() - mage0116.fits
             calibrations.py 592 get_flats() - mage0117.fits
             calibrations.py 592 get_flats() - mage0118.fits
             calibrations.py 592 get_flats() - mage0119.fits
             calibrations.py 592 get_flats() - mage0120.fits
             calibrations.py 592 get_flats() - mage0121.fits
             calibrations.py 592 get_flats() - mage0142.fits
             calibrations.py 592 get_flats() - mage0143.fits
             calibrations.py 592 get_flats() - mage0144.fits
             calibrations.py 592 get_flats() - mage0145.fits
             calibrations.py 592 get_flats() - mage0146.fits
             calibrations.py 592 get_flats() - mage0147.fits
             calibrations.py 592 get_flats() - mage0148.fits
             calibrations.py 592 get_flats() - mage0149.fits
             calibrations.py 592 get_flats() - mage0159.fits
             calibrations.py 592 get_flats() - mage0160.fits
             calibrations.py 592 get_flats() - mage0161.fits
             calibrations.py 592 get_flats() - mage0162.fits
             calibrations.py 592 get_flats() - stack1.fits
             calibrations.py 592 get_flats() - stack10.fits
             calibrations.py 592 get_flats() - stack2.fits
             calibrations.py 592 get_flats() - stack3.fits
             calibrations.py 592 get_flats() - stack4.fits
             calibrations.py 592 get_flats() - stack5.fits
             calibrations.py 592 get_flats() - stack6.fits
             calibrations.py 592 get_flats() - stack7.fits
             calibrations.py 592 get_flats() - stack8.fits
             calibrations.py 592 get_flats() - stack9.fits
             calibrations.py 592 get_flats() - mage0131.fits
             calibrations.py 592 get_flats() - mage0132.fits
             calibrations.py 592 get_flats() - mage0172.fits
             calibrations.py 592 get_flats() - mage0173.fits
[WARNING] :: combineimage.py 266 run() - Exposure time is not consistent for all images being combined!  Using the average.
[INFO]    :: flatfield.py 625 build_waveimg() - Generating wavelength image
[INFO]    :: wavecalib.py 244 build_waveimg() - Evaluating 2-d wavelength solution for echelle....
[INFO]    :: flatfield.py 847 fit() - Modeling the flat-field response for slit spat_id=243: 1/10
[INFO]    :: flatfield.py 928 fit() - Spectral fit of flatfield for 0/18744  pixels in the slit.
[WARNING] :: flatfield.py 933 fit() - Spectral fit includes only 0.0% of the pixels on this slit.
                       Either the slit has many bad pixels or the number of trimmed pixels is too large.`

I hope someone can help me.

Thanks!

**Comment by profxj** [comment]
Have you tried reducing the data in the DevSuite (or at least examining
its PypeIt file -- https://github.com/pypeit/PypeIt-development-suite/blob/master/pypeit_files/magellan_mage_1x1.pypeit 

I worry the flats used here aren't kosher.  Or need to be combined
in some other manner..
