### ISSUE TITLE
IndexError: index 21 is out of bounds for axis 0 with size 21

### ISSUE THREAD

**Issue by esoftich** [pypeit/PypeIt#1547]
Hi!
I'm running into this error when am running pypeit with the [run_pypeit magellan_fire_A/magellan_fire_A.pypeit]. 
I followed the instructions with the test data and was able to get that to run and am now attempting it with my own data. I have compared both magellan_fire_A.pypeit files for the two different runs and I'm not seeing any difference that would cause this error. 

*I have attached a screenshot of the error in question

1. I'm not sure where the error is coming from 
2. I don't know how to fix it

Please advise
<img width="881" alt="Screen Shot 2023-02-23 at 11 19 33 AM" src="https://user-images.githubusercontent.com/114195536/221008617-b372cad1-3d2a-4a52-9c74-521a5c56f0e4.png">

**Comment by profxj** [comment]
@esoftich -- I encourage you to jump on the PypeIt Users Slack
 and seek support there.  

There isn't enough information provided here to help/fix.
Thanks
