### ISSUE TITLE
Add `astropy.units` Quantities to 1D `SpecObj` data model?

### ISSUE THREAD

**Issue by tbowers7** [pypeit/PypeIt#1553]
In the current `SpecObj` data model, the units of a given item are specified in the item's description, but the data are saved as pure numeric arrays.

Can / should we be using `Quantity` objects for data model items with units?  These would then be saved into the output FITS file and the units would be reconstructed upon reading the file later.

While there are obvious benefits when analyzing the PypeIt-produced 1D spectra, are there drawbacks or concerns for major breakage within the PypeIt code base if units are added to the data?

What other benefits or concerns might there be in implementing units?

**Comment by profxj** [comment]
Let's discuss at the Team meeting.  But my expectation
is that we won't be going for units.

On the positive side, @kbwestfall has nearly integrated the Spectrum1D class
which does carry units.

**Comment by jhennawi** [comment]
Yes I think the main problem here is that the unit arrays slow down manipulations with the data by a huge factor (I think as large as 100). If someone unwittingly does not convert to numpy arrays then you have performance problems.
