### ISSUE TITLE
Error while running pypeit_show_1dspec

### ISSUE THREAD

**Issue by DGalanDieguez** [pypeit/PypeIt#1561]
After installing pypeit and doing the "run_pypeit -h" installation check, I continued checking that pyqt5 works using 

--> _"python -c "from pkg_resources import resource_filename; print(resource_filename('pypeit', 'tests/files/spec1d_r153-J0025-0312_KASTr_20150123T025323.850.fits'))" | xargs -I {} pypeit_show_1dspec {}"_

as indicated in the installation guide. However, I get the following error:

--> **TypeError: setMinimumWidth(self, minw: int): argument 1 has unexpected type 'float'**
![Pypeit_Error](https://user-images.githubusercontent.com/127629050/224510657-58e50637-9cda-4e54-bca5-2fbfc8a90b65.png)

I reduced some data with pypeit and everything seems to work fine except when I try to use **pypeit_show_1spec**. I would appreciate if someone could help me out with this error. Thanks!!

**Comment by profxj** [comment]
@DGalanDieguez this is because of the WARNING message
in your output.  You are trying to use a new version of PypeIt
on an old file.  

Sometimes that works, sometimes it doesn't.  
When it doesn't, you should re-run the reduction
with the new version.
