### ISSUE TITLE
Refactor rms_threshold

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#1651]
As a follow-on to https://github.com/pypeit/PypeIt/pull/1628, 
we need to refactor `rms_threshold` to be relative to the `FWHM`.

@debora-pe -- I suggest we do this as part of the LRIS wavelengths PR
that you are working on.  The main annoyance will be to update the 
values throughout the spectrograph files (and a few PypeIt files of the DevSuite).

**Comment by debora-pe** [comment]
PR #1672 is addressing it

**Comment by debora-pe** [comment]
Addressed. Closing this issue.
