### ISSUE TITLE
An error when process "Applying heliocentric correction to OPT extraction for object"

### ISSUE THREAD

**Issue by fgscc** [pypeit/PypeIt#1671]
When the code try to perform a heliocentric correction, the code is broken. And I have checked the source coude: specobj.py in line 1106. There is a warning: "This has only been tested for single-extension. Unpack if necessary". Since my data is multi-extensions, I'm wondering how I revise the code to make the code run.
<img width="1401" alt="bug1" src="https://github.com/pypeit/PypeIt/assets/116858817/db744006-c10d-4f02-9130-110679731399">
<img width="1402" alt="bug2" src="https://github.com/pypeit/PypeIt/assets/116858817/42a6a970-7c91-4f37-aa5e-c72a894d4e77">

**Comment by kbwestfall** [comment]
Hi @fgscc .  Please tell us a few things:

 - What OS are you using?
 - What version of pypeit are you running?
 - Am I right that you are trying to reduce `gemini_gmos_north_ham` data?
 
Thanks!

**Comment by fgscc** [comment]
Hi, @kbwestfall, thanks for the reply. My answer is:
(1) I am using macOS Monterey (version 12.6);
(2) The pypeit version is 1.13.0;
(3) Yes, I am trying to reduce gemini_gmos_north_ham data.

Besides, these data I have reduced about 2 years ago by using the pypeit code, and it works without any errors. Now I am trying to reduce them again. And I meet an interesting issue: after runing the step <pypeit_setup>, I could obtain a <.sorted> file, which contains many configurations (but the configuration begins with <Setup E> without any bias files). Then I run <run_pypeit ***.pypeit>, the code stops and reports <you should add the bias profiles>. And I check the <.pypeit> file I have generated 2 years ago, the configurations are totally different (contains the bias files in the configurations). I am wondering what caused the difference. (I'd like to show the 'setup block' for these two results.) . Should I install a lower version of pypeit?
![sorted_file_generate now](https://github.com/pypeit/PypeIt/assets/116858817/cf9ddf8f-70d0-49cf-b1fe-be0528b3f07a)
![sorted_file_generated_2 years ago](https://github.com/pypeit/PypeIt/assets/116858817/e821063f-32ce-4c5a-b903-0641c98d5dbf)

And thank you again for the reply!

**Comment by fgscc** [comment]
Hi, kbwestfall. I have uploaded the answers and described the questions more detail on github. It’s very nice for you could reply me. Thank you so much!&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Kyle Westfall ***@***.***&gt;
Date: Wed,Sep 13,2023 11:01 PM
To: pypeit/PypeIt ***@***.***&gt;
Cc: fgscc ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [pypeit/PypeIt] An error when process "Applying heliocentriccorrection to OPT extraction for object" (Issue #1671)





 
Hi @fgscc .  Please tell us a few things:
  
What OS are you using?
 
What version of pypeit are you running?
 
Am I right that you are trying to reduce gemini_gmos_north_ham data?
  
Thanks!

**Comment by kbwestfall** [comment]
Hi @fgscc ,

My first recommendation (you may already be doing this) is to make sure that you're working in a new directory.  That is, do not work in the same directory as you used for the reduction you performed 2 years ago.  pypeit is generally not backwards compatible, and the fault may be because the code is trying to read data produced by a previous version.

It's also possible that the frame typing is wrong.  You always need to check the pypeit file to make sure that it is correctly assigning images the correct frame type.  If not, you should edit the pypeit file directly before running `run_pypeit`.

**Comment by fgscc** [comment]
Ok, I see. I haven’t tried yet. I’d like to try it soon. And thank you so much for the recommendation!



发自我的iPhone


------------------ Original ------------------
From: Kyle Westfall ***@***.***&gt;
Date: Thu,Sep 14,2023 0:54 AM
To: pypeit/PypeIt ***@***.***&gt;
Cc: fgscc ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [pypeit/PypeIt] An error when process "Applying heliocentriccorrection to OPT extraction for object" (Issue #1671)





 
Hi @fgscc ,
 
My first recommendation (you may already be doing this) is to make sure that you're working in a new directory.  That is, do not work in the same directory as you used for the reduction you performed 2 years ago.  pypeit is generally not backwards compatible, and the fault may be because the code is trying to read data produced by a previous version.
 
It's also possible that the frame typing is wrong.  You always need to check the pypeit file to make sure that it is correctly assigning images the correct frame type.  If not, you should edit the pypeit file directly before running run_pypeit.

**Comment by kbwestfall** [comment]
Great.  Let me know if you have any more questions.  You're also welcome to join the pypeit users Slack workspace.  See the invitation link in our documentation here: https://pypeit.readthedocs.io/en/release/#community

**Comment by kbwestfall** [comment]
Closing.  Feel free to re-open if you have additional questions.
