### ISSUE TITLE
Improved scattered light model

### ISSUE THREAD

**Issue by rcooke-ast** [pypeit/PypeIt#1684]
At the moment a very crude model of the scattered light is implemented, and this is only used for KCWI reductions. Ideally, we should use the inter-order regions (for `Echelle` reductions) and the interslice region for `SlicerIFU` reductions. This enhancement would require that we pass the `Slits` calibration files into `rawimage.py` (because the scattered light should be removed before the flatfielding frames), and this is not currently well setup for this.

The current simplistic model for scattered light subtraction (at least for KCWI) was implemented in PR #1661. I assign myself to look into a better model for KCWI. Part of this effort should involve using the Slits information.

**Comment by kbwestfall** [comment]
Partially addressed by #1704 .  @rcooke-ast , can you comment on what's left to do?

**Comment by rcooke-ast** [comment]
Yes, this is now "fully" addressed. KCRM is not implemented, but KCWI and ESI are both implemented. So, this can be closed.
