### ISSUE TITLE
Duplicate object names in spec1d when reducing DEIMOS data

### ISSUE THREAD

**Issue by badpandabear** [pypeit/PypeIt#1690]
When reducing DEIMOS data, sometimes objects are detected at the same spatial positions which receive duplicate object names in the spec1d. This makes coadding impossible because the coadd code doesn't know which object to use. 

I have uploaded an example to:

https://drive.google.com/drive/folders/1jlGZXbNbA_8WxnFWQTZ2sKH63MvPKCmK?usp=sharing

See `SPAT0808-SLIT0823-MSC04` as an example duplicated name.

**Comment by debora-pe** [comment]
Resolved in PR #1739
