### ISSUE TITLE
Installation issue with Pyqt6

### ISSUE THREAD

**Issue by sinataamoli** [pypeit/PypeIt#1702]
I'm trying to install pypeit on a remote server, I tried both`conda create -n pypeit python=3.11` and `conda env create -f environment.yml` using yml file. At the `pip install pypeit` stage this error comes up:

```shell
Collecting pyqt6 (from pypeit)
  Using cached PyQt6-6.5.2.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1

...

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 

It seems that there is an issue with building the wheel for PyQt6, which is causing the installation to fail. Does anyone have a suggestion to handle this issue?

**Comment by kbwestfall** [comment]
Hi @sinataamoli .  Apologies for the slow response!

Another user on our PypeIt User's Slack had a similar problem.  I suggested they try deleting their current pypeit environment and start fresh by running:

```
conda create --name pypeit
conda activate pypeit
pip install pypeit
```

This worked without issue for me on my Mac (OSX 13.6; python 3.11), but other users have had different results.  One issue stemmed from a conflict between Spyder and pyqt6, which means you may need to update your conda installation.

Please give the above a try and let me know if you still have issues.

**Comment by sinataamoli** [comment]
Hi @kbwestfall. Thank you for your response. I had installed pypeit on my mac without any issues.
I had this issue when I was trying to install pypeit on a remote server. I finally ended up installing the dependencies separately this way: 
```shell
conda create -n pypeit python=3.11
conda activate pypeit

pip install scipy astropy bottleneck ipython matplotlib extension-helpers pygithub ginga configobj scikit-learn linetools
pip install pypeit --no-deps
``` 
it worked for me.

**Comment by kbwestfall** [comment]
Thanks for following up with the details.  I'll keep this in mind if others have similar issues.  Thanks!
