### ISSUE TITLE
Pixel coordinate system

### ISSUE THREAD

**Issue by rcooke-ast** [pypeit/PypeIt#171]
Rethink the method used to incorporate the pixel locations on the detector (e.g. gaps between pixels, and rectangular pixels). At the moment, the pixlocn array should deal with this, but only in some parts of the code. It would be better to stick to one coordinate system throughout (e.g. assume adjacent, square pixels), and deal with the true pixel coordinates during extraction.

**Comment by profxj** [comment]
these have been deprecated for now.
