### ISSUE TITLE
Keck LRIS data reduction issue

### ISSUE THREAD

**Issue by LucasViktor** [pypeit/PypeIt#1719]
Good afternoon,
My name is Lucas. I'm a PhD student at the University of Manitoba. I have been trying to apply your pipeline (Pypelt) to reduce Keck LRIS data (spectrum ) for the pulsar PSR J1741-2054 (Obs-date:20100611, MDJ 55,358.5). For the blue camera, everything worked quite well but it failed to calculate the sensitivity function. As for the red camera, it seems that it is not working. It keeps printing the following message:" No frames of type=trace provided.", I checked the input file and the calibration files and everything looks fine. I'm attaching these files if you want to check.  Could you provide me with support for this reduction? 

Thank you very much for your time and consideration.
[keck_lris_red_A_calib.txt](https://github.com/pypeit/PypeIt/files/13243869/keck_lris_red_A_calib.txt)
[keck_lris_red_A_pypeit.txt](https://github.com/pypeit/PypeIt/files/13243870/keck_lris_red_A_pypeit.txt)

**Comment by kbwestfall** [comment]
Hi @LucasViktor .  First, the developers (and the rest of the user community) provide a lot of support via our User's Slack.  You're encouraged to [join](https://join.slack.com/t/pypeit-users/shared_invite/zt-1kc4rxhsj-vKU1JnUA~8PZE~tPlu~aTg) and get more support there.

I took a quick look, and my guess is that you should make sure all files are set to the same calibration group in your pypeit file (assuming you want all calibration frames to be combined and used to calibrate your science frame).  I.e., make sure that the integers in the last (`calib`) column are all set to either 1 or 0.  It doesn't matter which, as long as they're all the same.

**Comment by kbwestfall** [comment]
Closing.  Feel free to re-open, if necessary.
