### ISSUE TITLE
How do I reduce the HIRES data before the 2004 update?

### ISSUE THREAD

**Issue by zxmyg86400** [pypeit/PypeIt#1763]
When I try to reduce the HIRES data of 1999, I meet some errors. How do I do this reduction correctly with pipet?

**Comment by kbwestfall** [comment]
Hi @zxmyg86400 .  Development to improve support for Keck/HIRES is ongoing, so this might not be possible yet.  Perhaps @profxj , @jhennawi , or @debora-pe have suggestions?  Regardless, I encourage you to join the PypeIt Users Slack workspace (use [this link](https://join.slack.com/t/pypeit-users/shared_invite/zt-1kc4rxhsj-vKU1JnUA~8PZE~tPlu~aTg)), which we use for these types of support questions.

**Comment by profxj** [comment]
That is correct.  Development for the original detector has not
started.  I doubt it would be too difficult if you wished to try it
yourself (with our help).  If so, jump on PypeIt Users Slack and
discuss further.

**Comment by zxmyg86400** [comment]
Yeah, I did give it a little try, since the single CCD data from the original detector looks a bit like that of ESI. But naively combing the code of updated HIRES and ESI leads to errors, and that's where I am now. I have jumped to PypeIt Users Slack but not sure where to start.

**Comment by profxj** [comment]
I've just started a HIRES channel

jump in there and ping me
