### ISSUE TITLE
Correct sky subtraction with PypeIt

### ISSUE THREAD

**Issue by jesusgomez2001** [pypeit/PypeIt#1779]
I am reaching out for assistance as a novice user of PypeIt, and I apologize in advance if my question seems too basic.

I am currently working with VLT-Xshooter files that have been processed using the corresponding pipeline. However, I am encountering challenges with the sky subtraction, as evident in the attached 2D images of the UVB and VIS spectra. 

<img width="872" alt="figure_1" src="https://github.com/pypeit/PypeIt/assets/153769047/6fc7ddae-ecea-499a-9f40-e096b2ad5a52">

I am wondering if it is possible to use PypeIt to effectively subtract the sky background, correct for spectrum curvature, and generate a 1D flux versus wavelength spectrum from these provided images.

My intention is not to perform the entire reduction using PypeIt but to focus solely on this specific aspect. I would greatly appreciate any guidance or instructions on how to achieve this with PypeIt. Additionally, if there are specific parameters or steps I should consider, please provide insights to help me overcome these challenges.

Thank you very much in advance for your assistance, and I sincerely apologize for any inconvenience.

**Comment by kbwestfall** [comment]
Hi @jesusgomez2001 .  I encourage you to join the PypeIt Users Slack and post your question in the #x-shooter channel.  I think you'll get faster feedback on your issue there.  The invitation link is here: https://pypeit.readthedocs.io/en/release/#community
