### ISSUE TITLE
pypeit_show_2dspec not working

### ISSUE THREAD

**Issue by fhamann3** [pypeit/PypeIt#1781]
I'm trying to use pypeit_show_2dspec to examine 2d frames obtained with Keck LRIS. Running this command opens a Ginga window without errors, but then it just hangs until it times out. It does not open the data file in Ginga. I have a brand new pypeit install and the data were just reduced with that install, so it's not a compatibility issue. 

I can also use the command "ginga --modules=RC,SlitWavelength" to open a Ginga window without errors, but then I can't figure out how to display the reduced sky-subtracted image. Inside that Ginga window, I have used the File button (lower right) to open the file, with [DET02-SCIIMG] appended to the end of the file name so I can see the science image on detector 2. That's awkward and it does not appear to be sky subtracted. 

Please tell me how to get pypeit_show_2dspec working or, at least, to somehow display the sky-subtracted image. Thanks!

**Comment by kbwestfall** [comment]
Hi @fhamann3 .  This may be a problem with `ginga`.  If you're running `ginga` version 5.0, please try reverting to version `4.1.1` (i.e., `pip install ginga==4.1.1`).  If that doesn't fix the problem, please let us know.

**Comment by fhamann3** [comment]
That worked! I was running Ginga 5.0.0. I installed 4.1.1 and now pypeit_show_2dspec loads the data as expected in 4 tabs. Thank you!!
