### ISSUE TITLE
add WD1911 flux std

### ISSUE THREAD

**Issue by mt-astro** [pypeit/PypeIt#1817]
add WD1911+536 to flux std list from calspec 
[wd1911_536_stiswfc_001.fits](https://archive.stsci.edu/hlsps/reference-atlases/cdbs/current_calspec/wd1911_536_stiswfc_001.fits)

**Comment by debora-pe** [comment]
@mt-astro this standard has been already added in the latest PypeIt release. See https://pypeit.readthedocs.io/en/release/standards.html
