### ISSUE TITLE
run_pypeit -c fails

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1823]
See data and PypeIt file in the developer Slack to reproduce this bug. 

<img width="1562" alt="Screenshot 2024-06-29 at 17 43 47" src="https://github.com/pypeit/PypeIt/assets/8774563/d39ed6b8-326a-4914-bc1e-1aa51ae05af1">

**Comment by kbwestfall** [comment]
See #1824.  This fixes the specific failure you found, but it might not fix larger issues associated with trying to only reduced calibrations (if they exist).
