### ISSUE TITLE
Improve automatic spatial flexure correction

### ISSUE THREAD

**Issue by debora-pe** [pypeit/PypeIt#1843]
It appears that the spatial flexure correction does not work well for some LRIS datasets. The shift is not detected, therefore it is not corrected for.

**Comment by tbowers7** [comment]
Was this issue corrected in #1848 to everyone's satisfaction?  Can we close this issue?

**Comment by debora-pe** [comment]
Unfortunately. #1848 didn't completely address this issue. I am working on it.

**Comment by debora-pe** [comment]
Addressed in #1870
