### ISSUE TITLE
Updating Python version requirements to include Python 3.13

### ISSUE THREAD

**Issue by bmitc** [pypeit/PypeIt#1869]
Hello! I am wondering when the Python version requirements will be updated to include version 3.13, which was released just last month. On the [PyeIt PyPI page](https://pypi.org/project/pypeit/), the version requirements are listed as `<3.13,>=3.11`. I would make the assumption that this is simply a matter of updating the package metadata, unless there are known incompatibilities or issues with Python 3.13.

If all that needs to happen is updating this line:

https://github.com/pypeit/PypeIt/blob/fd0074f381bf11df9a439a959d5579b7f35cfb66/environment.yml#L5

then I am happy to put up a pull request for that.

CCing @SHughes96

**Comment by kbwestfall** [comment]
Hi @bmitc .  Thanks for asking!  We'll plan to run some tests and support 3.13 in the next pypeit release.  Based on a quick browse of the release notes, I think support for 3.13 should be straight-forward.

**Comment by bmitc** [comment]
Hi @kbwestfall. Thanks for the response, and that sounds great. I'm thinking that our project will simply track the version requirements of PypeIt since it is such a major component. And it's great that the version requirements are on the forward edge of the Python versions. 👍

**Comment by kbwestfall** [comment]
Addressed by #1881 .  We'll release version 1.17.1 in the coming days.
