### ISSUE TITLE
PYPIT for red reductions

### ISSUE THREAD

**Issue by AlexaVillaume** [pypeit/PypeIt#202]
For reductions of the 600/10000 grating I think we'll need to augment a couple of the PYPIT routines. Most importantly, wavelength calibration and implementing a method of telluric correction. For the wavelength calibration I think we'll need to use sky features at reddest parts of the spectrum. Furthermore, there are many import spectral features that require careful telluric correction to reliably recover. 

This is an enhancement that I'll take the lead on, assuming that's okay with the lead developers. Unless told otherwise I'll follow the Astropy workflow guidelines (http://docs.astropy.org/en/stable/development/workflow/development_workflow.html). 

I'm traveling for a few more weeks still but once I'm back in Santa Cruz I'll be focusing on this.

**Comment by profxj** [comment]
Am thrilled you have volunteered on this.  Let me also suggest you chat
with Ryan Foley who is quite expert in dealing with telluric absorption and LRIS.
Maybe we can get him to make the switch away from IRAF!  :)
