### ISSUE TITLE
Implementing the ALFOSC spectrograph (long-slit data)

### ISSUE THREAD

**Issue by bomilvangjensen** [pypeit/PypeIt#231]
For information, to avoid duplication of effort: I am working on implementing long-slit data from the ALFOSC spectrograph at the NOT (Nordic Optical Telescope, La Palma) in PYPIT.

For reference, ALFOSC's web page is: http://www.not.iac.es/instruments/alfosc/

**Comment by bomilvangjensen** [comment]
Update: the code for ALFOSC is found in branch alfosc. Test data are found in
https://sid.erda.dk/share_redirect/CUMrAAeWkP/alfosc_testdata_milvang_5.tar.gz

Status:

pypit_setup works, except the standard frame (ALAa290065.fits) is not correctly classified (I was trying to use the exptime to split standard and science; maybe I don't understand the syntax of the settings file), and therefore has to be added manually.

run_pypit works until it crashes in a bspline fit for the sensitivity function ("Problem in the bspline knot"). I understand from Ryan that this has been seen for other spectrographs, so perhaps a common fix to this is possible.

Some limitations:
- ALFOSC has a different binning in x and y, header keywords DETXBIN and DETYBIN, and this is not handled (the 1x2 binning of the test data is hardwired into the definition of the overscan and data regions in the settings file)
- The test data have 4 types of arcs: He, Ne, HeNe and ThAr, which presents two issues:
  - A NIST line list is lacking in PYPIT for ThI, so ararc.py just says lamps=['HeI','NeI','ArI']
  - PYPIT seems to combine all the line lists stated in ararc.py, without the option to only consider the lines relevant for the given arc frame

This information is just FYI.

**Comment by profxj** [comment]
@bomilvangjensen -- Would be 'easy' to implement ALFOSC now, I think.

Let me know if you still wish to do so.  Am otherwise closing for now.
