### ISSUE TITLE
Record original headers

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#251]
Record most of the information from the raw file headers
(modulo things like NAXIS1) in the spec1d and spec2d files.

Or as a separate file.

**Comment by rcooke-ast** [comment]
I agree with this, but I think we should keep the most important properties (i.e. the ones we explicitly ask PYPIT to load) in the same file. We could easily copy paste the entire raw header into a separate file.

**Comment by profxj** [comment]
This was started by PR #262

**Comment by profxj** [comment]
But only a subset are taken.

**Comment by kbwestfall** [comment]
This is a pretty old issue.  What's left to do here?

**Comment by profxj** [comment]
This has been done for the spec2d files.

Closing while we consider whether to do it also
for the spec1d.
