### ISSUE TITLE
ARMED suggestions

### ISSUE THREAD

**Issue by rcooke-ast** [pypeit/PypeIt#287]
Over the years, I've collected a bunch of ideas and suggestions for ARMED, and I list them here for safe keeping:

* model spectral orders in 2-dimensions
* resample only once --- user specifies pixel size
* fit spectra using vacuum wavelengths
* spectral resolution (use seeing and arc lines)
* convert to a CMB and/or barycentric frame
* take into account gaps between detector pixels
* pixel size from stamping the detector (read in a map of the pixel size for each detector)
* user-specified function that described the profile to be used for the arc lines.
* use line selection algorithm from Michael Murphy's paper.
* remove extra-order saturation
* implement a basic final combination technique
* option to not resample (spit out things as a pixel-size)
* Trace atmospheric dispersion correction.
* user chooses how to extract (should it be a Gaussian, some other function).
* apodization of object at slit edge (Adrian Malec made this modification in HIRES redux.)

**Comment by kbwestfall** [comment]
Closing, but would be useful to open additional issues based on any of these.
