### ISSUE TITLE
Incorporating telluric correction 

### ISSUE THREAD

**Issue by AlexaVillaume** [pypeit/PypeIt#297]
I coded up a way to telluric correct the LRIS R 800/10000 grating spectra and I'd like feedback on the implementation and any thoughts on the best way to implement it in PYPIT. I've created a PR so the code can be looked at and here I'll explain what I did:

First,  I commented out line 465 in arflux.py which masks the telluric absorption bands. Then, I followed the telluric correction procedure of van Dokkum & Conroy 2012 which is basically minimizing the function, template = 1 + fscale * (atm_model - 1), and then I use the best template to telluric correct the data. I attached a figure that shows the before/after of the telluric correction for a spectrum of mine. 

This implementation only works for LRIS R for the 800/10000 grating because that's the only grating I have the wavelength-dependent resolution for. For any other instrument+grating combo to work, the wavelength-dependent resolution will be a necessary input.

I think it's best to leave it as a script to be used after the standard reduction steps. I think the only change to the PYPIT code would be to change which telluric bands are masked out in arflux.py. Some bands are definitely too extreme to be corrected in this way so they should be left as masked out. So, in that sense, it's pretty straightforward to implement in PYPIT. But maybe the main developers have opinions on how make this most useful?

![tc_diagnostic](https://user-images.githubusercontent.com/5116488/36523521-c3fe004a-1756-11e8-98c4-8fb949756ff1.png)

**Comment by rcooke-ast** [comment]
I think it would also be a good idea to check the algorithm against the spectrum of two featureless stars (e.g. two different standard stars, or a qso). This will allow us to test just how close to the Poisson limit we're getting.

**Comment by AlexaVillaume** [comment]
That's a really good point. I have standard star spectra that I can test on.
