### ISSUE TITLE
Refactor trace/object storage

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#326]
Consider using sub images to store
the info instead of full-frame images.

The current implementation generates
huge, primarily empty arrays.

**Comment by kbwestfall** [comment]
I don't know the specific context of this, but a couple thoughts:
 - Are they gzipped fits files?  I was surprised at how small a gzipped fits file can be when there are a lot of repeat values.
 - You could also store them as sparse arrays, if that's easier, but that depends on how sparse they are.

**Comment by profxj** [comment]
I should have also indicated I worry about *internal* storage in memory.

For multi-slit, e.g. 50 slits * 2 objects that is 100 float images 
per detector.  Add 8 detectors for DEIMOS and things get 
a bit large..

**Comment by rcooke-ast** [comment]
With the recent changes I implemented (now much faster), maybe it makes sense to just recalculate the regions whenever they are needed.

**Comment by kbwestfall** [comment]
Got it.  If they're very sparse arrays, the scipy.sparse module is very nice.

**Comment by profxj** [comment]
Dealt with.
