### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#329]
Using some discussion in #328 as a jumping off point... I'm not crazy about the exception handling in pypit.  I like the fact that `msgs.error` now raises an exception instead of calling `sys.exit` (I don't think the code should ever call exit unless for debugging purposes), but it will always raise PypitError.  Is there a reason to declare this exception instead of using the existing suite of python exceptions (like ValueError, TypeError, KeyError, FileNotFoundError, etc)?

I also want to understand the rationale behind having `run_pypit` hide the Traceback from the general user.  If it were me, I would essentially always be running pypit in develop mode when reducing data.  Otherwise, if it crashed, I wouldn't know if it was because of something simple, like a typo in a file name, or something deeper in the code.  In either of these case, without running in develop mode, I'd be given where the code failed and told to contact the authors.  More relevant to us the developers, if a user actually does contact us about some failure, I personally would first want to see the Traceback to see if was something quick that I can provide immediate advice on or a deeper problem that I need to dig into.  As it is, I would need to have them rerun it in develop mode and/or have them send me their data, etc, so that I could try to reproduce the error.

Sorry, this got a bit ranty, but hopefully you see my point.

**Comment by rcooke-ast** [comment]
I think the original goal was to keep the printout "pretty", and include some traceback messages, but it never got implemented, probably because everyone uses the develop flag without thinking past that!

**Comment by kbwestfall** [comment]
Similar to #405, but maybe this raises the larger question of when/if we should be using `raise ...` vs. `msgs.error()`.
