### ISSUE TITLE
Overload fracignore

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#333]
Overload fracignore such that:

```
if fracignore < 1.:
   # Interpret as a fraction of the detector
else:
  # Interpret as number of pixels
```

Used for ignore small slits (e.g. star alignment boxes)

**Comment by kbwestfall** [comment]
How does this fit in with the new `min_slit_width` parameter in `TraceSlits` ?

**Comment by jhennawi** [comment]
I think fracignore is now deprecated and should be removed.

**Comment by profxj** [comment]
Deprecated
