### ISSUE TITLE
Consider writing all 2D images as float32

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#339]
Except when float64 is required (e.g. wavelength image)

**Comment by kbwestfall** [comment]
Are you mostly concerned with saving disk space?  If so, do you gzip files?  There's a bit of a slow-down in terms of I/O, and we should check what we actually gain in saving space.  Also, worth noting that writing the fits image with astropy and then gzipping with the python gzip package can be faster than having astropy do both by writing to a `*.fits.gz` file.

**Comment by profxj** [comment]
Yes, disk space.  But you are write it is worth
checking on how much.

And I agree, avoid at all costs having astropy do the gzip.

I've been spawning but maybe I should use the Python package
just in case.

**Comment by kbwestfall** [comment]
I did this test a while back for MaNGA and I don't remember the result.  I think subprocess vs. using the gzip package were pretty close, maybe with a slight edge to the subprocess.  I don't know if there's any rational reason for this, but I tend to avoid subprocesses in python code, unless it's main purpose is to run the process.

**Comment by profxj** [comment]
We are sticking with 64
