### ISSUE TITLE
generate_sensfunc should operate on an astropy table not a python std_obj. 

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#344]
https://github.com/PYPIT/PYPIT/blob/24b39b0e93d7921885a448ece7954184f7fb8a98/pypit/core/arflux.py#L434

generate_sensfunc is a core routine that should not require any objects as input. If you look at the code the std_obj definition is totally superfluous.  It should just operates on tags in an astropy table. 

If someone wants to use this code they either need to figure out how to instantiate these objects, or write a class that looks like what this routine needs. I don't see the point of that. Why not just operate on an astropy Table?

I might be missing the point of the SpecObjExp class, but I don't see why this thing is not just an astropy table. The methods attached to this class appear to be rather trivial and unnecessary, but maybe I'm missing something.

**Comment by profxj** [comment]
I think a Table would be unnecessary here.  How about
you refactor it to just take:  wave, counts, var as ndarray's?

**Comment by jhennawi** [comment]
Sounds good will do that.

**Comment by profxj** [comment]
is this done @jhennawi ?

**Comment by EmAstro** [comment]
Done!
