### ISSUE TITLE
Slit profile / illumination flats

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#347]
Starting a thread on these.  Inviting discussion from
@jhennawi  and @rcooke-ast

**Comment by rcooke-ast** [comment]
What is it that you would like to discuss? Is the current algorithm not working very well? I think it makes sense to do a b-spline fit followed by a PCA (for ARMED).

**Comment by profxj** [comment]
I suspect it is mainly clarification on the algorithm
but I'll let @jhennawi ask.

**Comment by kbwestfall** [comment]
Is this addressed in #478 ?

**Comment by jhennawi** [comment]
Flats completely revamped. Closing this issue.
