### ISSUE TITLE
ParSet settings for classes:  In the Class or in pypitpar?

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#369]
I have been advocating to have all the settings in one module, 
like arparse.py or the new pypitpar.py.

But if we sync up individual ParSets to the calibration classes
(e.g. ```BiasFrame```), then I can see advantages to having
them defined within that module (biasframe.py) instead of pypitpar.py

Discuss..

**Comment by kbwestfall** [comment]
Right, I'd like to see the parsets be defined in the files that are relevant to the class they're used in.  E.g., I think it makes sense to have `TraceSlitsPar` be defined in `traceslits.py` alongside `TraceSlits`.  That example is pretty clear cut, but there may be more subtle examples where a given `ParSet` is used by multiple classes/modules.  Then we'll have to think harder about the code organization...

**Comment by profxj** [comment]
Closing.
