### ISSUE TITLE
Begin proper tagging of PyPit

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#371]
As titled

**Comment by kbwestfall** [comment]
Should we create/group a set of issues that we'd like to resolve into a version 0.8 milestone?

**Comment by profxj** [comment]
Very good idea.  I think there is a way to put them in milestones.
let me try

**Comment by kbwestfall** [comment]
Looks good to me.  I also included bumpversion in #376 to hopefully make keeping track of versioning a bit easier.

**Comment by kbwestfall** [comment]
This is done now.  See procedure in #420
