### ISSUE TITLE
Instrument specific header reading needs to be implemented 

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#375]
Hi All, 

There are too many instrument parameters which are currently passed in as settings to the ProcessImages class and its children, which could simply be taken out of the fits headers.  Given that the ProcessImages class operates on files, there is no reason why the user needs to pass in all these settings. 

I think we need to move from all of these settings keywords, and toward a mode that uses headers as soon as possible. Please keep this in mind during the settings makeover. 

In my opinion the only parameters that ProcessImages needs to take are a filename, and a detector number. All other params/settings should be optional. This is currently how the class is constructed, but some children of this class require things like datesec_img, which they should not. 

Joe

**Comment by rcooke-ast** [comment]
How about we create a Frame class in each `instrumentName.py` file? That way, with every fits file read in, we don't need to pass around a data file *and* a header (or multiple headers, in the case that multiple headers contain the required header information). We can use decorators on some methods in the class, as needed. That way, we can load a file with just a fits filename:

`frame = Frame("filename.fits")`

and if we wanted to get say, the x binning, we could simply call `frame.binx` and that would be the same throughout the entire code. In other words, all of the header information that needs to be loaded for each instrument, it will be done in each dedicated Frame class. Similarly, we could have a `frame.data` etc. where the data can be transposed as needed.

My original thought was that we could start passing this frame class to processimages instead of a fits file and or data+header. But, all that said, I think we could pass a fits filename to processimages and generate this frame class at the top of the class. This would cause some overhead, if we had to load it in every time, though, but it's probably better than having to store all of the images in memory.

This could be in addition to the Instrument Class (or they could possibly be combined). Anyway, it's another possibility that might be worth considering.

**Comment by jhennawi** [comment]
Hi @rcooke-ast, 

Let's discuss further in Marseille. I agree with using classes to do this when it makes developing and using the code faster and more elegant. That is not the case for the current settings and setup model. 

For example internal to process images, as you suggest,  one can instantiate the frame class and/or the instrument class from filename and image header, and use it code more elegantly and understandably, with all the header parsing taking place under the hood in the spectro class. The header parsing takes microseconds, so I don't think there is a speed or overhead issue. 

The question is whether the interface to the base classes (FlatField, or WaveImage, etc.) is easier or
more complicated to use with objects as opposed to filenames and headers. I'm of the opinion
that there is no need to wrap filenames,  headers, or images in a class, since the class will probably always be less familiar to the user. 

I struggled with all of this recently when were were trying to write a quicklook pipeline for NIRES, and do development of the eventual NIRES pipeline in PYPIT. The interface to the base classes is just unnecessary complicated, and it was very difficult to figure out which settings incantations, and which arguments needed to be passed, and which operations needed to be run before others. 

That is why I want to push for the simplest possible argument lists to those classes. In principle, they should only take as arguments files, headers, and something like tslits_dict which the routine crucially depends on. If they actually only need the slitpix image from tslits_dict, then this is preferable to passing the entire dict, since it is more transparent what the code operates on. If you need 5 things from tslits_dict, then obviously the shorter argument list is simpler. Do you see my point? There is also
then less documentation to maintain and update 

Right now the base classes take many arguments related to the master file creation. This is silly in my opinion, since we know what the master filename should be (or it can be known if we passed in the header), and so there is no reason why instrument, config, setup, and all these optional params need to be passed in. The only necessary thing is filename, hdr, and det = None. 

Now I'm willing to be convinced that if there is a simple single call to an instrument class at the beginning of running PYPIT or PYPIT-lab (what I want to call our development environment) then it may be simpler and more transparent to pass this object back and forth, and then the user would know exactly where the instrument specific stuff is being loaded, and which module to look at. That said, I don't understand how this will work, because as the driver runs or PYPIT lab runs, instrument specific information needs to be loaded in progressively. For example, if you are doing flats and biases, this could be setup independent, but once you touch an arc, there are more instrument specific things you need to do. So I fear the model we adopt is then that the spectro_class gets passed in and updated as you run the pipeline, and I'm *loathe* to do that, because then you are basically toggling global variables and settings in that object in a way that the user will have difficulty understanding. This then makes it rather hard to debug because I need to know if something got changed in the spectro_class object. 

Do you see my point? If the spectro class comes into being and then dies inside some internal routines based on parsing header information, then I never have some immutable object being passed around that causes future code failures. 

If we use the header rather than an object, then the user can still look at a single file in the spectro class to understand the instrument specific things. 

Joe

**Comment by rcooke-ast** [comment]
Hi @jhennawi, That all sounds good. The only concern that I have with passing headers is that sometimes the information that you need is in two headers (e.g. the post-2004 HIRES format). So, I think headers are not a good idea, partly for that reason. I'm OK with passing a fits filename, but I feel that the user shouldn't concern themselves with the details of the fits file. Hence my idea for creating an (immutable) class whose function is to take a fits filename and have the ability to return all of the relevant information about the file. The class that I propose above should not store anything that's derived from the input frame(s). Its purpose is solely a convenience function that is effectively a container for that fits file. You won't be able to set anything in the frame class, it will only return properties of that fits file.

Note: I won't be attending the conference in Marseille. I had to pull out (a few months ago - it took me a while to realise what you meant). But, we can discuss this during the next telecon, if time permits.

**Comment by jhennawi** [comment]
Hi @rcooke-ast, 

Sorry to hear that I'll miss you in Marseille. I'm fine with the frame class that you suggest, but I'd probably prefer that it be instantiated in the base classes, rather than be a required argument to them. On the other hand, I can see an argument for doing it the other way if that results in more elegant code and a simpler interface. 

The main reason we are having this discussion about using something besides the filename as input, is that occasionally we pass an image to the base class rather than a filename. This occurs for example if we create an msarc image, and then want to use it for both the wavelength solution in say WaveCalib, as well as for the tilts, in WaveTilts. The idea being that we don't want to read in the files twice and do the combines twice, which would be the requirement if everything ran on files or file lists. 

That said, this computational cost is not that significant, and my argument would be that it makes for much simpler code interfaces if most/everything runs on a fits files or a file list, rather than on an image and a class in some cases and on filenames in other cases. 

In principle, we can have from_file or from_hdr or from_class method options as input. But we should decide on what the default mode is for the required arguments, and I think we should aim for what creates the simplest most robust interface with the fewest number of failure modes.  

Joe

**Comment by rcooke-ast** [comment]
That all sounds sensible to me, and I agree.

I only have an issue passing a fits file around, since that is anyway (effectively) a class. By creating our own frame class we can repackage the data and header in a way that makes it easier for us to code.

I'm certainly in favour of passing around a filename. As you said, this will forcibly refresh the data/header without any extra concern to the user.

However, with the amount of development going on, it seems sensible that we let the dust settle a little before making any final decisions on this matter.

**Comment by jhennawi** [comment]
Thinking about this more @rcooke-ast, I think that your spectro-class instrument reader can just concatenate two hdrs from HIRES, and pass that back as the header. So I'd argue that arguments to the base classes should be filename or hdr, but inside the base classes one could use the Frame class to make the coding more elegant.

**Comment by kbwestfall** [comment]
I think this is solved by having all the instrument-specific parameters in the relevant children of the `Spectrograph` class.  Closing, but feel free to reopen if you think we're not done with this.
