### ISSUE TITLE
Insure every core method/class has at sufficient doc strings

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#377]
For v1.0

**Comment by kbwestfall** [comment]
Just to add to this...  When building the docs with sphinx following:

```
cd ./doc
make clean
make html
```

a `sphinx_warnings.out` is produced that lists all the problems that sphinx encountered in the doc strings.  We should aim to limit these as much as possible.

**Comment by profxj** [comment]
Nearly satisfied by #1269
