### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#378]
I trolled through the issues because I thought this had already been raised, but couldn't find the relevant issue.  Sorry if this is a repeat.

It says in the docs that we plan to deprecate python 2.7 support.  Is there any reason not to do this now? ... please :)

**Comment by kbwestfall** [comment]
Setting milestone to 1.0, but could be earlier.

**Comment by profxj** [comment]
I think @rcooke-ast is our main hold-out  :)

**Comment by jhennawi** [comment]
Python 2.7 is the new IDL folks. May it rest in peace.

**Comment by rcooke-ast** [comment]
Just for the record:

IDL's first release = 1977
Python's first release = 1990
Python 2.7 release = 2008
Python 2.* no longer supported = 2020

I'm happy to move to python 3 as well, I'm only sticking with 2.7 if users need help debugging `2.7.x` issues... It seems that we need to have fully moved over within the next couple of years though, so perhaps now is as good a time as any to say goodbye...

**Comment by profxj** [comment]
That a boy.  

We move with v1.0 as per the Milestone on this Issue.

**Comment by profxj** [comment]
Accelerating to v0.9.  

@rcooke-ast -- Prepare yourself...

**Comment by profxj** [comment]
2.7 is gone
