### ISSUE TITLE
Remove the now defunct debug thing in PyPit

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#384]
Not debugger, debug.

**Comment by kbwestfall** [comment]
Can you clarify?  Does you mean that we should basically be removing
```
from pypit import ardebug as debugger
```
anytime we see it?

**Comment by profxj** [comment]
Sorry, quite the opposite.  It is code like this:

```
# For out of PYPIT running
if msgs._debug is None:
    debug = debugger.init()
    debug['develop'] = True
    msgs.reset(debug=debug, verbosity=2)
```

**Comment by kbwestfall** [comment]
Okay, I'll start removing this anytime I come across it.

**Comment by profxj** [comment]
I think we are most of the way there now.
