### ISSUE TITLE
PyPit or PipeIt?

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#388]

**Comment by rcooke-ast** [comment]
According to the meeting notes, I think the decision was between PypIt and PipeIt.

**Comment by profxj** [comment]
Right you are.

**Comment by kbwestfall** [comment]
+1 for PipeIt

**Comment by jhennawi** [comment]
As much as I've fallen with PYPIT, my vote wold be fore Pypeline. Makes it more clear what we are doing at the expense of a slightly longer name.

**Comment by rcooke-ast** [comment]
I second the suggestion by @jhennawi. Note that as an organisation, [pypeline](https://github.com/pypeline/pypeline/) is available but [pipeit](https://github.com/pipeit/pipeit/) has already been taken...

**Comment by profxj** [comment]
When I go to add an Organization on GitHub, I find the following are taken:

pypeline
Pypeline
PypIt

Actually I think any capitalization schema is taken for those.
Not sure the names are really case-sensitive.

The following are available:

PipeIt
PypeIt

I've just taken both.  Have to say I'm rather fond of how this looks:

https://github.com/pypeit

**Comment by profxj** [comment]
This is just fine by me too:

https://github.com/PipeIt

**Comment by tiffanyhsyu** [comment]
Between PipeIt and PypeIt, my vote would be for PipeIt!

**Comment by rcooke-ast** [comment]
Between PipeIt and PypeIt, my vote is also for PipeIt.

I've also tried to think of a few new ideas too, but I've come up (pretty much) empty handed... I'm not particularly good at this kind of thing, though.

RAPAD (pronounced "rapid") - Reduction And Processing of Astronomical Data
ROAD - Reduction Of Astronomical Data  (I agree... this is a *really* lame one, but is here to make the above one look a little better)...

**Comment by kbwestfall** [comment]
If we're going further afield, how about SLit Extraction and Reduction Pipeline, SLERPy.  Well, at least it made me laugh

**Comment by rcooke-ast** [comment]
You're better at this game than I am!

**Comment by profxj** [comment]
This isn't helping..  :)

**Comment by rcooke-ast** [comment]
This topic is quickly becoming the most discussed issue in PYPIT...  :-)  So, following on from @jhennawi's pun, let me make matters worse:

HOSE - HOlistic Spectral Extraction

At some point, we should probably make a list and take a vote... history says that we'll probably end up using PYPIT...

**Comment by rcooke-ast** [comment]
I swear this is my final suggestion...

pyproc

originally this stood for ‘python process’, but could also be:

PYPeline Reduction, Organisation and Calibration.

and...

ORCA/ORCAD - Organisation, Reduction and Calibration of Astronomical data

**Comment by profxj** [comment]
PypeIt rules

**Comment by profxj** [comment]
Now we need to migrate the Repo.

Re-opening this Issue until that is done.

**Comment by profxj** [comment]
https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

**Comment by profxj** [comment]
Also good to know:

https://help.github.com/articles/about-repository-transfers/

**Comment by kbwestfall** [comment]
We've settled on PypeIt, for better or for worse :)
