### ISSUE TITLE
Revamping peak finding

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#390]
Hi Folks, 

In look at our wavelength solutions and tilts, I've found that the peak finding algorithm we are using is missing lots of obvious peaks. This is because it is pretty simplistic. We are also using two different algorithms at the moment, find_minima and detect_lines. 

This blog post has a nice summary of alternatives in python, all of which look better than what we are using. 

https://blog.ytotech.com/2015/11/01/findpeaks-in-python/

Joe

**Comment by jhennawi** [comment]
I've mostly addressed this, but still need to add the new algorithm to the object finding code, so I'm leaving this open.

**Comment by profxj** [comment]
Can we close this @jhennawi ?

**Comment by jhennawi** [comment]
Yes it is been fixed.
