### ISSUE TITLE
Can we discuss a new naming convention for masters?

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#401]
Hi All, 

I'd like to avoid having to pass setup as an explicit argument when running all the base classes. The point is that the master is constructed from a file is known since it is an argument to e.g. flatfield.py, and all the information pertaining to that master exists in the hdr for that file, i.e. spectroscopic setup, filename if needed, binning, etc. So why does the user need to deal with this?

If the filename is uniquely determined from the setup, then basically flatfield.py can  default to trying to read in the master file if mode = master. 

I can see problems arising when one is using the same grating at several central wavelengths that differ by a tiny amount, but this is solvable. 

Maybe the answer is that pypit_setup creates, classifies, and names the setups, and that this naming is necessary to dump the master files to the correct sub-directory of MF.

If so I suppose I can live with it. 

Joe

**Comment by profxj** [comment]
By all means propose a better solution than the current.
