### ISSUE TITLE
Make the -d option permanent (not an option)

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#405]
Can't recall if this was already in an Issue.

**Comment by kbwestfall** [comment]
This was effectively accomplished in #400 by commenting out the code in `run_pypeit` that prevents spitting out the Traceback.  The -d option now just changes the detail in the messages.  We could make this part of the verbosity?  I guess I'll leave this one open for now.

**Comment by rcooke-ast** [comment]
Addressed by PR #435
