### ISSUE TITLE
Make PypeIt pip installable

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#414]
Should be done before #412 .

**Comment by profxj** [comment]
Can you teach me how to do this for linetools too?

**Comment by kbwestfall** [comment]
Yep, will do.  I need to figure out myself first, but the SDSS people have some short instructions on how to do this, so I'm hoping it will be straight forward.

**Comment by profxj** [comment]
See:

https://sdss-python-template.readthedocs.io/en/latest/#deploying-your-product

**Comment by profxj** [comment]
And there we are:

https://pypi.org/project/pypeit/

**Comment by profxj** [comment]
Done.
