### ISSUE TITLE
Flat field bug

### ISSUE THREAD

**Issue by rcooke-ast** [pypeit/PypeIt#418]
It seems that, in `arflat.flatfield`, the `mspixelflatnrm` is multiplied by the slit profile... but `mspixflatnrm` already contains the slit profile, so this shouldn't be done (it's probably a bug).

We should think more about whether or not we should pass around the blaze function, slit profiles, and pixel to pixel variation separately.

**Comment by profxj** [comment]
My fault for sure.

**Comment by profxj** [comment]
Addressed
