### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#421]
Is there a specific reason why we're using the GPL license?  Is this because we were using GSL before and so we had to distribute under GPL?  Now that we're not using GSL, what do people think about using a license that isn't copyleft (i.e., a license that doesn't require anyone that incorporates pypit functionality into other software to also distribute under GPL), like MIT or BSD.  I'm mainly asking because SDSS recommends BSD3.

**Comment by jhennawi** [comment]
I defer to your judgement @kbwestfall as you probably know a lot more about this then the rest of us.

**Comment by rcooke-ast** [comment]
I originally setup the license, and I don't remember the reason for choosing the GPL license... it may have just been the first one on the list... so we can change without a problem, I think.

**Comment by profxj** [comment]
I suggest we go for BSD3

**Comment by profxj** [comment]
Modified.
