### ISSUE TITLE
spectrograph class needs to know the date for instantiaion

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#425]
Hi All, 

Currently we are instantiating the spectrograph object based on an instrument name, i.e. basically a string. In reality spectrographs change with time, for example the LRIS red detector. So to properly instantiate the spectrograph class, one actually needs to know the name of the instrument, as well as the date that the data was taken. 

I think the following line in arms.py needs to be modified to accommodate date in the fitstbl so that we can properly reduce LRIS data. 

        _spectrograph = load_spectrograph(spectrograph=fitstbl['instrume'][0])

Joe

**Comment by rcooke-ast** [comment]
I don't think this is needed. There can be a method inside the spectrograph class that, when passed a fits file and/or header, knows how to obtain the date, and information about the data.

Unless the spectrograph class has changed in recent times, I think this is just a container of methods that are instrument specific. By passing in data/headers to these methods, the methods know how to deal with the data/headers.

**Comment by jhennawi** [comment]
Okay I think we are advocating for the same thing @rcooke-ast. Now I see that actually the spectrograph class just will use the lris reader and the lris reader can then parse the data.
