### ISSUE TITLE
constant failures in slit tracing

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#431]
Hi All, 

The slit tracing algorithm that we are using needs major work. It appears to be working fine for rectilinear slits, but it is having major problems for curved orders. There are two scripts in the dev suite that illustrate the problem. They are at dev_algorithms/dev_xshooter_nir.py and dev_algorithms/dev_xshooter_vis.py. You need to switch to the branch dev_nires_run in order to access these scripts. The XSHOOTER and NIRES data are in the master branch of the dev suite now, but you'll need to fetch the tar balls (follow the instructions in the README). 

These should work directly out of the master branch in PYPIT, where all the xshooter spectrograph class stuff now all exists. 

Joe

**Comment by rcooke-ast** [comment]
Hi @jhennawi - All you need to do is change `par['calibrations']['slits']['sigdetect'] = 300.` and the tracing seems to work just fine.

I agree, that maybe this parameter is a little sensitive to the instrument and/or the data. Maybe we can figure out a way to better determine what this parameter should be automatically...
