### ISSUE TITLE
Documentation on parlist settings refactor is not up to date

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#434]
Hi @kbwestfall, 

Are the automatically generated docs live yet. I don't see them on https://pypit.readthedocs.io. 
It would help @EmAstro and @feigewang to be able to read docs on this. Do you have anything to send us until we get the docs up, a screenshot even. 

Thanks,
Joe

**Comment by profxj** [comment]
It's not building on readthedocs.  Will take some sleuthing to figure it out.
For now, do this:

cd docs
make html
open _build/html/index.html

**Comment by kbwestfall** [comment]
This is tied to #447

**Comment by profxj** [comment]
we are now ingesting these into the repo.
