### ISSUE TITLE
Eliminate dead branches

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#442]

**Comment by rcooke-ast** [comment]
OK - I've cleaned up _a lot_ of the stale branches. I suggest that everyone now go through the branches that you've created (you can check this from the home page of pypeit - click [this link](https://github.com/pypeit/PypeIt/branches) to see your branches).

If you have a stale branch, either:
(1) Delete it if you no longer intend to develop on it
(2) Bring it up to date by merging the current master branch into it
(3) Branch off the current master branch, and insert those bits of code that you desperately want to cling on to! (Then, delete the stale branch).

This should be done before the release of v0.9 - thanks!

**Comment by profxj** [comment]
I trimmed the ones I could.

**Comment by profxj** [comment]
I think we are best we can do for now.
