### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#443]
I get the following failures when running the unit tests on master:

 - `test_run()` in `test_flatfield.py`
 - Tests in `test_flux.py`, `test_fluxspec.py`, `test_load.py` fail and all point back to line 271 in  `pypeit/pypeit/core/load.py`
 - Both tests in `test_setups.py` fail.
 - `test_geocorrect(fitstbl)` in `test_vcorr.py`, which points back to a specobj issue.

Can people run the tests and see if they immediately know (and can fix) the issue?

**Comment by profxj** [comment]
Addressed by PR #444

**Comment by kbwestfall** [comment]
Fixed in #444, closing.
