### ISSUE TITLE
Header Keyword Defaults

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#449]
I just tried this:

```
# imports
import os
import glob
from pypeit import pypeitsetup

files = glob.glob(os.path.join(os.environ['PYPEIT_DEV'], 
                               'RAW_DATA/Keck_DEIMOS/830G_M/*.fits.gz'))
setupc = pypeitsetup.PypeItSetup(files, spectrograph_name='keck_deimos')
par, spec, fitstbl, setup_dict = setupc.run()
```
and I get these warnings:
```
[WARNING] :: load.py 102 load_headers() - DICHNAME keyword not in header. Setting to None
```
All this is just to say that we need to go through and make sure things in `Spectrograph.default_header_keys` are either defaults for all spectrographs or make sure this function is over-ridden by the child classes when necessary.

PS - The above code fails to type the DEIMOS files, which we should also fix.  I'm switching to reading the pypeit file in the dev suite with the files already typed for the meantime.

**Comment by rcooke-ast** [comment]
I think this is also the root of LRISr failing in the dev suite.

**Comment by kbwestfall** [comment]
I think it is out of date, as of #526.
