### ISSUE TITLE
Nonsense outputs for WHT_ISIS_blue in dev suite

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#458]
Hi All, 

WHT_ISIS_blue is producing complete garbage in the test suite. I've tracked down the problem to the MasterFlat which has nonsense values. I'm not sure what is causing this issue in the flat field code, but it leads to crashes because the data is completely garbage after being divided by this image. 

We need to either fix this issue or remove this from the dev suite. @rcooke-ast would you mind taking a look at what causes the flat fielding code to go berserk?

P.S. Image r2324580.fit.gz is saturated and should be removed from the dev suite and the pypit file. It would be good idea to vet images for problems before putting them in the dev suite. Note however that this issue is not the source of the problem, since I get garbage even when excluding it.

**Comment by rcooke-ast** [comment]
This should be raised in the dev suite. Closing, and raising there.
