### ISSUE TITLE
PypeIt keck_lris read_lris cannot handle old LRIS data

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#465]
The read_lris function is a port of the IDL routine x_readmhdufits. But this function fails for old LRIS data that was packaged differently. For example pre 2009-07-01, LRIS images were single extension fits files. 

long_oscan.pro in LowRedux has the albeit messy logic to deal with previous versions of the LRIS red CCD as well as header and image packaging. The port to PypeIt was not done completely, and instead only the x_readmhdufits. The full port needs to be accomplished to reduce old archival data.

**Comment by amanda-olmo** [comment]
Hi, is there any update on this topic? I am using Pypeit to reduce some archival spectra from LRIS instrument. 
I have a problem with the performance of the pipeline in some data from 2006 to 2010, so it may be related to the fact that these data are not yet supported. Pypeit returns an error on the header of the spectra, they are missing keyword "lampstat01”. If you think it is not related, I can submit a new issue with more information.

**Comment by profxj** [comment]
Hi @amanda-olmo -- I suggest you:

1.  Join the PypeIt Users Slack.
2.  Generate a test dataset for development.

**Comment by profxj** [comment]
WIP on the `old_lris` branch

**Comment by profxj** [comment]
See the PypeIt Users Slack for more.
Am asking @amanda-olmo to perform additional tests.

**Comment by profxj** [comment]
Largely addressed
