### ISSUE TITLE
traceslits master file output needs to be updated. 

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#471]
Everything downstream in the code uses the tslits_dict dictionary. Currently in order to get to the tslits_dict dictionary one has to reload the class from the master file (which does not contain tslits_dict, but a bunch of other stuff which is not what the code uses) using the master method, and then invoke several different incantations from the traceslits class in order to final get what the code needs. 

@profxj can you please address. How about we just write out the tslits_dict to json in place of what you are currently writing to json which is not what downstream functionality needs.

**Comment by jhennawi** [comment]
This is an easy fix, so I'm moving to v0.9. You just need to slightly modify the class to write out the master file that the code actually needs.

**Comment by profxj** [comment]
the items being saved are key for debugging and simply to 
reconstruct the object from disk.  The tslits_dict is generated with
a single call.

**Comment by jhennawi** [comment]
In opinion, the master files should not be thought of as reconstructing all the information in the object from disk. Let's discuss.
