### ISSUE TITLE
Odd lines in several spectra output

### ISSUE THREAD

**Issue by nvvazque** [pypeit/PypeIt#473]
I am an undergrad working with Caitlin Johnson on reducing optical data using pypit, I was told to submit an issue here about some of the results we have been getting. I've attached a couple of the output that we got from reducing the data and in the spectra there seem to be a couple of constant lines that we think may come from an issue with the sky subtraction but we are not sure. There are a couple obvious ones around 4300, 4750 and 5000 angstroms. Any help on this issue would be great! 

Note: We are using the dev v0.8.0 version of PYPIT.

[Spectra-3.pdf](https://github.com/pypeit/PypeIt/files/2341188/Spectra-3.pdf)

**Comment by profxj** [comment]
are these Kast spectra?  

If so, I suggest you meet with @tiffanyhsyu 
or Marie Lau at UCSC.  They are both experts.

If not, you need to provide more info.

ps.  Better to attach PNGs than PDFs for viewing on GitHub.

**Comment by jhennawi** [comment]
I think this is also the old extraction which is known to have sky
subtraction issues
