### ISSUE TITLE
LRIS red long slit crashes with slit finding error

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#481]
Please address this @profxj since you are the slit finding master. 

Check out the dev suite for long_600_7500_d560. I've made a pypeit file for this setup by hand (because previously we were relying on pypeit_setup which was broken, so this test never ran). Now the pypeit_test script will run it. 

Joe

**Comment by jhennawi** [comment]
@profxj has this been fixed?

**Comment by profxj** [comment]
fixed
