### ISSUE TITLE
Arclines now failing on DEIMOS dev suite (830G_M_8100_37)

### ISSUE THREAD

**Issue by freddavies** [pypeit/PypeIt#491]
When I originally added the 830G_M_8100_37 setup to the dev suite, arclines did not complain about the accuracy of the wavelength calibration. However, the standard method now fails on both detectors 3 and 7 (the ones with actual arcs) due to somewhat poor RMS (0.115 and 0.193, respectively) and crashes PypeIt because there are no other slits to cross-match to.

I checked my old dev suite QA images and the RMS on both detectors was the same before, so I guess this is happening due to a change in the cross-matching behavior. The initial fit should probably not be thrown out if there are no other slits, or maybe `rms_threshold` should be somewhat higher.

**Comment by jhennawi** [comment]
Fixes to peak finding and cutting out saturated lines fixed this.
