### ISSUE TITLE
test_flexure test is unstable and/or incorrect

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#492]
Hi All, 

The recent changes to the arc.detect_lines function in PR #489 is resulting in a new failure in the test_flexure.py test. This code is using the the lines only in a preliminary step where it determines the resolution. I don't see why it should be so sensitive to this. I suspect the code is unstable or has issues. 

This is evidence by the two plots below based on this step. The value of the shift that the master branch preferred is 15.7, which is the first plot attend labeled master.png. The new arclines_ThAr wants the shift to be -19.2, which is the second plot. Neither of these look correct to me. 

![master](https://user-images.githubusercontent.com/8774563/45471325-9c3fe800-b6e5-11e8-9c43-2de0d46fe64c.png)

![arlines_thar](https://user-images.githubusercontent.com/8774563/45471334-a2ce5f80-b6e5-11e8-8cd6-5bdf569398a6.png)

**Comment by kbwestfall** [comment]
I think I may have fixed this.  See #503 .  The shift is 43.7 pixels, which I confirmed by applying the shift and overplotting the result.  The only thing I changed is the maximum shift allowed (`mxshft=60`).

**Comment by jhennawi** [comment]
Hi @kbwestfall, 

43.7 pixels is a ridiculously large shift. This is not really the best test since it is so atypical. Perhaps @profx can comment. 

Joe
