### ISSUE TITLE
arcparam needs to become a parset

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#504]
Hi All, 

Currently the arcparam, setup_arcpara and all this stuff for arclines is a mess. It is particularly challenging to figure out which of these parameters arclines actually uses and furthermore none of this stuff is documented. Right now the arcparam is a dictionary defined in each spectrograph class. My suggestion is that we make this a parset, document it like the other parsets, and then modify the defaults in each instrument class file. In other words, let's treat this like all the other parameters. 

Right now arclines is the only method we use, and furthermore within arc.py the semi-brute and basic methods are no longer used either. I would not worry about any backwards comptability, since I think these methods are now defunct (@rcooke-ast can maybe comment).

Another reason why arcparam needs to be a parset is the unfortunate way in which DEIMOS calibrates blue setups. You can read about this at the two links below, but the upshot is that DEIMOS has a calib_blue script which turns on lamps which are different from the standard or default lamps for red setups,  but these lamps are not recorded properly in the headers. As such the only way to properly run pypeit on such arcs is to specify the lamps that were on in the .pypeit file. The only way to do this would be for arcparam to be a parset. 

https://www2.keck.hawaii.edu/inst/deimos/calib_blue.html
https://www2.keck.hawaii.edu/inst/deimos/procs/calib_blue.html

Thanks,
Joe

**Comment by jhennawi** [comment]
@profxj  is this addressed in the new gmos PR?

**Comment by profxj** [comment]
done
