### ISSUE TITLE
slit tracing crashing for DEIMOS keck_deimos_600zd_m_7500.pypeit

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#505]
Hi @profxj, 

Slit tracing is crashing for this new DEIMOS setup in the test suite. It works just fine on detector 7, but detector 3 crashes. I've commented out detector 3 for now in the test suite, but please run on this to reproduce this bug. 

Thanks,
Joe

**Comment by profxj** [comment]
no longer crashing on det=3
