### ISSUE TITLE
arc line fails for Keck_LRIS_blue/multi_600_4000_d560

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#509]
Detector number 1 works perfectly and gets sensible wavelength solutions. Detector number 2 gets some correct wavelength solutions and other very wrong ones, and then the cross-correlation fails. 

The number of arc lines errors is piling up fast. See for example issues #502 and #506. It is currently the primary failure mode in the dev suite.

**Comment by profxj** [comment]
Now passing.

**Comment by Jing-Guo94** [comment]
I’m still encountering the same issue in the LRIS_Blue/long_600_4000_d560 dataset while using PypeIt 1.17.1. I’m unsure if the issue has been resolved yet, but I’m still facing the same problem.

**Comment by profxj** [comment]
Continue this on Slack
