### ISSUE TITLE
GNIRS Slit Finding Problem

### ISSUE THREAD

**Issue by feigewang** [pypeit/PypeIt#516]
The slit tracing code is failing for GNIRS, because some orders are short. It prevents all downstream development. Could anyone help to take a look at it. This could be a common problem for echelle data. 

Thanks!

**Comment by jhennawi** [comment]
@feigewang is this sorted out with new thresholds?

**Comment by feigewang** [comment]
Hi @jhennawi ,
   I tried different thresholds. But the main parameter that we need to change is probably the PCA fitting order.  Here is the slit QA with par['calibrations']['slits']['pcapar'] = [4,3, 2, 1,0] and par['calibrations']['slits']['polyorder'] = 5. 

Feige

![slit_trace_a_01_aa](https://user-images.githubusercontent.com/23131361/46812940-9fe97d80-cd2a-11e8-9a1a-19df798136f0.png)

**Comment by profxj** [comment]
@feigewang -- Is this now resolved?  if so, please close
