### ISSUE TITLE
Required bias frames?

### ISSUE THREAD

**Issue by ChrisRsk** [pypeit/PypeIt#534]
Hello, I'm attempting to run calcheck on the following file:
# This is a comment line

# User-defined execution parameters
[rdx]
spectrograph = keck_lris_blue
    sortroot = keck_lris_blue_setup_A
[calibrations]
    [[arcframe]]
        number = 1
    [[Biasframe]]
        number = 0    

# Setup
setup read
 Setup A
 --:
   dichroic: '680'
   disperser: {angle: none, name: 400/3400}
   slit: {decker: m1149_3., slitlen: none, slitwid: none}
 '01': {binning: '1,2', det: 1, namp: 2}
 '02': {binning: '1,2', det: 2, namp: 2}
setup end

# Read in the data
data read
 path /Users/chrismac/.spyder-py3/Brian_work/Science_arc_frames/
|          filename |                date | frametype |  target | exptime | dispname |   decker |
| b170427_0007.fits | 2017-04-27T03:39:32 |       arc | unknown |       1 | 400/3400 | m1149_3. |
| b170427_0039.fits | 2017-04-27T06:24:03 |   science | m1149_3 |    1620 | 400/3400 | m1149_3. |
| b170427_0040.fits | 2017-04-27T06:51:44 |   science | m1149_3 |    1620 | 400/3400 | m1149_3. |
| b170427_0041.fits | 2017-04-27T07:19:25 |   science | m1149_3 |    1620 | 400/3400 | m1149_3. |
data end

run calcheck=True

But every time I run the code I get the following error about bias frames:

[INFO]    :: Loading the reduction file
[INFO]    :: Found 4 raw data frames
[INFO]    :: Input file loaded successfully
[INFO]    :: util.py 431 parse_pypeit_file() - Loading the reduction file
[INFO]    :: util.py 456 parse_pypeit_file() - Found 4 raw data frames
[INFO]    :: util.py 468 parse_pypeit_file() - Input file loaded successfully
[INFO]    :: load.py 153 load_headers() - Successfully loaded headers for file:
             /Users/chrismac/.spyder-py3/Brian_work/Science_arc_frames/b170427_0007.fits
[INFO]    :: load.py 153 load_headers() - Successfully loaded headers for file:
             /Users/chrismac/.spyder-py3/Brian_work/Science_arc_frames/b170427_0039.fits
[INFO]    :: load.py 153 load_headers() - Successfully loaded headers for file:
             /Users/chrismac/.spyder-py3/Brian_work/Science_arc_frames/b170427_0040.fits
[INFO]    :: load.py 153 load_headers() - Successfully loaded headers for file:
             /Users/chrismac/.spyder-py3/Brian_work/Science_arc_frames/b170427_0041.fits
[INFO]    :: load.py 156 load_headers() - Checking spectrograph settings for required header information
[INFO]    :: load.py 167 load_headers() - Headers loaded for 4 files successfully
[INFO]    :: fsort.py 103 type_data() - Typing files
[INFO]    :: pypeitsetup.py 326 type_data() - Adding file type information to the fitstbl
[INFO]    :: fsort.py 856 match_to_science() - Matching calibrations to Science frames
[INFO]    :: fsort.py 865 match_to_science() - =================================================
[INFO]    :: fsort.py 867 match_to_science() - Matching calibrations to m1149_3: b170427_0039.fits
[INFO]    :: fsort.py 921 match_to_science() -   Found 1 arc frame for m1149_3 (1 required)
[INFO]    :: fsort.py 921 match_to_science() -   Found 0 bias frame for m1149_3 (5 required)
[WARNING] :: fsort.py 986 match_warnings() -   Only 0/5 bias frames for m1149_3

[ERROR]   :: fsort.py 963 insufficient_frame_error() - Insufficient bias frames found. Include more frames, reduce the required amount by setting
             [calibrations]
                 [[biasframe]]
                     number = XX
             in the pypeit file, or specify a specificpixelflat file by setting
             [calibrations]
                 [[biasframe]]
                     useframe = XX
             in the pypeit file
Traceback (most recent call last):
  File "/anaconda3/bin/run_pypeit", line 4, in <module>
    __import__('pkg_resources').run_script('pypeit==0.8.2.dev0', 'run_pypeit')
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/EGG-INFO/scripts/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/scripts/run_pypeit.py", line 97, in main
    pypeIt.init_setup(args.pypeit_file, redux_dir, calibration_check=True)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypeit.py", line 493, in init_setup
    self._setup(self.pypeit_file, calibration_check=calibration_check)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypeit.py", line 626, in _setup
    sort_dir=sort_dir)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypeitsetup.py", line 438, in run
    self.match_to_science(setup_only=setup_only)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypeitsetup.py", line 294, in match_to_science
    and self.par['scienceimage']['nodding'])
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/core/fsort.py", line 925, in match_to_science
    code = match_warnings(calib_par, ftag, nmatch, numfr, fitstbl['target'][sci_idx])
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/core/fsort.py", line 994, in match_warnings
    insufficient_frame_error(ftag)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/core/fsort.py", line 963, in insufficient_frame_error
    + msgs.newline() + 'in the pypeit file')
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypmsgs.py", line 269, in error
    raise PypeItError("PYPIT ENDS")
pypeit.pypmsgs.PypeItError: PYPIT ENDS

I've searched through the code and cannot find the issue, are bias frames currently required?
Thank you

**Comment by kbwestfall** [comment]
Hi Chris.  What happens if you change `Biasframe` to `biasframe` ?

**Comment by ChrisRsk** [comment]
That fixed the issue, thank you. I'm kicking myself for not noticing that sooner.

**Comment by kbwestfall** [comment]
No worries!  It would be worth thinking about if we want to make user-level input case-insensitive.
