### ISSUE TITLE
PypeIt failing setup.py test after updating packages

### ISSUE THREAD

**Issue by rtlow** [pypeit/PypeIt#535]
Dear PypeIt development team,

I am an undergraduate working at UCSD who is using PypeIt to reduce LICK/Kast data for Dr. Burgasser's CoolStar lab. After updating my Anaconda packages yesterday, PypeIt stopped working. Unfortunately, I did not record which packages were updated. PypeIt now consistently fails during reduction giving an error "ValueError: invalid literal for int() with base 10: 'N'". I have attached a stack trace for this error below, as well as the log file for the most recent reduction run.

[StackTrace291020182032.txt](https://github.com/pypeit/PypeIt/files/2532678/StackTrace291020182032.txt)

[shane_kast_red_setup_A.log](https://github.com/pypeit/PypeIt/files/2532683/shane_kast_red_setup_A.log)

I have ran the setup.py test to see where it keeps failing, and the tests fail with the same error. I have attached the PyTest report below.

[PyTestFailure.txt](https://github.com/pypeit/PypeIt/files/2532671/PyTestFailure.txt)

I hope you can solve my issues. Thank you for your time.

**Comment by kbwestfall** [comment]
Hi.  I think this is a problem with numpy version 1.15.3.  Try reverting back to 1.15.2 and retrying:

`conda install numpy==1.15.2`

**Comment by rtlow** [comment]
Downgrading numpy has solved this issue. Thanks!
