### ISSUE TITLE
run_pypeit script keeps failing during flux calibration, even though flux standard info is available

### ISSUE THREAD

**Issue by rtlow** [pypeit/PypeIt#536]
Dear PypeIt development team,

I am an undergraduate working at UCSD who is using PypeIt to reduce LICK/Kast data for Dr. Burgasser's CoolStar lab. While PypeIt was still functioning on my computer, I had tried to reduce my first set of LICK/Kast data. PypeIt consistently failed at flux calibration. I have attached a stack trace for that error, the corresponding log file, and the .pypeit file below.

[StackTrace1810181958.txt](https://github.com/pypeit/PypeIt/files/2532722/StackTrace1810181958.txt)

[shane_kast_red_setup_A.log](https://github.com/pypeit/PypeIt/files/2532723/shane_kast_red_setup_A.log)

[shane_kast_red_setup_A (copy 1).txt](https://github.com/pypeit/PypeIt/files/2532724/shane_kast_red_setup_A.copy.1.txt)

The .fits file for the flux standard contained the RA and Dec of the standard, Feige110, and it seems like PypeIt should recognize the standard name, since it identified it in the .pypeit file, yet run_pypeit would not find that information.

I hope you can solve my issues. Thank you for your time.

**Comment by profxj** [comment]
@rtlow --  Am closing for now as fluxing is now run
outside of `run_pypeit`.

Re-open as desired.
