### ISSUE TITLE
Install instructions for ginga on main pypeit page

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#544]
I think we need to add these. Specifically, one needs the latest ginga master branch. This I believe is linked from ejeschke's GitHub.

**Comment by jhennawi** [comment]
Ginga is hosted at https://github.com/ejeschke/ginga 

To install it simply type: 

git clone https://github.com/ejeschke/ginga.git

cd ginga

python setup.py install

**Comment by profxj** [comment]
Actually, this should be my fork of Ginga.

Being addressed in `docs_gallore` branch.
