### ISSUE TITLE
docs on par['calibrations']['biasframe'] need to be clarified

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#546]
Our default behavior is to use a user input bias. This needs to be more clearly indicated. If the user does not know to set useframe = 'overscan' in the the biasframe block of the pypeit file the code crashes in a very confusing way. Try the keck_lris_blue_multi_300_400_d680.pypeit file in the dev suite
without the useframe='overscan' to see what I mean. 

I didn't see an obvious path to updating the decryption of the defaults in the FrameGroup parset because.

**Comment by kbwestfall** [comment]
Step one of this is in #559.

**Comment by profxj** [comment]
outdated
