### ISSUE TITLE
useframe bias functionality

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#554]
Try running a reduction where useframe for an arc is overscan, whereas useframe is 'bias' for science images. Calibrations reads in the msbias and then subtracts it from everything. It looks like something like the determine_bias_mode function in Biasframe.py needs to be applied in every image that reads in a master in order to decide what to do. 

This is a pretty serious bug, since someone may not want to subtract biases from everything for example if they amplifier mode for arcs or flats is different producing a different bias level. For calibrations one ought to be able to sue the overscan.

Also, in principle we should be overscan subtracting *all* images and then bias subtracting those. That is the right way to do things, and is in fact why the overscan exists at all!

**Comment by profxj** [comment]
Addressed by #700
