### ISSUE TITLE
Begin developing in new `develop` branch instead of `master`

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#560]
When we have a "stable" version of PypeIt (to be defined) we should tag it and leave the `master` branch as the "production" version of the code.  We can then create a `develop` branch that we effectively use as we're now using `master`.  I.e., we shouldn't feel too bad about "breaking" it as we converge on new functionality and new instruments.  Then when we're ready to tag again with a stable version, we merge from `develop` to `master`.

**Comment by jhennawi** [comment]
Shall we implement this in v1.0 or now, to get some practice with it?

**Comment by profxj** [comment]
It has begun
