### ISSUE TITLE
LRIS_blue trace slit issue 560 dichroic

### ISSUE THREAD

**Issue by ChrisRsk** [pypeit/PypeIt#576]
Hello,
I'm trying to run pypeit with the following image as the trace (well, one amplifier of the trace). The code is removing some edge identifications because less than 0.33 of the detector is traced, but it seems like the slits are illuminated enough to trace a greater percentage. in any case is it possible to change the percentage required? or is there another fix? thank you
![27tracefail](https://user-images.githubusercontent.com/43919137/51414379-1e726a00-1b27-11e9-8e62-7e6e4fca300e.png)

**Comment by ChrisRsk** [comment]
Sorry, my mistake. We used the 400 grism

**Comment by ChrisRsk** [comment]
Hello again, I'm currently debugging a little and I noticed in the modifications that the smash_range[0] is a string value '(0.5' and not a double near line 3103 of trace_slits.py. I'm not sure where it is assigned this, but I'm just going to grab the 0.5 and change the type at the same location for a quick fix.

**Comment by ChrisRsk** [comment]
My apologies. I found the root of the issue. in my .pypeit file I input smash_range as (0.5, 1.0) instead of 0.5, 1.0 and it was read in as a string because of this. Something that concerns me is the config_specific_par in keck_lris.py which forces the additional parameters for the 300 grism. Is something similar necessary for the 400 grism?

**Comment by profxj** [comment]
If you find this is a good solution for the 400 grism data,
then we should probably modify the defaults as per the 300.

So, let us know.

**Comment by profxj** [comment]
or, even better, submit your own PR.

Would also be good to add a portion of your
dataset to the Development suite.  @jhennawi can
give you access.

**Comment by profxj** [comment]
@ChrisRsk -- did this work?

**Comment by ChrisRsk** [comment]
For the most part yes. The code is still missing one slit and it is currently unclear why. but it is much improved with the new method. Could you specify what a PR is?

**Comment by ChrisRsk** [comment]
The code runs well on it, using the add_slits parameter can account for any missing slits. Thank you profxj. I am going to close this thread.
