### ISSUE TITLE
code crashes when flexure fails

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#580]
Currently PypeIt crashes if a single slit/object fails in the flexure compensation. This is likely happening because of a poor reduction of a slit, but we agreed that PypeIt should not crash.

A current example can be find in the coadd2d_1d_pypeit branch (soon to be master) for Keck_LRIS_red/multi_400_8500_d560 in the dev suite. The error message is: 

raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Improper sky spectrum for flexure.  Is it too faint??

**Comment by profxj** [comment]
Resolved
