### ISSUE TITLE
Problem with LRIS-R overscan for 2x1 binning

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#584]
Hi Everyone, 

Take a look at the  /Users/joe/python/PypeIt-development-suite/RAW_DATA/multi_1200_9000_d680_2x1 

This is new to the dev suite so you will need to download the files.

The reduced images are the wrong size and still contain the overscan. They should be 1024 in the spatial direction for each detector, which they aren not. It appears that something with trimming the images is crapping when we are binned. 

Thanks,
Joe

**Comment by profxj** [comment]
This was our first asymmetric binning mode and it led us to a bug.

This precipitated the over-due swapping of binspec and binspat in
the parse binning methods.

See PR #585
