### ISSUE TITLE
lris red arc solution for 400/8500

### ISSUE THREAD

**Issue by codebreaker2** [pypeit/PypeIt#599]
Here is an LRIS longslit setup.   Pypeit finds the slit but fails badly on the arc.

[keck_lris_red_400_8500.pypeit.txt](https://github.com/pypeit/PypeIt/files/2858374/keck_lris_red_400_8500.pypeit.txt)

data available for download at http://web.physics.ucsb.edu/~cmartin/data/4JoeH/rawdir_lris_red_400_8400.tar.gz

I'm not sure how to proceed.

**Comment by profxj** [comment]
Please provide the QA PNG

**Comment by codebreaker2** [comment]
![slit_trace_oiiblob_1_02](https://user-images.githubusercontent.com/47435481/52750382-f1d43580-2fa0-11e9-8085-7ff24eca0ebe.png)

This is the part of the longslit on DET-2.  No other PNGs were produced.  I

**Comment by profxj** [comment]
I see.  What is the signature of a failed red arc solution?
Is the code bombing out during the arc fitting?

Post the trace.  Thanks.

**Comment by codebreaker2** [comment]
Solved blue side problem, extra space between ‘path’ and filename.

 

Just showed Joe the red arc problem.  

 

C.

**Comment by profxj** [comment]
Good, please close the Issues as they are resolved.
Thanks.

**Comment by jhennawi** [comment]
The issue here was the fwhm parameter was not taking binning into account. This issue is fixed the my current PR #602 which is awaiting your approval.
