### ISSUE TITLE
Implementing slicing and 'all' for calib_id

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#612]
e.g.   0:17 instead of 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17

**Comment by profxj** [comment]
And set an upper limit in the PypeIt file such that a new one is made when
one exceeds 64.

**Comment by kbwestfall** [comment]
First part is taken care of in #625.

**Comment by profxj** [comment]
closing
