### ISSUE TITLE
LRIS red 400/8500

### ISSUE THREAD

**Issue by codebreaker2** [pypeit/PypeIt#617]
![image](https://user-images.githubusercontent.com/47435481/53213844-46119200-35ff-11e9-9302-60b3ea3e1a20.png)
[keck_lris_red_400_8500.pypeit.txt](https://github.com/pypeit/PypeIt/files/2892045/keck_lris_red_400_8500.pypeit.txt)

![arc_1dfit_oiiblob_1_02_s0000](https://user-images.githubusercontent.com/47435481/53213818-37c37600-35ff-11e9-8fe5-654ba0423441.png)

**Comment by jhennawi** [comment]
Link to the data is here: http://web.physics.ucsb.edu/~cmartin/data/4JoeH/rawdir_lrisr_400_8500.tar.gz.

**Comment by profxj** [comment]
Is this still an Issue @codebreaker2 + @jhennawi ?

**Comment by codebreaker2** [comment]
No.

Sent from my iPhone

On Jun 9, 2019, at 12:02 PM, J. Xavier Prochaska <notifications@github.com>
wrote:

Is this still an Issue @codebreaker2 <https://github.com/codebreaker2> +
@jhennawi <https://github.com/jhennawi> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pypeit/PypeIt/issues/617?email_source=notifications&email_token=ALJ45WMXUNGNP6TFY3WSLCLPZVHVXA5CNFSM4GZCXCXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXIQDVY#issuecomment-500236759>,
or mute the thread

**Comment by profxj** [comment]
closing
