### ISSUE TITLE
LRIS blue

### ISSUE THREAD

**Issue by codebreaker2** [pypeit/PypeIt#618]
Here is the write up of the issue we discussed for LRIS blue today.  

This tar file includes the pypeit file: http://web.physics.ucsb.edu/~cmartin/data/4JoeH/blue_issue.tar.gz

Science frames 28-31, 32, and 39-40 are processed into spec2d frames.  

The error is that Pypeit does not produce spec2d*fits frames for the other science frames.  I can tell that is does work on the other frames (like 33 and 42), but it must encounter some problem that doesn't crash it before generating the 2dspec*fits files.

**Comment by profxj** [comment]
Assumed outdated
