### ISSUE TITLE
coadd_1dspec.py fails on some slits

### ISSUE THREAD

**Issue by cnaw** [pypeit/PypeIt#619]
When co-adding the 1D spectra, the script works for all slits (~20)  but 2; I get this error (which I think are really 2 - one is about formatting for the raise ValueError  command; the other suggests that the same file could have been used twice: 
[160]cnaw@ninimma:/data/cnaw/lris5/keck_lris_red_B_2019_02_21% pypeit_coadd_1dspec breaks.yaml
[INFO]    :: Coadding 4 data frames
[INFO]    :: Using OPT extraction
Traceback (most recent call last):
 File "/home/cnaw/anaconda3/bin/pypeit_coadd_1dspec", line 4, in <module>
   __import__('pkg_resources').run_script('pypeit==0.9.2.dev0', 'pypeit_coadd_1dspec')
 File "/home/cnaw/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
   self.require(requires)[0].run_script(script_name, ns)
 File "/home/cnaw/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
   exec(code, namespace, namespace)
 File "/home/cnaw/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/EGG-INFO/scripts/pypeit_coadd_1dspec", line 11, in <module>
   coadd_1dspec.main(args)
 File "/home/cnaw/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/pypeit/scripts/coadd_1dspec.py", line 168, in main
   raise ValueError("Multiple matches to object {:s} in file {:s}".format(iobj, fkey))
TypeError: unsupported format string passed to list.__format__

This is a snippet of the yaml file; the first slitlet failed, the second one was combined successfully (after editing):

'filenames' : ['./Science/spec1d_nR2n25061_LRISr_2018Dec06T111657.418.fits','./Science/spec1d_nR2n25061_LRISr_2018Dec06T114816.790.fits','./Science/spec1d_nR2n25061_LRISr_2018Dec06T121928.992.fits','./Science/spec1d_nR2n25061_LRISr_2018Dec06T125031.517.fits']
'extract' : 'OPT'
'flux' : False
'det_2_slit_00_0070.5_0.668' :
    'object' : ['SPAT0071-SLIT0000-DET02','SPAT0071-SLIT0000-DET02','SPAT0071-SLIT0000-DET02','SPAT0071-SLIT0000-DET02']
    'outfile': 'det_2_slit_00_0070.5_0.668.fits'

**Comment by tiffanyhsyu** [comment]
I recently had the same "Multiple matches to objects in file" error during coadding of my longslit data -- I'm not familiar with coadding of multi-slit data and I'm not sure this will fix your crash, but in case it's the same issue:

Were there multiple spectra extracted in your spec1d frames, and if so, are any of them spatially close to these object you *want* to coadd? In one of my spec1d frames, I had my target extracted at, for example, SPAT0020, but PypeIt also detected and extracted a spectrum at SPAT0025 in the same spec1d frame. Even though I specified that I wanted SPAT0020 coadded, the coadd1d code still looks through all the extensions of my spec1d frame and considers any object within an object tolerance ('otol') of 10 a match (i.e., for my case, anything from SPAT0010 through SPAT0030, I believe).

Anyway, if you do have another spectrum extracted near your SPAT0071 target, you can lower your desired object tolerance in your .yaml file. There's an example of this in the [coadding documentation](https://pypeit.readthedocs.io/en/latest/coadding.html), in the Additional Coadding Parameters section.

**Comment by cnaw** [comment]
Thanks Tiffany !
Indeed - I had 2 objects in the slit and the script did its role of playing safe. Reducing the tolerance from 10 to 2 solved the problem.  We can close this issue.
