### ISSUE TITLE
previously working code is now broken

### ISSUE THREAD

**Issue by codebreaker2** [pypeit/PypeIt#640]
Hi,

I reduced LRIS Det2 successfully 10 days ago.  Then I went out of town. I tried to run Det1 upon my return, and I got an error message about spaces in the pypeit file.  I restored my original pypeit file from 10 days ago and tried to process Det2 again.   I was alarmed to learn that it no longer runs either!!

 Here is the error message.

[pypeit_error.txt](https://github.com/pypeit/PypeIt/files/2948977/pypeit_error.txt)

Please note that I am running this in the very same ipython window that I had open 10 days ago.  I am on the 'cmartin_fixes' branch that Joe created.

I also attach the pypeit file.
[keck_lris_red_OIIblob.pypeit.txt](https://github.com/pypeit/PypeIt/files/2948984/keck_lris_red_OIIblob.pypeit.txt)
(The fits files are still available at http://web.physics.ucsb.edu/~cmartin/data/4JoeH/rawdir_lrisr_400_8500.tar.gz should you need them.)

I checked that the 'cmartin_fixes' branch was still up to date, and it is.

There is presumably some simple explanation.  At the moment I'm extremely frustrated though. Can someone explain why code that ran a little over a week ago cannot read the pypeit file now?

THANKS!

**Comment by profxj** [comment]
1.  You should not be running `PypeIt` in an `ipython` window
2.  The `cmartin_fixes` branch is defunct.  You should only ever be running in `master`
3.  The `IndentationError` smells like user error to me, but @kbwestfall will need to confirm

I am unlikely to be able to explain why code you ran in a defunct branch a week ago
no longer works in that defunct branch.

**Comment by profxj** [comment]
ps.  For running PypeIt, I recommend you check out this [HOWTO](https://docs.google.com/presentation/d/14gA84R8Zcrd_mFEvg5EfR7xZjqZeUC6HjwzbQ1lGkW8/edit?usp=sharing)

**Comment by kbwestfall** [comment]
It looks like you tried to run the pypeit file as the script, instead of running the code itself.  From the command line do:
```
run_pypeit keck_lris_red_OIIblob.pypeit -o
```
I agree with @profxj that this should be how you run the code, but if you really want to do this from within an IPython session, you would need to run something like:
```
from pypeit.scripts import run_pypeit
args = run_pypeit.parser(['keck_lris_red_OIIblob.pypeit', '-o'])
run_pypeit.main(args)
```

**Comment by profxj** [comment]
closing
