### ISSUE TITLE
Shane KAST red, only half the image is traced?

### ISSUE THREAD

**Issue by rtlow** [pypeit/PypeIt#641]
Dear PypeIt development team,

I am still having issues with reducing KAST red data. The slit trace does not appear to be capturing the entirety of the data, cutting it off vertically.

![Slit_Trace_A_1_01](https://user-images.githubusercontent.com/37086221/54152241-ff42db00-43f9-11e9-92b1-d9f6f6b97c25.png)

Compare this slit trace to the actual data for HD164595, one of our telluric calibrators

![Screenshot from 2019-03-11 12-27-49](https://user-images.githubusercontent.com/37086221/54152265-0ec22400-43fa-11e9-8d99-f8fa3ec3a929.png)

PypeIt attempted to extract this spectrum using the faulty slit trace, leading to a severely truncated 2d spectrum

![Screenshot from 2019-03-11 12-28-22](https://user-images.githubusercontent.com/37086221/54152382-55b01980-43fa-11e9-824a-4494a749d66d.png)

I am unsure how to proceed from here. I have Google Drive links to the data that I tried to reduce as well as the reduction folders that I used (including the generated QAs, .pypeit files, etc.)

Data:
https://drive.google.com/file/d/11pgP0twgHMqRFPm251wjXd74L2TGjTKv/view?usp=sharing

File r1000 is the arc lamp
Files r1001-1011 are bias frames
Files r1012-1031 are dome flats
File 1033 is HD164595, a telluric calibrator
File 1035 is J1655+6224, a science target
File 1061 is Feige 110, the flux calibrator

Reduction Folders:
https://drive.google.com/file/d/1mEO-b6MG5DfdH-Q1QH_BJIzrgvSLspBs/view?usp=sharing

I hope you can assist me with my issue. Thank you for your time.

**Comment by profxj** [comment]
I think this is resolved.

**Comment by rtlow** [comment]
Dear PypeIt development team,

I updated PypeIt and its dependencies today, and this issue is still occurring on my system. I ran PypeIt again on our dataset, and PypeIt is still producing the same results. PypeIt is still not processing the full height of the image.

![Screenshot from 2019-06-09 13-14-15](https://user-images.githubusercontent.com/37086221/59163640-81ee3b80-8ab8-11e9-914c-99713984f567.png)

This is the raw data for HD164595 (file r1033.fits). After running PypeIt, PypeIt produced the following 2D spectrum:

![Screenshot from 2019-06-09 13-11-18](https://user-images.githubusercontent.com/37086221/59163617-3045b100-8ab8-11e9-923c-68c813d254b5.png)
 
PypeIt is not reducing the entire image. I have attached a Google Drive link to the latest reduction folder. The data I used is the same as above.

https://drive.google.com/file/d/1gYBMFZ3x9KXzL8NQdq53k71iVN-UpPtY/view?usp=sharing

I hope you can help me resolve this issue. Thank you for your time.

**Comment by profxj** [comment]
Ok, reopening.  Can you give this a quick try on the `singleimage` branch
which is under review?  I suspect we are going to need a custom image
reader for Kast because everyone can do a custom windowing..

Thanks @rtlow

**Comment by rtlow** [comment]
Thanks for the swift response! I just tried the reduction under the singleimage branch. No luck. The same issue still persists.

Thank you for your time.

**Comment by profxj** [comment]
Ok, @rtlow 
I have started a `kast_reader` branch and I think this will work on your files
(indeed, I have run it on them).  Please give it a whirl.

**Comment by rtlow** [comment]
Thanks again for another swift response! I have just tried reducing using the kast_reader branch. The result has not changed on my system. Still the exact same issue.

Thank you for your time and effort.

**Comment by profxj** [comment]
@rtlow has stated that PypeIt is "not reducing the full image".  
I attach the 1D arc QA which shows ~2700 pixels were analyzed
in the spectral dimension (the images have 
NAXIS2  =                 2725 / NUMBER OF ROWS)

![Arc_1dfit_A_1_01_S0000](https://user-images.githubusercontent.com/3998093/59200063-43a25c00-8b4c-11e9-9d89-7b8b166bd51d.png)

And a screen shot of the 2D reduced image generated with `pypeit_show_2dspec`:

![rskysub](https://user-images.githubusercontent.com/3998093/59200187-8401da00-8b4c-11e9-96f4-e7872e174b0d.png)

At this stage, I suspect user error or lack of a full knowledge of
the PypeIt outputs.  @rtlow -- Please examine further on your own.

**Comment by rtlow** [comment]
Sorry for not getting back immediately. I am unsure where I am making an error. Would it be possible for you to send the .pypeit file you used to perform this reduction? I can assure you that I am using the kast_reader branch for PypeIt
![Screenshot from 2019-06-11 13-59-02](https://user-images.githubusercontent.com/37086221/59307018-720a5f00-8c52-11e9-9b4a-be6f7b34ac18.png)

I have made sure that all of PypeIt's dependencies are up to date. 
I have attached a Google drive link to the latest reduction attempt. The QA files, .pypeit file, and processed images are all contained there.

https://drive.google.com/file/d/1-JyYF9yDFcZD-jC51GE6a1ckpSim28vm/view?usp=sharing

Please take a look at the PypeIt outputs that I obtained. I'm pretty sure that I am not misinterpreting the PypeIt outputs. I hope you can help me resolve this issue.

Thank you for your time.

**Comment by profxj** [comment]
Odd that.  Does your QA PNG file for the Arc look the same as mine?
As for the PypeIt file, I am pasting my in:

----
# Auto-generated PypeIt file
# Sun 09 Jun 2019 18:51:17

# User-defined execution parameters
[rdx]
spectrograph = shane_kast_red

# Setup
setup read
 Setup A:
   --:
     dichroic: d57
     disperser: {angle: 11861.0, name: 600/7500}
     slit: {decker: 0.5 arcsec, slitlen: none, slitwid: none}
   '01': {binning: '1,1', det: 1, namp: 2}
setup end

# Read in the data
data read
 path ../1035
|   filename |       frametype |          ra |        dec |    target | dispname |     decker | binning |                mjd |        airmass | exptime | dichroic |
| r1001.fits |            bias | 13:32:12.53 | 37:25:58.4 |      Bias | 600/7500 | 2.0 arcsec |     1,1 | 57978.008904282404 |            1.0 |     0.0 |      d57 |
| r1002.fits |            bias | 13:32:57.95 | 37:25:57.9 |      Bias | 600/7500 | 2.0 arcsec |     1,1 | 57978.009446412034 |            1.0 |     0.0 |      d57 |
| r1003.fits |            bias | 13:33:28.31 | 37:25:57.6 |      Bias | 600/7500 | 2.0 arcsec |     1,1 |     57978.00978125 |            1.0 |     0.0 |      d57 |
| r1004.fits |            bias | 13:33:53.66 | 37:25:57.3 |      Bias | 600/7500 | 2.0 arcsec |     1,1 |  57978.01011643519 |            1.0 |     0.0 |      d57 |
| r1005.fits |            bias | 13:34:23.78 | 37:25:56.9 |      Bias | 600/7500 | 2.0 arcsec |     1,1 |  57978.01045162037 |            1.0 |     0.0 |      d57 |
| r1006.fits |            bias | 13:34:54.14 | 37:25:56.6 |      Bias | 600/7500 | 2.0 arcsec |     1,1 |  57978.01078657407 |            1.0 |     0.0 |      d57 |
| r1007.fits |            bias | 13:35:24.51 | 37:25:56.3 |      Bias | 600/7500 | 2.0 arcsec |     1,1 |  57978.01112152778 |            1.0 |     0.0 |      d57 |
| r1008.fits |            bias | 13:35:49.85 | 37:25:56.0 |      Bias | 600/7500 | 2.0 arcsec |     1,1 | 57978.011456597225 |            1.0 |     0.0 |      d57 |
| r1009.fits |            bias | 13:36:20.22 | 37:25:55.7 |      Bias | 600/7500 | 2.0 arcsec |     1,1 |  57978.01179143519 |            1.0 |     0.0 |      d57 |
| r1010.fits |            bias | 13:36:50.58 | 37:25:55.3 |      Bias | 600/7500 | 2.0 arcsec |     1,1 |  57978.01212650463 |            1.0 |     0.0 |      d57 |
| r1011.fits |            bias | 13:37:20.95 | 37:25:55.0 |      Bias | 600/7500 | 2.0 arcsec |     1,1 | 57978.012461805556 |            1.0 |     0.0 |      d57 |
| r1035.fits |         science | 16:55:17.51 | 62:24:44.9 | 1655+6224 | 600/7500 | 2.0 arcsec |     1,1 | 57978.170674189816 | 1.110000014305 |   150.0 |      d57 |
| r1061.fits |        standard | 23:19:58.41 | -5:09:56.0 |  Feige110 | 600/7500 | 2.0 arcsec |     1,1 |  57978.45125416667 | 1.370000004768 |   900.0 |      d57 |
| r1000.fits |        tilt,arc | 13:25:58.60 | 37:26:02.3 |      Arcs | 600/7500 | 0.5 arcsec |     1,1 | 57978.004601851855 |            1.0 |     3.0 |      d57 |
| r1012.fits | trace,pixelflat | 13:45:46.61 | 37:25:49.0 | Dome Flat | 600/7500 | 2.0 arcsec |     1,1 |  57978.01831099537 |            1.0 |     6.0 |      d57 |
| r1013.fits | trace,pixelflat | 13:46:21.99 | 37:25:48.6 | Dome Flat | 600/7500 | 2.0 arcsec |     1,1 |  57978.01871597222 |            1.0 |     6.0 |      d57 |
| r1014.fits | trace,pixelflat | 13:46:57.37 | 37:25:48.2 | Dome Flat | 600/7500 | 2.0 arcsec |     1,1 |  57978.01912106481 |            1.0 |     6.0 |      d57 |
| r1015.fits | trace,pixelflat | 13:47:32.76 | 37:25:47.8 | Dome Flat | 600/7500 | 2.0 arcsec |     1,1 | 57978.019527083336 |            1.0 |     6.0 |      d57 |
| r1016.fits | trace,pixelflat | 13:48:08.14 | 37:25:47.3 | Dome Flat | 600/7500 | 2.0 arcsec |     1,1 | 57978.019935185184 |            1.0 |     6.0 |      d57 |
| r1017.fits | trace,pixelflat | 13:48:43.52 | 37:25:46.9 | Dome Flat | 600/7500 | 2.0 arcsec |     1,1 |  57978.02034097222 |            1.0 |     6.0 |      d57 |
data end

**Comment by profxj** [comment]
fixed
