### ISSUE TITLE
manual extraction convention switched relative to PypeIt spec, spat convention

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#642]
Hi @profxj and @tiffanyhsyu, 

I'm looking at your slides look which great. 

One quick important question Your are documenting the manual stuff as being (spatial_pxiel, spectral_pixel) for both how it is explained in the presentation and also how it is written in the PypeIt file. The PypeIt convention is (spectral, spatial). Is this just not updated, or did you really code the manual options to be opposite to the PypeIt convention. That is bad. 

We agreed that we would adopt spectral, spatial everywhere and went to a lot of pain and a few generations of bugs and PRs to get that all organized. Can you please address this issue in the code/slides before these slides and go live?

Thanks!
Joe

**Comment by tiffanyhsyu** [comment]
Thanks for bringing this up Joe. This is my bad, but luckily it's just typo-ed in my notes and PypeIt does take in (spectral, spatial) pixel locations for the manual extraction. I've used it to reduce ~4 nights of NIRSPEC data too, so I think it's well-tested :)

I've updated my NIRSPEC How-To slides to reflect the (spectral, spatial) convention!
