### ISSUE TITLE
PypeIt fails if there are no science frames. This should not be the case

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#645]
Hi Folks, 

The PypeIt file below fails because there is no science or standard frame in the file list. I don't think this I the desired behavior. But perhaps there is no way simple way out here given the way the code is written.  The point is that I don't know what the calib IDs are yet but I would like to get started on the reductions to check that my calibrations were taken correctly. This is not an uncommon thing that someone might want to do at an observatory, i.e. I'm weathered out but took calibrations and want to check if they work with the pipeline. 

Is there a workaround you can think of here? Note that if I set the calib group to 0 instead of 'all' it does not crash, but then also does not run. Maybe we can add some logic to pypeit.py that basically just tries to loop over calib groups and create calibrations even if there are no science frames. 

# User-defined execution parameters
[rdx]
    spectrograph = keck_nires

# Setup
setup read
 Setup A
setup end

# Read in the data
data read
 path /Users/joe/RAW_DATA/NIRES_Mar19/2019mar15/
|          filename |       frametype |     ra |   dec | target | dispname |  decker | binning |              mjd |          airmass | exptime | calib | comb_id | bkg_id |
| s190315_0019.fits | pixelflat,trace |   58.0 |  45.0 |   flat |     spec | default |     1,1 | 58557.0742587919 | 1.41291034446565 |   100.0 |  all  |      -1 |     -1 |
| s190315_0021.fits | pixelflat,trace |   58.0 |  45.0 |   flat |     spec | default |     1,1 | 58557.0770035836 | 1.41291034446565 |   100.0 |  all  |      -1 |     -1 |
| s190315_0023.fits | pixelflat,trace |   58.0 |  45.0 |   flat |     spec | default |     1,1 | 58557.0797365697 | 1.41291034446565 |   100.0 |  all  |      -1 |     -1 |
| s190315_0025.fits | pixelflat,trace |   58.0 |  45.0 |   flat |     spec | default |     1,1 | 58557.0824695558 | 1.41291034446565 |   100.0 |  all  |      -1 |     -1 |
data end

Traceback (most recent call last):
  File "/Users/joe/anaconda3/bin//run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/joe/python/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/Users/joe/python/PypeIt/pypeit/scripts/run_pypeit.py", line 86, in main
    logname=logname, show=args.show)
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 112, in __init__
    self.fitstbl.finalize_usr_build(frametype, setups[0])
  File "/Users/joe/python/PypeIt/pypeit/metadata.py", line 541, in finalize_usr_build
    self.set_calibration_groups(default=True)
  File "/Users/joe/python/PypeIt/pypeit/metadata.py", line 1045, in set_calibration_groups
    self._set_calib_group_bits()
  File "/Users/joe/python/PypeIt/pypeit/metadata.py", line 976, in _set_calib_group_bits
    self['calibbit'][i] = self.calib_bitmask.turn_on(self['calibbit'][i], grp)
  File "/Users/joe/python/PypeIt/pypeit/bitmask.py", line 310, in turn_on
    out = value | (1 << self.bits[_flag[0]])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by profxj** [comment]
dealt with
