### ISSUE TITLE
remove XSpectrum1d dependencies in core methods?

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#646]
PypeIt has a coding policy that there are no depedendencies on objects in core and utility methods. This is violated occasionally in very special cases (specobjs for example). We need to discuss whether XSpectrum1d constitutes one of these exceptions. 

In my opinion, there is little gain from having this dependency and lots of harm and I'd like to see it removed from all core routines, and only used in the plotting scripts, i.e. pypeit_show_1dspec. 

I'm happy to discuss this though. 

Joe

**Comment by profxj** [comment]
removed
