### ISSUE TITLE
Python setup.py test  inside Pypelt

### ISSUE THREAD

**Issue by ASOAM** [pypeit/PypeIt#653]
**running setup.py is broken using "python setup.py test" but it is working when installed pysets and run tests inside pypeit.**
linetools could not be installed using 'pip'. Linetools were installed using git.
The errors are shown below.

> python setup.py test
> /Users/asoam/miniconda2/envs/py36/lib/python3.6/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '0.9.4dev' to '0.9.4.dev0'
>   normalized_version,
> running pytest
> running egg_info
> writing pypeit.egg-info/PKG-INFO
> writing dependency_links to pypeit.egg-info/dependency_links.txt
> writing top-level names to pypeit.egg-info/top_level.txt
> reading manifest file 'pypeit.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching '*.c' under directory '*.pyx'
> warning: no files found matching '*.pxd' under directory '*.pyx'
> warning: no files found matching '*' under directory 'docs'
> warning: no files found matching '*' under directory 'cextern'
> warning: no files found matching '*' under directory 'scripts'
> no previously-included directories found matching 'build'
> no previously-included directories found matching 'docs/_build'
> no previously-included directories found matching 'docs/api'
> warning: no previously-included files matching '*.pyc' found anywhere in distribution
> warning: no previously-included files matching '*.o' found anywhere in distribution
> writing manifest file 'pypeit.egg-info/SOURCES.txt'
> running build_ext
> =============================================================== test session starts ===============================================================
> platform darwin -- Python 3.6.8, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
> rootdir: /Users/asoam/Desktop/PypeIt-master, inifile:
> plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.3.0, arraydiff-0.3
> collecting ... WARNING: AstropyDeprecationWarning: The module `astropy.tests.pytest_plugins has been deprecated. The variables `PYTEST_HEADER_MODULES` and `TESTED_VERSIONS`should now be imported from `astropy.tests.plugins.display`. The function `enable_deprecations_as_exceptions` should be imported from `astropy.tests.helper` [astropy.tests.pytest_plugins]
> collected 414 items / 5 errors / 409 selected                                                                                                     
> 
> ===================================================================== ERRORS ======================================================================
> ____________________ ERROR collecting linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_autodoc_enhancements.py _____________________
> ImportError while importing test module '/Users/asoam/Desktop/PypeIt-master/linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_autodoc_enhancements.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/__init__.py:3: in <module>
>     from .numpydoc import setup
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/numpydoc.py:29: in <module>
>     from sphinx.util.compat import Directive
> E   ImportError: cannot import name 'Directive'
> _________________________ ERROR collecting linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_automodapi.py __________________________
> ImportError while importing test module '/Users/asoam/Desktop/PypeIt-master/linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_automodapi.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/__init__.py:3: in <module>
>     from .numpydoc import setup
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/numpydoc.py:29: in <module>
>     from sphinx.util.compat import Directive
> E   ImportError: cannot import name 'Directive'
> _________________________ ERROR collecting linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_automodsumm.py _________________________
> ImportError while importing test module '/Users/asoam/Desktop/PypeIt-master/linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_automodsumm.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/__init__.py:3: in <module>
>     from .numpydoc import setup
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/numpydoc.py:29: in <module>
>     from sphinx.util.compat import Directive
> E   ImportError: cannot import name 'Directive'
> __________________________ ERROR collecting linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_docscrape.py __________________________
> ImportError while importing test module '/Users/asoam/Desktop/PypeIt-master/linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_docscrape.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/__init__.py:3: in <module>
>     from .numpydoc import setup
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/numpydoc.py:29: in <module>
>     from sphinx.util.compat import Directive
> E   ImportError: cannot import name 'Directive'
> ____________________________ ERROR collecting linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_utils.py ____________________________
> ImportError while importing test module '/Users/asoam/Desktop/PypeIt-master/linetools/astropy_helpers/astropy_helpers/sphinx/ext/tests/test_utils.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/__init__.py:3: in <module>
>     from .numpydoc import setup
> linetools/astropy_helpers/astropy_helpers/sphinx/ext/numpydoc.py:29: in <module>
>     from sphinx.util.compat import Directive
> E   ImportError: cannot import name 'Directive'
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ============================================================= 5 error in 4.19 seconds =============================================================

**Comment by profxj** [comment]
I doubt this is a problem anymore
