### ISSUE TITLE
LRIS multi-slit data reduction 

### ISSUE THREAD

**Issue by marijana777** [pypeit/PypeIt#655]
I've run into an error with reducing LRIS red data.  The error happens during flexure correction.  Here are my pypeit configuration parameters.

# User-defined execution parameters
[rdx]
spectrograph = keck_lris_red
[calibrations]
[[biasframe]]
number = 2
[[pixelflatframe]]
number = 3
[[arcframe]]
number = 1
[[pinholeframe]]
number = 0
[[traceframe]]
number = 3
[[standardframe]]
number = 1
[[tilts]]
tracethresh = 10.0
[[slits]]
rm_slits = 1:1000:238 

And here is the full Traceback:

Traceback (most recent call last):
  File "/home/smailagic/anaconda3/bin/run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/smailagic/PYPIT/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/home/smailagic/PYPIT/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/home/smailagic/PYPIT/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/home/smailagic/PYPIT/pypeit/pypeit.py", line 358, in reduce_exposure
    = self.extract_one(self.frames, self.det, bg_frames = self.bg_frames, std_outfile = std_outfile)
  File "/home/smailagic/PYPIT/pypeit/pypeit.py", line 585, in extract_one
    self.redux.flexure_correct(self.sobjs, self.basename)
  File "/home/smailagic/PYPIT/pypeit/reduce.py", line 357, in flexure_correct
    wave.flexure_qa(sobjs, self.maskslits, basename, self.det, flex_list,out_dir=self.par['rdx']['redux_path'])
  File "/home/smailagic/PYPIT/pypeit/core/wave.py", line 650, in flexure_qa
    fit = this_flex_dict['polyfit'][iobj]
IndexError: list index out of range

The error does not appear when we set parameter  
[flexure]
    method = skip
The reason for the error could be that in the code 
/pypeit/core/wave.py in 
def flexure_obj(specobjs, maskslits, method, sky_file, mxshft=None)
specobjs and the output of the flexure_obj do not have the same number of elements. 
This could happen if not all slits have objects unique / well identified.

**Comment by marusa** [comment]
We have the same issue. Most of our slits have no objects in them, especially in the individual frames.

**Comment by jhennawi** [comment]
Hi All, 

I recommend running with flexure method = skip for now. @profxj can you look into this? This method has been a buggy thorn in my side for a while now. 

Joe

**Comment by profxj** [comment]
Someone needs to provide a *small* dataset where the bug occurs
for me to debug it.

**Comment by marijana777** [comment]
I found that pypeit/core/wave.py case in def flexure_obj in the line 321 (msgs.warn("No previous good solution.  Punting on this object") ) does not define fdict, which would lead to a different number of objects in flex_dict['polyfit'] and in this_specobjs. 
This would further give different number of objects in def flexure_qa in this_flex_dict and in this_specobjs, and give the error described in the issue.                             
The case in  def flexure_obj in the line 321 in my case happened because sky spectrum contained large negative values in flux in some pixels.

**Comment by marijana777** [comment]
I would propose defining fdict as in the next good solution (in  def flexure_obj before the line 321 ), for this case, and adding pdb trace if there are no any good solutions, if that sounds reasonable

**Comment by marijana777** [comment]
@profxj ,  @marusa  and @jhennawi  here is my branch : https://github.com/marijana777/PYPIT/tree/mslts . For my data, this works and I am not getting the issue any more. @marusa  and @jhennawi , @profxj  is also working on it, and I think he will push new changes to PypeIt, so you could either use my changes , or wait for the final version from @profxj  .

**Comment by profxj** [comment]
Thanks @marijana777 -- Am going to implement something like this
in the `lris_gratings` branch.  Stay tuned.

**Comment by profxj** [comment]
@marijana777 -- can you test that the edits to the `lris_gratings` branch
work for you?  Now PR #672

**Comment by marijana777** [comment]
@profxj just responded in https://github.com/pypeit/PypeIt/pull/672
