### ISSUE TITLE
calib, comb_id, and bkg_id column definitions in NIRES .pypeit file?

### ISSUE THREAD

**Issue by wrensuess** [pypeit/PypeIt#659]
Hey all,

I'm working on reducing some NIRES data with PypeIt. Is there a good place to look for documentation on the "calib," "comb_id," and "bkg_id" columns in the .pypeit file? Right now, my PypeIt run is crashing during the wavelength calibration, and I suspect it's because my .pypeit file isn't set up correctly (the auto-generated "calib" column is all 0, and the "comb_id" and "bkg_id" columns are all -1, which doesn't seem right...).

Thanks so much!
- Wren Suess

**Comment by jhennawi** [comment]
Hi Wren, 

I suggest looking at the Pypeit-Development-Suite. 

https://github.com/pypeit/PypeIt-development-suite

There are examples of NIRES pypeit files there. The documentation on the calib and comb_ids are still under construction. If you took your data as ABBA, you can find relevant example pypeit files in the dev-suite pypeit_files directory, i.e. 

https://github.com/pypeit/PypeIt-development-suite/blob/master/pypeit_files/keck_nires_nires.pypeit

Also, there is a how two which @tiffanyhsyu put together on these. @tiffanyhsyu can you send that to Wren. 

Thanks and good luck!
Joe

**Comment by tiffanyhsyu** [comment]
Hi Wren,

Here's [a link](https://docs.google.com/presentation/d/1jOgwOBP9OhlhHxMTqxuc2dsBZ86PTxjje1kJ1FnSVs4/edit?usp=sharing) to some slides on how I used the comb_id and bkg_id for reducing NIRSPEC data. The idea in using those columns should be the same.

-Tiffany

**Comment by wrensuess** [comment]
Hi Joe & Tiffany,

Thanks so much for the very quick replies! Tiffany's slides are very helpful for setting up ABBA reduction (which I used for my telluric standards).

For my science frames, I used an ABC dither pattern (0", +5", -5") and was intending on doing background subtraction using the average of the surrounding two frames (ie, a B frame is background-subtracted using the average of the A frame before it and the C frame after it; a C frame is background-subtracted using the average of the B frame before it and the A frame after it). Any chance the ABC dither pattern has been implemented in PypeIt? If so, what would be the right syntax to use in bkg_id?

Thanks!
Wren

**Comment by tiffanyhsyu** [comment]
Hi Wren,

I believe we considered an ABCDE dither pattern, using an average of BCDE as the sky frame for A, but I haven't tested this. My feeling is that you'll have to reduce your A, B, and C science frames separately, i.e., do run_pypeit 3 times, once to reduce each science frame, and changing the .pypeit file each time to specify the desired background frames for science frame. Does doing:
```
filename    frame_type    comb_id    bkg_id
A                arc,science         1                2
B                                            2
C                                            2 
```
Work for you? I'm not sure if PypeIt will take the empty frame_type and bkg_id for B, C. If not, I think you'd have to do:
```
filename    frame_type    comb_id    bkg_id
A                arc,science         1                2
B                   science            2                1
C                   science            2                1
```
But the reduced 2d, 1d outputs for files B, C would be trashed in this run. That's my first thought, but it's possible there's something more elegant and less tedious!

-Tiffany

**Comment by wrensuess** [comment]
Thanks, Tiffany! And the formatting totally worked out :)

Is there a way to disable the part of the pipeline that does background subtraction, and just feed PypeIt pre-background-subtracted frames? What I'd really like to do is to use the average of just the frame *right* before and *right* after a given frame to do the background subtraction (since the near-IR sky is so variable). It seems like that would be a bit difficult to set up using this scheme, since I would have so many bkg_id's to keep track of. But it would be pretty simple for me to just background-subtract the frames myself before running PypeIt!

-wren

**Comment by tiffanyhsyu** [comment]
Hi Wren,

I'm not super sure about this, but I feel like it would require you dig into the code a bit to get that to work, which might be more difficult than setting up your .pypeit files using the above scheme.

I imagine if you want to feed in already background-subtracted frames, you can just ignore the comb_ID and bkg_ID columns/not set it up at all. However, for NIR reductions, I use the sky lines in my science frame for wavelength calibration, and feeding in a background-subtracted frame would mean most of the sky is subtracted out, so you'd need an arc lamp. Currently, I believe it's hard coded in PypeIt for Keck NIRES to read in an OH (sky) line list for wavelength calibration, and I don't know that we have a NIR arc lamp line list working.

That's the biggest problem I can think of. I also assume you'd want to turn off bias subtraction if you're background-subtracting your science frames in advance, but I think if you turn off bias subtraction in PypeIt, it also won't bias subtract your flats or arc lamp.

@jhennawi, @kbwestfall, @profxj -- do you guys have a say on this?

-Tiffany

**Comment by jhennawi** [comment]
Hi Wren, 

We have thought a lot about the background subtraction for NIRES. Any game you are going to play is going to be inferior to what we are doing. Trust us. My suggestion is that you simply try to run with differenced frames and inspect the results. I'm sure you will be happy with them. Any frames will work as long as they are not at the same location, and even if they sky varied. 

The point is PypeIt is doing difference imaging and then fitting a model to the residuals. So the fact that they sky varies is not such a big issue. We model and take that out. The main reason why we difference is because there are detector artifacts, systematics, and illumination effects that cannot be fully modeled. 

Anyway, if you want to access the development suite to run on a canned data that allows you to inspect sky subtracted frames, we can give you access.
