### ISSUE TITLE
Add LRISr gratings

### ISSUE THREAD

**Issue by tiffanyhsyu** [pypeit/PypeIt#660]
I need the following Keck+LRISr gratings added:

600/10000
600/7500
900/5500

Happy to add them myself (although @profxj said at the March 21 PypeIt workshop that it's more involved than it used to be and I don't know what's needed) or help with adding them

**Comment by jhennawi** [comment]
I would coordinate with @profxj but the solutions are in xidl.

**Comment by profxj** [comment]
The 600/7500 is in the DevSuite and runs masterfully (longslit).

Do you have mask data now?

Anyways, my preference is to use the outputs from PypeIt 
with Holy Grail.  So I will need multi-slit examples for each
of these gratings.

The fall back is the XIDL files which I should prefer to avoid.

**Comment by profxj** [comment]
ps.  Am going to try my own 600/7500 multi-slit data now.

**Comment by profxj** [comment]
sorry,  I am wrong.  Am working on 400/8500 data.

So I need some masks with 600/7500 too.

**Comment by tiffanyhsyu** [comment]
Update:
- 600/7500 grating does work for long slit already, as X mentioned
- 600/10000 grating works; may need to have more lines identified at higher wavelengths
- 900/5500 grating works
