### ISSUE TITLE
Need a blue solution for the DEIMOS 1200B grating

### ISSUE THREAD

**Issue by percygomez** [pypeit/PypeIt#662]
I am unable to reduce the blue side of MOS data when using the 1200B grating (centered at 5200). Pypeit is able to reduce the red chips but fails on the blue chips. The arcs are heavily contaminated by internal reflections which might also make the matching more complicated. I only use the KrXe arcs.

**Comment by profxj** [comment]
Indeed, this is new.  Do you have a previous solution?
Will make life much easier if you do.

And is only using KrXe arcs the 'standard' approach.
I would generally recommend all arcs with any instrument.

Last, we should develop a recommended DEIMOS calibrations
page like:

https://github.com/pypeit/PypeIt/blob/master/doc/lris.rst

**Comment by jhennawi** [comment]
Hi @percygomez and @profxj, 

Were 'blue arcs' taken as described here: 

https://www2.keck.hawaii.edu/inst/deimos/calib_blue.html

or was something non-standard done? I'm pretty sure the solutions we have are from "Blue arcs", but I'm not actually sure what @profxj ingested here. 

Joe

**Comment by profxj** [comment]
addressed
