### ISSUE TITLE
Consider using the sacred package to control/record PypeIt running

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#667]
https://sacred.readthedocs.io/en/latest/experiment.html

Would add a new dependency.

**Comment by profxj** [comment]
There’s an introduction to Sacred on YouTube by the creator: https://www.youtube.com/watch?v=qqg7RO0o1OE

**Comment by jhennawi** [comment]
Looks quite interesting for running and log files, and capturing standard. For the config stuff, I'm not seeing that this would be easy to implement. 

I also think we have more pressing problems to sort out. But if you think this is quick implementation that doesn't modify much code, and nevertheless makes running much easier, I'm fine with it being implemented.

**Comment by profxj** [comment]
closing
