### ISSUE TITLE
install doc update for linetools

### ISSUE THREAD

**Issue by astronomeara** [pypeit/PypeIt#671]
current install directions tell you how to grab X's ginga, but do not give the link for where to clone linetools.  Recommend including for the dullards like me who would try to grab it from github.com/profxj/linetools instead of github.com/linetools/linetools (the former *does* download something!

**Comment by profxj** [comment]
The docs do include the direct link to the code
(as a hyperlink).

What else can we do to help said dullard?

**Comment by jhennawi** [comment]
One quick point on this @profxj. Can we convince the ejeschke to put your two line change to ginga into the official ginga. I find it annoying that we have to maintain our own ginga fork. I think you asked them this in the past, and they said no, but maybe they would reconsider given all the ginga users we will be feeding them. 

Alternatively, we could write a PypeIt plugin using their plugin model. That is not so easy to figure out, but maybe we can get one of your undergrads on it. 

Joe

**Comment by profxj** [comment]
Your comment is entirely unrelated @jhennawi .

Raise that as a separate Issue if you wish.

**Comment by astronomeara** [comment]
Sure.  The dullard notes that in 
conda list "^python$|numpy|astropy$|scipy$|matplotlib|numba|PyQT|ginga|yaml|h5py"

configobj is not included in the list

**Comment by astronomeara** [comment]
The dullard reports that it's not possible to run the test suite after pip install

**Comment by profxj** [comment]
Addressed by #672
