### ISSUE TITLE
Tilted slits

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#677]
I am seeing that a fair number of our user community tilt their 
slits with LRIS and DEIMOS.

I suspect this is going to raise issues that we haven't anticipated.

This is more of a head's up, but people should add on to this thread
what they think might 'break'.

e.g.  we saw one of the more extreme slits fail on wavelengths.
Am not sure the tilted slit was the issue, but quite possible.

**Comment by profxj** [comment]
I have uploaded a DEIMOS tilted test suite, called `600ZD_tilted`

**Comment by jhennawi** [comment]
The code handles tilted slits fine. The only issue is that our extraction along one
of the rectilinear axes requires more thought if you tilt the slit. Basically if the sit is very tilted the extraction is degrading the resolution.

**Comment by profxj** [comment]
closing
