### ISSUE TITLE
Not ready for VLT X-Shooter NIR with the K-band blocking filter

### ISSUE THREAD

**Issue by freddavies** [pypeit/PypeIt#684]
When the K-band blocking filter is included, the NIR arm of X-Shooter effectively has 14 instead of 16 orders, which breaks the reduction in several places that have the number of orders hardcoded in.

One possible solution would be to add a new X-Shooter setup, NIR_JH perhaps, which is fixed to the 14 shorter wavelength orders. Another potential solution would be to remove the hardcoded order number altogether and work with the IDs from the arxiv cross-matching, but that might require more effort.

**Comment by profxj** [comment]
I might add that I am modifying the way the `slit2order` and `slit_minmax` methods work
for MagE and will work under the assumption that if *fewer* orders are recovered than 
expected that one has recovered all the red ones.

Looks like this is opposite to your K-band blocking issue.  But you might modify things accordingly.

**Comment by profxj** [comment]
Actually, scratch that.

I am going to insist that one label the orders during wavelength `reidentification`.
This will eliminate `slit2order` and will require `slit_minmax` to work on true 
order number instead of "slit".

**Comment by profxj** [comment]
heads up @jhennawi

**Comment by profxj** [comment]
@freddavies -- See if PR #695 handles this fine.
I think it should.

**Comment by freddavies** [comment]
@profxj I can confirm that it works now. Thanks! Closing...
