### ISSUE TITLE
MOSFIRE Persistence 

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#693]
Consider building the framework to mask the pixels
affected by persistence from alignment using the mask
design (ideally) or some image differencing (not as ideal).

**Comment by jhennawi** [comment]
Can you attach an example image. My guess is that you need to difference.

**Comment by jhennawi** [comment]
I have thus far not seen any Hawaii-II data that does not look better when differenced compared to modeling the entire sky directly.

**Comment by profxj** [comment]
closing
