### ISSUE TITLE
GMOS binning issue

### ISSUE THREAD

**Issue by feigewang** [pypeit/PypeIt#696]
The GMOS reader reads in the binned data, but it seems that the processimages will trim the data again based on the binning. Thus, I can only got half of the data reduced without any breaks. Please see line 554-555 in processimages.py and line 384-390 in spectrograph.py

I also tried to reduce the LRIS binned data which seems working fine. So, I'm not quite sure whether this issue comes from processimages.py or from gemini_gmos.py. It's not easy for me to debug the processimages, it would be great if @kbwestfall and/or @profxj could take a look at this.

**Comment by jhennawi** [comment]
Hi @kbwestfall your last changes to binning and the dataset parsing broke GMOS. Could you please help @feigewang with GMOS. It was working correctly before. 

@profxj and @kbwestfall, see the process images Slack channel for more discussion.

**Comment by profxj** [comment]
Binning was ignored in the data reader. 
I don't see how this ever worked successfully (as claimed).

Anyhow, I think this is fixed in the `gmos_wavecen` branch.
I encourage @feigewang to test.

**Comment by feigewang** [comment]
Thanks @profxj. I will check it out.

**Comment by profxj** [comment]
I believe this is addressed by PR #739
