### ISSUE TITLE
We need a .log pypeit_setup file

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#699]
The .sorted file tries to sort setups. This is valuable, but often a user just wants a straight log file with all the meta information. My suggestion is that we also dump the fitstable in the same format as .sorted as just a chronological list of images with no attempt to be clever and divide them into setups. When there are 5 different setups like for a multislit spectograph, the .sorted file is just a morass of information that is unpleasant to look out.

**Comment by profxj** [comment]
The .sorted file is no more
