### ISSUE TITLE
Create a Anaconda cloud for PypeIt

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#708]
As they do for MOSFIRE

https://docs.anaconda.com/anaconda-cloud/

**Comment by profxj** [comment]
Or this?

https://conda.github.io/conda-pack/

**Comment by bpholden** [comment]
Part of the way to get there is to make a environment.yml file which will provide a list of requirements and build a new conda environment. 

% conda env create -f environment.yml

The file looks like:
name: pypeit
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - astropy
  - scipy
  - matplotlib
  - numba
  - pyqt
  - yaml
  - pyyaml
  - configobj
  - scikit-learn
  - ipython
  - requests
  - packaging
  - pytest

**Comment by bpholden** [comment]
Should this be a new branch? or should I add to dev?

**Comment by kbwestfall** [comment]
Yeah, I would branch off of `develop` and add the yml file.

BTW, there's this text from the installation docs:

```
If you are using Anaconda, you can check the presence of these packages with::

	conda list "^python$|numpy|astropy$|scipy$|matplotlib|numba|PyQT|ginga|pyyaml|h5py"

If the packages have been installed, this command should print out all the packages and their version numbers.
```

This is out-of-date.  Instead of adding in the missing packages, is something like this also made easier by using the yml file?

**Comment by bpholden** [comment]
The yaml file with the above command makes a conda environment. So you can do a conda upgrade in that environment. 

I am not sure about updating the requirements, though. I should probably read the documentation?

**Comment by kbwestfall** [comment]
I just checked the `conda list` docs, and it doesn't seem like there's a way around having to list all of the packages in the regular expression.  I don't know regular expressions and I don't use conda, so I don't know how to edit that recommendation.  Leaving it for now.

**Comment by finagle29** [comment]
Could a package hosted on [conda-forge](conda-forge.org) address this issue? I'm willing to take a stab at making a recipe and trying to add it to conda-forge.

**Comment by finagle29** [comment]
PypeIt is now installable via conda! https://anaconda.org/conda-forge/pypeit https://github.com/conda-forge/pypeit-feedstock
``conda install -c conda-forge pypeit``
