### ISSUE TITLE
What is still missing in image proc-ing. 

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#719]
There are two problems with our current image processing that were not addressed properly: 

1) We currently have instrument specific readers that overload "load_raw_frame". I think this is the wrong approach. Instrument specific processing go beyond just reading in the frame, but extend to the entire image processing itself. For this reason, I very much dislike the corner we are boxed into in PypeIt ProcessRawImage. Here are few examples: 

-- Some instruments require processing the overscan in different ways. For some instruments a simple median might be okay. For others, you need to fit as a function of one dimension. 

--- Instruments like ESI have a big hot spot that varies, and cannot be simply dealth with according to a BPM. In principle one needs to fit the masked region image by image. I believe this is what we did in xidl. 

-- For this reason, I think the code that processes the images should be instrument specific. In other words, it should be possible to use the generic reader in spectrograph or wherever when that works, but then a user should be able to overload the entire proc-ing process. 

2) We are constantly reading and re-reading the same files, which massively slows down the code for big images particularly when the are gzipped. Each image should be read in only once.

**Comment by profxj** [comment]
Addressed
