### ISSUE TITLE
No way for user to associate Master files with the frame that create them

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#722]
We currently only identify our Master frames with an integer which is related to bits indicating which calib_ids are being used. This means there is no way for a user to associate what is in the PypeIt file with what gets written out to disk.  For situations (like the near-IR) where every image has its own arc, etc. this, or any situation where multiple setups are used, this is a big annoyance.   

My suggestion is that we append the raw filename used to the master filename. This will make for some long filenames, but we already have long filenames in the 1d and 2d output files (which I implemented for exactly this reason). A question remains as to what to do with masters derived from other masters that were not created from a file (e.g. wave_calib). My suggestion is that upon parsing the PypeIt file we create a dict that holds the bit key of the masters, and also its real-world filename. 

Another approach would be to somehow relate this to the calib-ids in the PypeIt file. I'm fine with at, although would prefer to have the filename in the master filename.

**Comment by profxj** [comment]
Superseded by #1022
