### ISSUE TITLE
Guidelines to implement a new instrument

### ISSUE THREAD

**Issue by jpsub** [pypeit/PypeIt#728]
First of all, thank you for a very nice package that streamlines spectroscopic data reductions (I'm currently using it to reduce Lick Shane 3-m Kast data).  We also have another visible+near-IR spectrograph (visitor instrument) that is used on the Shane 3-m and I was wondering if there exists instructional guidelines for implementing a new instrument.  While generating a new spectrograph class module is straightforward, I expect there are other places where changes are required.  Thanks again!

John

**Comment by jhennawi** [comment]
Hi John, 

My suggestion would be that you join the PypeIt developer Slack channel. At the moment, only core developers have added new spectrographs but I suspect that it would not be very difficult if you were to ask us questions on Slack when you have them. If you write me an e-mail, I'll add you the Slack. 

Joe

**Comment by jpsub** [comment]
Hi Joe,

Thank you for the prompt response.  Yes, please add me to the Slack channel
and we'll proceed from there.

Thanks again,
John

**Comment by jhennawi** [comment]
Send me a private e-mail message with your e-mail and I will do so.
