### ISSUE TITLE
Image processing still needs work. Top level is now good, but methods do many things wrong. 

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#740]
ProcessRawImage, and CalibrationImage need to have the following changes made: 

-- No images should ever be returned in ADU, everything should be in counts. This requires that we deal with nonlinear_counts everywhere taking into account the gain. Many routines require a noise model (like cr-masking) and this cannot be accommodated with images in ADU. The saturation value should in counts should just be an attribute of the image object. 

-- Dark current is not being added to the noise budget. 

-- We have no ability to deal with dark frames. 

-- combine.comb_frames is doing lots of silly things, like improperly masking pixels and setting masked pixels to mask values. This routine should be scrapped and rewritten from scratch. 

--  The image ProcessRawImage or CalibrationImage needs to return, an image in counts, a noise model (ivar), and a good pixel mask (inmask) or a bad pixel mask. 

-- CR masking needs to be an option for CalibrationImage. It needs to properly build a mask, and then propagate this mask into the combine. None of this is currently being done. 

-- Another option would be to use the ScienceImage class for calibration frames where we need these things. Ideally we would just get rid of the combine method that is in the calibration frames and use the one in science image, which takes masking into account. In that limit, CalibrationImage and ScienceImage could be merged.

**Comment by profxj** [comment]
"all wrong" is insulting.

**Comment by jhennawi** [comment]
Sorry I changed it to "many things wrong" but didn't hit save.

**Comment by profxj** [comment]
Many of the items raise here would have major knock on implications, 
e.g. challenges in addressing saturation.  Both in images and in 'spectra'
derived from the images.

And, we'd have to rethink entirely what we saved as Masters
and what we carry around in `Calibrations` and other classes.

I see no clean path forward to implementing most of these at
the present time.

**Comment by jhennawi** [comment]
I agree that it is work, but what we are currently doing is incorrect and inconsistent. I just fixed a bug where the flat field images were being gain multiplied, but the code was assuming they were not, causing a bunch of crashes in flat fielding. What I've done is put in kludges to undo the silly things that combine frames does. 

You seem to be implying that these issues are minor, but they are major:  we really can't deal with near-IR data without dark frames, and I don't see how a self-respecting astronomer can ignore dark current in the noise model (especially in the NIR where the dark current is large). 

The clean path forward is to completely refactor the image processing to address these shortcomings. You are instead focused on making incremental changes to a code architecture which is flawed, sloppily written and poorly documented (here I'm referring to the core image processing routines that you are calling like  combine.comb_frames), and ultimately performing incorrect operations on the data.  Whereas I think a complete refactor would actually be the faster and more efficient path forward which would also produce better code.

Joe

**Comment by profxj** [comment]
Addressed
