### ISSUE TITLE
ginga fork breaks image registration

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#744]
Hi All, 

The ginga fork @profxj which adds the WCS wavelength option breaks the WCS registration of images that we need for viewing multiple images show2dspec. The addition of wavelength to WCS is very helpful, but is admittedly a hack. What we really need is a ginga plugin for this, so that the WCS registration functionality is there. 

If you want to see the problem, run pypeit_show_2dspec using @profxj fork of ginga and try to click around. The images don't stay aligned, whereas in ejeschke's version they do. 

Joe

**Comment by profxj** [comment]
fork is deprecated
