### ISSUE TITLE
PypeIt sensitivity functions

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#747]
Hi All, 

I'm running into a small conceptual issue with regards to sensitivity functions. I've always defined these as [erg/s/cm^2/A]/counts, and in PypeIt we evaluate this with a polynomial fit as a function of wavelength. This is not binning dependent, i.e. if you change the binning by 2 you change the value of this function by two. Normally one always takes standards with the same binning and never has to worry about this. One option is to track the binning. 

I think the sensitivity function ought  to actually be defined [erg/s/cm^2/A]/[counts/A]. That requires determining the size of each wavelength bin which is easy enough. If we did that then we always have a binning dependent quantity. This also seems physically more correct to me. 

Thoughts?

**Comment by profxj** [comment]
I would have thought we had done it this way, so I am definitely in favor.

**Comment by jhennawi** [comment]
Fixed by PR #1071
