### ISSUE TITLE
Bias and overscan subtraction

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#75]
Consider developing a combined method that uses both bias images
and the overscan region.

**Comment by rcooke-ast** [comment]
This should be straightforward with the new parser...

**Comment by profxj** [comment]
On a related note, I think the overscan subtraction should be on the
ampsec not the datasec.  That is, I believe it will be more common for
the overscan region (e.g. in the header) to be defined across the entire detector.

Am implementing this now..

**Comment by rcooke-ast** [comment]
The settings keword for amplifier 1 `det01 oscansec01 []` and for amplifier
2 `det01 oscansec02 []` should take this into consideration. Are you
talking about a fix to the hardcoded LRIS code?

**Comment by profxj** [comment]
It is my expectation (with little evidence) that instruments that write these
sections to the header will have the overscan region include the
entire ampsec.   Seems to me they should (i.e. each row does get an overscan
whether or not that row is useful).

That is how the oscansec is defined for LRIS but it doesn't have to be if 
we choose to go with datasec.

**Comment by profxj** [comment]
Addressed by PR #700
