### ISSUE TITLE
(working on develop branch) 2D coadd failing with qhull error

### ISSUE THREAD

**Issue by csnap001** [pypeit/PypeIt#764]
I'm working with LRIS data with 560 dichroic, 400/3400 grism. I'm including the pypeit and coadd2d files, the raw data is too large to add here so let me know where to provide it if you would like to use it. 
The error occurs when I try to run pypeit_coadd_2dspec on the 2d data set output from running run_pypeit on the pypeit file (it was actually multiple runs on groups of science frames from the provided pypeit file). This is the error that is output:
scipy.spatial.qhull.QhullError: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4)

I can provide the full traceback as well if necessary.
[keck_lris_blue_A.pypeit.zip](https://github.com/pypeit/PypeIt/files/3633317/keck_lris_blue_A.pypeit.zip)
[test.coadd2d.zip](https://github.com/pypeit/PypeIt/files/3633319/test.coadd2d.zip)

**Comment by jhennawi** [comment]
Can we close this issue Chris?

**Comment by csnap001** [comment]
Yes, I'll close it now
