### ISSUE TITLE
Ginga can't open 2d spectra

### ISSUE THREAD

**Issue by lfinnert** [pypeit/PypeIt#767]
I installed pypeit after the Keck science meeting and am trying it on some of our NIRES data.  The reduction seems to run, but when I try to run pypeit_view_fits on the 2d spec it raises an attribute error:
File "~/anaconda3/lib/python3.7/site-packages/pypeit/ginga.py", line 132, in show_image
    header['NAXIS1'] = img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

pypeit_show_spec2d also gives an error:
xmlrpc.client.Fault: <Fault 1: "<class 'ginga.GingaPlugin.PluginError'>:Error creating image data for 'sciimg-det01': list index out of range">

I set up and ran my .pypeit files based on the cookbook.  I cloned ginga from the repo on the installation guide, and it seems to work fine otherwise.  I can view the 1d spec with pypeit_show_spec1d, and all the QA plots came out fine. I can also manually load the 2d spec into ginga, it's only when the pypeit tools try to do it that it fails.  I can provide more details or copies of my files, I'm not sure what's going wrong or what would be useful, or if this is a known issue/I'm running something incorrectly.

**Comment by jhennawi** [comment]
Hi @lfinnert, 

By 2d spec, do you mean the spec2d_*.fits files? pypeit_view_fits does not run on those files. The right way to view the spec2d output is with pypeit_show_2dspec. It sounds like you are running that but getting an error. 

Can you confirm that you are launching ginga from the command line with

ginga --modules=RC

Thanks,
Joe

**Comment by lfinnert** [comment]
I'm launching ginga from the same directory with ginga --modules=RC.  Pypeit prints a message that it loaded a pre-existing master calibration frame, then crashes with the attached traceback.  Ginga prints that it's reading the header and an address/timestamp but nothing after that.

[pypeit_show_2dspec_traceback.txt](https://github.com/pypeit/PypeIt/files/3673704/pypeit_show_2dspec_traceback.txt)

**Comment by profxj** [comment]
outdated
