### ISSUE TITLE
Sort command in pypeit_setup appears to cause a crash for corrupted files with no MJD

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#779]
A test case is available for X-shooter. @profxj can you put the relevant files somewhere and link to this issue.

**Comment by profxj** [comment]
Line 1476 of `metadata.py` inserted by @jhennawi is causes the crash,
reproduced here:
``` 
subtbl.sort(['mjd']) # JFH added this line so that the output reads like a log file
```

Simply removing that line solves the problem as considered in PR #768.

`pypeit_setup` will no longer run on files with missing MJD in the header. 
This is a common occurrence with Keck data and therefore now a common
failure mode for PypeIt.

**Comment by profxj** [comment]
closing
