### ISSUE TITLE
LRIS Red det=2 long-slit tracing

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#792]
This illustrates a pernicious issue with slit tracing, specifically for det=2 Keck-LRIS red data (not the dev-suite data), but maybe more generally.

With the default threshold, below is an example of the edge detection and initial organization into slit edges (i.e., the result of `pypeit.edgetrace.EdgeTraceSet.initial_trace`):

![full_detect](https://user-images.githubusercontent.com/15785898/69104792-5f286180-0a1e-11ea-8d29-96542ec27a40.png)

The bottom of the image is masked by the BPM, so the edge gets rejected because it's too short.  The two "edges" near the actual slit edge are found because the slit illumination function has a steep increase at the slit edge before actually reaching the slit edge.  With the default detection threshold, the code interprets this as a left edge, just before hitting the actual right edge.  The other edge detections are because of bad pixel columns.  Here's a zoom in that shows the increase in intensity of the flat near the slit edge.

![zoom_detect](https://user-images.githubusercontent.com/15785898/69105055-145b1980-0a1f-11ea-9bd9-1618c3302ad5.png)

Note from the first image that the code detects two consecutive rights, so in the synchronization process it adds a left just after the actual slit edge.  Then it deletes the left and right edges near the actual slit edge because it's below the slit-length threshold.  So by the end, the code has defined two slits, neither of which actually contain the slit spectrum.

The quick fix for this was to change the threshold for edge detection.  I.e., I added:
```
[calibrations]
    [[slitedges]]
        edge_thresh = 1000
```
to the pypeit file.  Only the real slit edge meets this criterion so that the final slit tracing looks like this:

![full_good_final](https://user-images.githubusercontent.com/15785898/69105514-5b95da00-0a20-11ea-89d2-4ce421ff7f1e.png)

For now, this is just a failure mode that we need to be aware of, but there may be an algorithmic way of catching this.

**Comment by gterreran** [comment]
I had the same problem but with **LRIS blue**. It was struggling to find the edges of the det=2.
I tried edge_thresh = 1000 but apparently this was even too high!
I managed to make it work using edge_thresh = 500.

I'm using pypeit 0.12.3

**Comment by profxj** [comment]
I believe this has been addressed.
