### ISSUE TITLE
Non-ascii symbols in shooter standards table

### ISSUE THREAD

**Issue by felixbosco** [pypeit/PypeIt#809]
The file `pypeit/pypeit/data/standards/xshooter/xshooter_info.txt` contains an Angstrom symbol, which caused my `pypeit_setup` call to crash, as the `Table.read()` could not read this non-ASCII symbol. 

Apparently, this caused a crash only on my system, but it is probably worth to replace it by a regular A.

**Comment by feigewang** [comment]
Thanks. Changed finally.
