### ISSUE TITLE
standard star spec1d error

### ISSUE THREAD

**Issue by sarafina325** [pypeit/PypeIt#823]
I'm having an issue when running the `run_pypeit` command on some Kast data using Shane. Namely, I get the following error message:

```
[INFO]    :: Generating read noise image from detector properties and amplifier layout)
[INFO]    :: Generating raw variance frame (from detected counts [flat fielded])
[WARNING] :: No objects to extract for target bd284211
             On frames:
             r63.fits
             
[WARNING] :: No objects to save. Only writing spec2d files!
[INFO]    :: Wrote: /global/project/projectdirs/astro250/spectra/tmp/shane_kast_red_A/Science/spec2d_r63-bd284211_KASTr_2019Oct07T082405.030.fits

[ERROR]   :: Could not find standard file: /global/project/projectdirs/astro250/spectra/tmp/shane_kast_red_A/Science/spec1d_r46-bd284211_KASTr_2019Oct07T024713.630.fits
Traceback (most recent call last):
  File "/project/projectdirs/astro250/astro/bin/run_pypeit", line 4, in <module>
    __import__('pkg_resources').run_script('pypeit==0.12.2.dev0', 'run_pypeit')
  File "/project/projectdirs/astro250/astro/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/project/projectdirs/astro250/astro/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/global/project/projectdirs/astro250/astro/lib/python3.7/site-packages/pypeit-0.12.2.dev0-py3.7.egg/EGG-INFO/scripts/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/project/projectdirs/astro250/astro/lib/python3.7/site-packages/pypeit-0.12.2.dev0-py3.7.egg/pypeit/scripts/run_pypeit.py", line 93, in main
    pypeIt.reduce_all()
  File "/project/projectdirs/astro250/astro/lib/python3.7/site-packages/pypeit-0.12.2.dev0-py3.7.egg/pypeit/pypeit.py", line 290, in reduce_all
    std_outfile = self.get_std_outfile(frame_indx[is_standard])
  File "/project/projectdirs/astro250/astro/lib/python3.7/site-packages/pypeit-0.12.2.dev0-py3.7.egg/pypeit/pypeit.py", line 234, in get_std_outfile
    msgs.error('Could not find standard file: {0}'.format(std_outfile))
  File "/project/projectdirs/astro250/astro/lib/python3.7/site-packages/pypeit-0.12.2.dev0-py3.7.egg/pypeit/pypmsgs.py", line 264, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Could not find standard file: /global/project/projectdirs/astro250/spectra/tmp/shane_kast_red_A/Science/spec1d_r46-bd284211_KASTr_2019Oct07T024713.630.fits
```

This continues until I comment out each of my standards. At that point, I am only able to output spec2d files--no spec1d files are made, and presumably pypeit isn't able to use any standards for calibration. I'm linking an arc, standard, science, and flat for testing purposes.(r500.fits is a uv centering arc, r504.fits is an ir_focusing arc, r12.fits is a flat, r46.fits is science, and r44.fits is a standard.)

[https://drive.google.com/drive/folders/1IyreEeK3vTFHgQc5spqgkV3hFzgxXSjI?usp=sharing](https://drive.google.com/drive/folders/1IyreEeK3vTFHgQc5spqgkV3hFzgxXSjI?usp=sharing)

**Comment by jhennawi** [comment]
Hi Sarafina, 

I think there is a slight flaw in the logic. If you have a spec2d file, PypeIt won't remake them unless you run with -o --overwrite explicitly set which overwrites existing files. If there is a standard star in your 
reduction directory, then I believe pypeit will try to read it in, and is complaining when it is not there. 

So my suggestion is try to either remove the spec2d file of the standard star, or try running with the -o option, but this will then re-reduce everything in your pypeit file. 

Joe

**Comment by profxj** [comment]
@sarafina325 -- I downloaded your files and see the following issues:

1.  There is no flux in your flat frame.  r12.fits is a Bias not a Flat
2.  r504.fits is not useful for data reduction (it is only a focus frame)

If you want me to fuss further, I need a real Flat image.

**Comment by sarafina325** [comment]
@profxj thanks for pointing this out. I'm not sure why r12.fits was mislabeled in the .pypeit file as a Flat, thanks for catching! I just went through and made sure they're all correctly labeled. I uploaded a correct Flat image (r13.fits), and removed r504.fits. Let me know if you need anything else.

[https://drive.google.com/open?id=1IyreEeK3vTFHgQc5spqgkV3hFzgxXSjI](https://drive.google.com/open?id=1IyreEeK3vTFHgQc5spqgkV3hFzgxXSjI)

**Comment by profxj** [comment]
@sarafina325 -- Your files ran through just fine on the `develop` branch (`master` isn't compliant
with astropy 4.0).  The wavelength solution was poor because there was no Ar lamp on.  And there was no object found for the r47.fits exposure but I don't see anything by eye in that image either.  The standard start was extracted fine.

Bottom line:  I see nothing out of the ordinary here.

I'm attaching my PypeIt file where I modified the lamps to not include Ar.
Am closing this Issue.


[shane_kast_red_A.txt](https://github.com/pypeit/PypeIt/files/4171229/shane_kast_red_A.txt)
