### ISSUE TITLE
Not reducing all XS VIS science spectra

### ISSUE THREAD

**Issue by keheintz** [pypeit/PypeIt#827]
Hello, I have installed the most recent version of PypeIt from the Master branch today (Feb. 5, 2020) and tried to reduce X-shooter VIS arm spectra. The reduction appeared to run smoothly, but for some reason only one of the science spectra were reduced (out of 4). I get the following error message:

Traceback (most recent call last):
 File “//anaconda/envs/py36/bin/run_pypeit”, line 7, in <module>
  exec(compile(f.read(), __file__, ‘exec’))
 File “/Users/keheintz/PypeIt/bin/run_pypeit”, line 17, in <module>
  rtval = run_pypeit.main(args)
 File “/Users/keheintz/PypeIt/pypeit/scripts/run_pypeit.py”, line 93, in main
  pypeIt.reduce_all()
 File “/Users/keheintz/PypeIt/pypeit/pypeit.py”, line 309, in reduce_all
  std_outfile=std_outfile)
 File “/Users/keheintz/PypeIt/pypeit/pypeit.py”, line 424, in reduce_exposure
  std_outfile=std_outfile)
 File “/Users/keheintz/PypeIt/pypeit/pypeit.py”, line 579, in extract_one
  obstime=self.obstime)
 File “/Users/keheintz/PypeIt/pypeit/reduce.py”, line 265, in run
  manual_extract_dict=manual_extract_dict)
 File “/Users/keheintz/PypeIt/pypeit/reduce.py”, line 343, in find_objects
  manual_extract_dict=parse_manual, debug=debug)
 File “/Users/keheintz/PypeIt/pypeit/reduce.py”, line 959, in find_objects_pypeline
  show_trace=show_trace, debug=debug)
 File “/Users/keheintz/PypeIt/pypeit/core/extract.py”, line 1844, in ech_objfind
  sobjs.add_sobj(sobjs_slit)
 File “/Users/keheintz/PypeIt/pypeit/specobjs.py”, line 272, in add_sobj
  self.specobjs = np.append(self.specobjs, sobj)
 File “<__array_function__ internals>“, line 6, in append
 File “//anaconda/envs/py36/lib/python3.6/site-packages/numpy/lib/function_base.py”, line 4691, in append
  values = ravel(values)
 File “<__array_function__ internals>“, line 6, in ravel
 File “//anaconda/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py”, line 1797, in ravel
  return asanyarray(a).ravel(order=order)
 File “//anaconda/envs/py36/lib/python3.6/site-packages/numpy/core/_asarray.py”, line 138, in asanyarray
  return array(a, dtype, copy=False, order=order, subok=True)
 File “/Users/keheintz/PypeIt/pypeit/specobjs.py”, line 354, in __getattr__
  raise ValueError(“Empty specobjs”)
ValueError: Empty specobjs

Any ideas on possible fixes?
Thanks, Kasper

**Comment by profxj** [comment]
Addressed by PR #817 , right @keheintz ?
If so, kindly close this Issue.

**Comment by keheintz** [comment]
Exactly, thanks!
