### ISSUE TITLE
Add 'calibrations only' flag to run_pypeit

### ISSUE THREAD

**Issue by rcooke-ast** [pypeit/PypeIt#846]
It might be helpful to have a mode in `run_pypeit` that prepares all calibrations, and then exits.

This has several benefits that I can think of (there's probably more):
* It allows the user to confirm that the calibrations are all working correctly (perhaps on a run, when you can retake calibrations during the afternoon if some frames are crap).
* It would allow observers to reduce their science frames faster during the night (since the calibrations will be pre-processed).
* If there are GUI modes that a user wants to use before reducing the science frames (e.g. wavelength identification, or sky region selection) this operates as a safe exit.

**Comment by profxj** [comment]
Nearly ready-to-go in `calibs_only` branch

**Comment by kbwestfall** [comment]
Sorry, I thought I had mentioned that this is basically done in the `noplots` branch.  We'll need to consolidate.

**Comment by profxj** [comment]
Ah, ok.   Looks like the main things to keep from mine are changes to `Calibrations`
and my tests.

**Comment by profxj** [comment]
added
