### ISSUE TITLE
Consider subtracting by a dummy bias of zeros instead of using None

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#871]
This would simply aspects of the code at the expense of doing
an un-necessary and potentially confusing operation.

**Comment by profxj** [comment]
Consider the same for flats (i.e. unity values).

**Comment by kbwestfall** [comment]
As annoying as it is for book-keeping, I would rather that we avoid using these kind of dummy arrays because:
 - it takes time to allocate the memory
 - it increases the memory footprint
 - it takes time to do unnecessary operations that can be skipped with an if statement.

**Comment by profxj** [comment]
Dealt with.
