### ISSUE TITLE
Discrepancy between docs and code for 1d Coadd 

### ISSUE THREAD

**Issue by csnap001** [pypeit/PypeIt#880]
This may be addressed in issue #797 
There is a discrepancy between what is described in the documentation for 1d coadding spectra and what is required in the 1d coadd script. This is what is described when using 
pypeit_coadd_1dspec --help 

                        [coadd1d]
                           coaddfile='output_filename.fits'
                           sensfuncfile = 'sensfunc.fits' # Required only for Echelle
                        
                           coadd1d read
                             spec1dfile1 objid1
                             spec1dfile2 objid2
                             spec1dfile3 objid3
                                ...    
                           coadd1d end
                        
And it is suggested by the error messages that this should be a .coadd1d file.
But the documentation gives the following structure for a .yaml file:
'spectrograph': 'shane_kast_blue'
'filenames': ['spec1d_1.fits', 'spec1d_2.fits', 'spec1d_3.fits']
'a':
    'object': ['O290-S1592-D02-I0002', 'O457-S1592-D02-I0003
    ', 'O626-S1592-D02-I0004']
    'outfile': 'tmp.hdf5'

The documentation should be updated to reflect the new structure

**Comment by profxj** [comment]
How does this look:

https://github.com/pypeit/PypeIt/blob/spec_datamodels/doc/coadd1d.rst

Once PR #879 makes it to `master`, you'll see it on `readthedocs`

**Comment by csnap001** [comment]
Yes, that is clear, instructive, and helpful. Thank you.
