### ISSUE TITLE
extension_helpers dependency

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#890]
`pip install pypeit` leads to an installation that complains about the new dependency (`extension_helpers`) not being present.  `extension_helpers` is only needed to build the modules with the C backend.  I.e., it's not a "run-time" dependency of pypeit.  If pip can install and build the C libraries without `extension_helpers` being listed in the `requirements.txt` file, then maybe we should remove it from that file.  Otherwise, it would be nice if there was a way to have pip install packages that don't exist on the system, but not update any existing packages that are already present.

In the meantime, people will just need to make sure they have `extension_helpers`.

**Comment by profxj** [comment]
Now in docs.
