### ISSUE TITLE
pypeit_chk_edges should operate on SlitTrace not EdgeTrace

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#898]
The current show method in EdgeTrace is very complicated and does not label orders correctly, because this information is not known at the EdgeTrace stage. SlitTrace needs its own show method and that is what we should be calling with the script to view the masters, since this uses the correct slitord_id to label the slits/orders.

**Comment by kbwestfall** [comment]
I'm fine with whatever you want to do, but I don't have time to address this over the next ~month or more.  Regardless of where the method is, you'll still need to load EdgeTrace, or at least read its fits file, if you want the show method(s) to include the trace image and/or sobel-filtered image.
