### ISSUE TITLE
Bug in Data Container

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#934]
The DataContainer reader does not raise an exception if it is fed a file from a different data container. This seems like a bug. To reproduce it do the following on the attached file. 

from pypeit import specobjs
sobjs = specobjs.SpecObjs.from_fitsfile(‘pisco_coadd.fits’)

This should fault. Basically, I’m trying to read in a data container (SpecObj) from a file that contains a different data container (CoAdd1d).

This returns a junk specobj object full of booleans. 

What is the point of having a rigorous data model if there is no actual checking that the object in question  that you are trying to read in actually adheres to that model

Anyway, maybe the header of a data container written to disk needs to have  some knowledge of what data container it was and then when you read it in, you check that it is compatible. 

https://pypeit.slack.com/files/U5G88K072/F012P94TXKP/pisco_coadd.fits

**Comment by profxj** [comment]
@jhennawi -- Please provide the trace.  I'm betting it raised 
a warning and as we discussed we decided *not* to have it 
raise an error (same if the version type is not a match).

**Comment by profxj** [comment]
i.e.  am expecting the code is working as designed

**Comment by jhennawi** [comment]
There is no trace that is the whole point. I read in a Coadd1d file with a specobjs reader and I get a specobjs full of nonsense. If that is not a major bug I'm not sure what is?

**Comment by profxj** [comment]
Sorry, misspoke.  Provide what was printed to the terminal.

**Comment by jhennawi** [comment]
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison (arraysetops.py:569)

**Comment by kbwestfall** [comment]
Addressed by #958
