### ISSUE TITLE
Need a better representation for the SpecObjs data container

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#939]
Run the following code in the dev suite, on the develop branch of Pypeit. 

from pypeit import specobjs
sobjs = specobjs.SpecObjs.from_fitsfile('spec2d_b24-Feige66_KASTb_2015May20T041246.960.fits')    

Then type sobjs to see the representation. Screenshot attached. This is not particularly helpful. 

![Screen Shot 2020-05-18 at 10 54 18 AM](https://user-images.githubusercontent.com/8774563/82244338-f0a55d00-98f5-11ea-8e3b-5bcbf5ee487c.png)

**Comment by profxj** [comment]
closing
