### ISSUE TITLE
Cosmic rays in Master Bias

### ISSUE THREAD

**Issue by ConsueloAN** [pypeit/PypeIt#948]
By combining three Bias frames to the Keck LRIS red light (lines 47, 48, 49):
![pypeit_file](https://user-images.githubusercontent.com/52365185/84110222-78145680-a9f2-11ea-9b8d-706b00b707fc.png)
![LR 20170324 06849](https://user-images.githubusercontent.com/52365185/84110236-7ea2ce00-a9f2-11ea-83ce-c799e1432cb8.png)
![LR 20170324 06908](https://user-images.githubusercontent.com/52365185/84110245-806c9180-a9f2-11ea-9616-9d3e84c597fa.png)
![LR 20170324 06967](https://user-images.githubusercontent.com/52365185/84110248-819dbe80-a9f2-11ea-8fa6-f87cf603380d.png)
pypeit gives me a Master Bias where cosmic rays have not been removed properly.
![MasterBias_with_cosmics](https://user-images.githubusercontent.com/52365185/84110349-b0b43000-a9f2-11ea-81d8-3f8b5c88fb3b.png)
In the pypeit file I attempt to use a median as the Bias combination parameter, as follows:
![median](https://user-images.githubusercontent.com/52365185/84110382-c75a8700-a9f2-11ea-98d1-e36f2cd1689b.png)
This is the command line that I run and the first messages that the console gives:
![consola](https://user-images.githubusercontent.com/52365185/84110425-d9d4c080-a9f2-11ea-9657-015ed73f1bff.png)

**Comment by profxj** [comment]
I confirm that my Dev-Suite run on keck_lris_red_multi_600_5000_d560.pypeit shows cosmic rays in the MasterBias frames.

Am digging in.

**Comment by profxj** [comment]
Addressed by PR #950
