### ISSUE TITLE
[JOSS REVIEW] Installation questions

### ISSUE THREAD

**Issue by Gabriel-p** [pypeit/PypeIt#949]
Hi there I'm Gabriel one of the reviewers for the [Joss article](https://github.com/openjournals/joss-reviews/issues/2308). Some questions/comments:

1. In the [docs](https://pypeit.readthedocs.io/en/latest/installing.html) it is stated as a requirement:

> PyQT5 version 5 (needed for linetools)

Could you specify which version is required?

2.  `extension_helpers` should be `extension-helpers`.

3. By this:

> Use conda’s pip install to install the following:
>
> linetools – version 0.2 or later

do you mean "*use pip install inside the conda environment*"? What if the user is not using `conda`?

4. The packages in the docs do not match entirely those in the [requirements.txt](https://github.com/pypeit/PypeIt/blob/master/pypeit/requirements.txt) file:

* `packaging`: present in `requirements.txt`, not in the docs. Optional? For developers?
* `pytest`: present in `requirements.txt`, not in the docs. For developers? If so, is `h5py` also for developers as stated in that file?

5. There a re **a lot** of dependencies. Could you provide a single `conda` command to install those listed at the top of the docs, for convenience?

**Comment by profxj** [comment]
I had been assuming additional comments/requests were coming and was going to wait to address them all at once.  But let me know if you are waiting on us.  Thanks!

**Comment by Gabriel-p** [comment]
I'm waiting on you to answer these issues so I can move forward with the review.

**Comment by profxj** [comment]
Got it.  Will do so soon.

**Comment by profxj** [comment]
@Gabriel-p -- Have made these edits:

- Added `packaging` to the depenency list
- Added a verison for `PyQT5`
- Edited the `linetools` installation note
- Commented out `pytest` in the `requirements`

Note that `extension_helpers` is written correctly

Last, we are aiming to have a conda bundle and/or
a `docker` for distribution.  Also, a standard `pip` 
install with dependencies grabs everything, e.g.
`pip install -r path/requirements.txt`

Please continue with your review.

**Comment by Gabriel-p** [comment]
Hi again. The installation procedure is a bit confusing:

1. First you recommend to use `conda`, but give no one-line command to install all the dependencies (which is possible) or a `yaml` file with all the dependencies. Why is this? Could you provide one?
2. The possibility of using `pip install -r path/requirements.txt` is mentioned *after* the instructions to install `pypeit`. Shouldn't this be an alternative to the `conda` installation? Why is it located here?

**Comment by Gabriel-p** [comment]
3. **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
I guess this is covered by "*Python based data reduction pipeline (DRP) written oringinally for echelle spectroscopy and since expanded to low-resolution spectrometers*", but it could be expanded a bit with some more details. Also, notice the typo in "oringinally".

**Comment by profxj** [comment]
Hi @Gabriel-p,

We've cleaned up the installation instructions.  Here are some direct responses to your comments/questions:

>> First you recommend to use conda, but give no one-line command to install all the dependencies (which is possible) or a yaml file with all the dependencies. Why is this? Could you provide one?

We've added the `environment.yml` file to the top-level directory and provided a description how this is used in the installation page.

>> The possibility of using pip install -r path/requirements.txt is mentioned after the instructions to install pypeit. Shouldn't this be an alternative to the conda installation? Why is it located here?

Yes, we've cleaned up the organization of the installation page to hopefully make it clear that these are two separate paths to installation of the dependencies.  See further discussion with the other reviewer in #993 

>> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?  I guess this is covered by "Python based data reduction pipeline (DRP) written oringinally for echelle spectroscopy and since expanded to low-resolution spectrometers", but it could be expanded a bit with some more details. Also, notice the typo in "oringinally".

This is now described in the opening clause of the documentation:

```
``PypeIt`` is a Python package for semi-automated reduction of
astronomical, spectroscopic data. Its algorithms build on
decades-long development of previous data reduction pipelines by the
developers. The reduction procedure - including a complete list of
the input parameters and available functionality - is provided by
this online documentation.``PypeIt`` is a set of commands designed to perform the reduction
without any additional coding.This v1.1 release of ``PypeIt`` is designed to be used by both
advanced spectroscopists with prior data reduction expertise and
astronomers with no prior experience of data reduction. It is highly
configurable and designed to be applied to any standard slit-imaging
spectrograph, and can accommodate long-slit, multi-slit, as well as
cross-dispersed echelle spectra.
```

>> Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
>> The docs could be better organized. There are currently 54 entries at the main level, which makes navigating the docs somewhat of a hassle. Could this be better organized?

We have streamlined the menu options in the navigation bar.  We continue to improve the documentation and its readability guided by our expanded user base.  See #994 for further details.

>> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)
>> See point above. I can't tell if there is a clear example somewhere.

The front page of the new documentation provides a series of "Getting Started" links that point to examples for using the code.  In particular, see the PypeIt Cookbook and the "Step-by-step example" (https://github.com/pypeit/PypeIt/blob/joss-paper-branch/doc/step-by-step.rst).  Other sections below provide more detail on how to manipulate the control flow of the code.

>> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
>> Is this covered anywhere?

Yes, see the "Contributors" section of the front page.  We've also
improved the text that points out that we have a user-based slack
workspace and provide a link for submitting a GitHub issue.

**Comment by Gabriel-p** [comment]
Thank you for the detailed answer @profxj. I'll resume the reviewing as soon as possible

**Comment by Gabriel-p** [comment]
Hi @profxj, still can't move past the installing phase. Please see https://github.com/pypeit/PypeIt/issues/1019
