### ISSUE TITLE
EdgeTrace cannot handle an orphan echelle order

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#962]
There are several bugs I've discovered in EdgeTrace in trying to get what should be a very simple echelle setup to trace. 

Example data along with a README file are here: 

https://www.dropbox.com/s/gk54p672lsrkigr/gnirs_10_debug.tar.gz?dl=0

Just run pypeit_trace_eges - f pypeit_file

I've hacked this setup into working, but I think these bugs need to be addressed. 

Thanks

**Comment by kbwestfall** [comment]
Effectively addressed by #965 , but with some change in the pypeit parameters used.  I'll leave this open until after #965 is merged and I've added the solution here.
