### ISSUE TITLE
JOSS review: paper

### ISSUE THREAD

**Issue by astrom-tom** [pypeit/PypeIt#992]
Dear @profxj ,

First of all, sorry for the long delay for the review. I am opening few ticket related to the submission of your code to JOSS [https://github.com/openjournals/joss-reviews/issues/2308](url)

Here is the first one about the paper itself:

The paper is nicely written. I have a single remark about it: it could be useful to mention that pypeit is a set of commands design to perform the reduction (i.e. no need to know how to code in Python to use it).

**Comment by profxj** [comment]
Added in this commit:  https://github.com/pypeit/PypeIt/commit/315e54224125bd0cf23e1ef2b9b39258e63d5b37#diff-e2778e7674f45b806282a9611faa7220

**Comment by astrom-tom** [comment]
perfect thanks!
