### ISSUE TITLE
JOSS review: testing

### ISSUE THREAD

**Issue by astrom-tom** [pypeit/PypeIt#995]
Review of paper : [https://github.com/openjournals/joss-reviews/issues/2308
](url)
About testing:

What is the difference between [2-Run the PypeIt unit tests] and [3-Try the test suite]? It should be clearly stated. For the moment I ran only the [2-Run the PypeIt unit tests] but I would like to know if I need to run the [3-Try the test suite]?.

I tried to run the unit tests with 'python setup.py tests'. It complained about missing **numba, pytest, ginga and linetools**. This should be installed automatically during the pypeIt installation, please add it to the dependencies in the documentation AND in the setup.py.

Results: -----144 passed, 89 skipped, 536 warnings in 33.60s------

Then I cloned the dev suite. The tests gave me the following error:

```
Traceback (most recent call last):
  File "./pypeit_test", line 772, in <module>
    raise EnvironmentError('Enviroment must include PYPEIT_DEV, which points to the '
OSError: Enviroment must include PYPEIT_DEV, which points to the top-level directory with the dev-suite raw data.
```

Should this be taken care of with the installation? It is only after that I realised that the full instruction for running the dev suite is back on github! Please create a page with testing instruction on the documentation (see above). Downloading the data is not simple: The author proposes to use Google File stream which is not available to me ('To use Drive File Stream, you need to have a Google Account through work or school'). I will wait to have a clarification on the difference between [2-Run the PypeIt unit tests] and [3-Try the test suite] before running these tests.
@astrom-tom

**Comment by profxj** [comment]
The notes on testing have advanced considerably.  Please review the latest:
https://github.com/pypeit/PypeIt/blob/joss-paper-branch/doc/installing.rst

where you will see the test suite is only for Developers.  
We prefer not to provide additional information at this stage, 
in part because it is an evolving system.

If you think it is best (i.e. less confusing), we could remove those notes altogether.

**Comment by astrom-tom** [comment]
Hi @profxj ,

Thanks for the update! 

If the [Run the PypeIt unit tests] is enough to check that the functionalities are working correctly then I would remove the [Try running PypeIt on our extensive development test suite] section. Maybe just mention it in once sentence like 'A test suite for development purposes is available at [link]' at the end of [Run the PypeIt unit tests].

**Comment by profxj** [comment]
Good call @astrom-tom . Here it is updated:

https://github.com/pypeit/PypeIt/blob/joss-paper-branch/doc/installing.rst

The unit tests do test enough for a user to go forth.

**Comment by kbwestfall** [comment]
Hi @astrom-tom .  Just checking in on this.  Can we close this part of the review, or do you have additional requests/comments?

**Comment by profxj** [comment]
This Issue is related to JOSS review: openjournals/joss-reviews#2308

**Comment by astrom-tom** [comment]
Yes, I think this part can be closed. 
I reran all the tests with the latest version (with python setup.py test):
================== 153 passed, 86 skipped, 204 warnings in 24.10s ==============

Just as a side note (I guess you are aware of it) I got some warnings:

_Most of them are related to FITS header keywords, an example:_
   VerifyWarning: Keyword name 'FLEX_SHIFT_TOTAL' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. (card.py:263)

_A few like this as well:_
pypeit/tests/test_wvcalib.py: 24 warnings
   DeprecationWarning: tostring() is deprecated. Use tobytes() instead. (base.py:1555)

_One like this_:
pypeit/tests/test_arc.py::test_detect_lines
   OptimizeWarning: Covariance of the parameters could not be estimated (minpack.py:828)

pypeit/sampling.py:131
   DeprecationWarning: invalid escape sequence \l (sampling.py:131)
