### ISSUE TITLE
QA for 1D extraction

### ISSUE THREAD

**Issue by debora-pe** [pypeit/PypeIt#998]
It would be good to have QA for 1D extraction saved to disk for the users to check them. 

This is useful for manual extraction (to see if the input parameters are reasonable), but it's useful in general to check every extraction.

The QA showed with run_pypeit -s are already good (see attached). I would only add vertical lines showing the size of box_width and  opt_fwhm.
[1Dextraction.pdf](https://github.com/pypeit/PypeIt/files/5065758/1Dextraction.pdf)

**Comment by kbwestfall** [comment]
@debora-pe Is this done now?

**Comment by debora-pe** [comment]
Oh yeah! It's done!
Closing.
